// English, and the shape every other language file has to match.
//
// Keys are grouped by the surface they appear on rather than by page, because
// the same words show up on the activity page and in a reminder. Anything that
// interpolates a value is a function: word order moves between languages, and
// gluing strings together at the call site is how it gets frozen into English.

const en = {
	code: 'en',
	label: 'EN',
	nav: {
		home: 'Home',
		projects: 'Projects',
		activities: 'Activities',
		bills: 'Bills',
		servers: 'Servers',
		account: 'Account',
		signOut: 'Sign out',
		signIn: 'Sign in',
	},

	auth: {
		discord: 'Sign in with Discord',
	},

	bills: {
		eyebrow: 'Megu ledger',
		title: 'Your bills',
		lede: 'Start with the things you collect every month, then open a one-off bill whenever it needs work or another look.',
		signedOutTitle: 'Bills and monthly costs',
		signedOutLede: 'Sign in with Discord to see subscriptions, shared bills, and payments that still need your attention.',
		monthlyTitle: 'Monthly costs',
		monthlyLede: 'Subscriptions, internet, rent, and anything else the group comes back to every month.',
		oneOffTitle: 'One-off bills',
		oneOffLede: 'Meals, trips, and shared purchases — both bills in progress and ones already settled.',
		monthlyCount: n => `${n} ${n === 1 ? 'monthly item' : 'monthly items'}`,
		oneOffCount: n => `${n} one-off ${n === 1 ? 'bill' : 'bills'}`,
		open: 'Open bill',
		newBill: 'Add a bill',
		emptyMonthly: 'No monthly costs yet. Create one from Activities and choose “Every month”.',
		emptyOneOff: 'No one-off bills yet. Once an activity has an expense, it will appear here automatically.',
		status: {
			awaiting: n => `${n} ${n === 1 ? 'payment' : 'payments'} to confirm`,
			outstanding: (amount, n) => `${amount} due · ${n} ${n === 1 ? 'person' : 'people'}`,
			settled: 'This round is paid in full',
			notStarted: 'No balance in this round yet',
		},
		guestTitle: 'Friends can still open a bill from its link',
		guestBody: 'People who do not sign in can claim their name and see their share from the activity link. Megu reminds linked people through Discord and keeps the owner up to date on what remains.',
		loadFailed: 'Megu could not load your bills. You can try again now.',
		retry: 'Try again',
	},

	account: {
		title: 'Your account',
		eyebrow: 'Megu account',
		lede: 'Your Megu account connects to Discord to manage your servers and activities.',
		signInEyebrow: 'One account for your servers',
		signInHeadingBefore: 'Pick up every task',
		signInHeadingAccent: 'where Discord left it',
		signInTitle: 'Sign in to Megu',
		signInLede: 'Use your Discord account so Megu knows which servers you manage and can return you to the right work.',
		signInCardLede: 'Authorize through Discord once, then manage your servers, activities, and Megu settings right away.',
		signInManageTitle: 'Servers you manage',
		signInManageHint: 'Only servers where you have management access appear.',
		signInContinueTitle: 'Resume without losing context',
		signInContinueHint: 'Your activities, settings, and history stay together.',
		signInPrivacy: 'Megu requests only the Discord access needed to identify you and list the servers you manage.',
		profileHint: 'This is your default Megu name. Each activity can still use a different nameplate.',
		connectedTitle: 'Connected Discord account',
		connectedHint: 'This account identifies you and finds the servers you are allowed to manage.',
		providers: { google: 'Google', discord: 'Discord' },
		connected: 'Connected', notConnected: 'Not connected', connect: 'Connect', unlink: 'Unlink',
		lastIdentityHint: 'Keep at least one sign-in method connected.',
		unlinkConfirm: provider => `Unlink ${provider}?`,
		unlinked: 'Sign-in method unlinked.',
		noMergeNote: 'If a sign-in already belongs to another Megu account of yours, Megu offers to merge the two — after you have proved both. Nothing moves until you confirm.',
		linkConflict: 'That sign-in already belongs to a Megu account that cannot be merged with this one — a Megu account holds one sign-in per provider. Unlink the one connected here first. Nothing was changed.',
		linkSuccess: 'Sign-in method connected. You can now use either provider for this account.',
		profileSourceTitle: 'Profile name and picture',
		profileSourceHint: 'Use your Discord name and picture in Megu, or keep a name you set yourself.',
		profileSources: { google: 'Follow Google', discord: 'Follow Discord', manual: 'Keep what I typed' },
		profileSourceSaved: 'Profile source saved.',

		merge: {
			title: 'Merge these two accounts',
			lede: 'This sign-in belongs to another Megu account of yours. You have now proved both, so Megu can combine them into one.',
			checking: 'Working out what would move…',
			movesTitle: 'What moves',
			movesHint: 'Everything below moves to one account. Nothing is deleted, and no amount changes.',
			counts: {
				owned_activities: n => `${n} ${n === 1 ? 'activity you organise' : 'activities you organise'}`,
				participant_rows: n => `${n} ${n === 1 ? 'roster entry' : 'roster entries'}`,
				payments: n => `${n} ${n === 1 ? 'payment' : 'payments'}`,
				identities: n => `${n} ${n === 1 ? 'sign-in method' : 'sign-in methods'}`,
			},
			ledgerNote: 'Payment history is moved, never recalculated. What everybody owes stays exactly as it is.',
			duplicatesTitle: 'You will appear twice',
			duplicatesHint: 'Both accounts are on these activities. Megu keeps both roster entries, because combining them would mean adding two shares together — and that would change a settled ledger. Rename either one afterwards.',
			duplicatesIn: (title, code) => `${title} · ${code}`,
			notificationTitle: 'Notifications afterwards',
			notificationNote: mode => `Both channels you already use stay on: ${mode}. You can change this any time on this page.`,
			profileTitle: 'Which name and picture to keep',
			profileHint: 'This only changes the name and picture. Sign-in continues through Discord.',
			irreversible: 'A merge cannot be undone. Megu records who did it and tells both your email and your Discord, each naming the other.',
			confirm: 'Merge accounts',
			merging: 'Merging…',
			cancel: 'Cancel, change nothing',
			blocked: providers => `These accounts both use ${providers}, and one Megu account holds a single sign-in per provider. Unlink one first.`,
			expired: 'This merge request expired. Start again by connecting the sign-in from your account page.',
			done: 'Accounts merged. Both sign-ins now reach this one account.',
		},
		notificationsTitle: 'Activity notifications',
		notificationsHint: 'Choose where Megu sends payment and activity results. Email messages come from Megu, not from your Gmail account.',
		modes: { discord: 'Discord only', email: 'Email only', both: 'Discord + Email', off: 'Off' },
		modeHints: { discord: 'Send through the Megu Discord bot.', email: 'Send to your verified Google email.', both: 'Send an independent copy to each channel.', off: 'Do not send optional activity notifications.' },
		connectFirst: 'This channel is not available for this account.',
		savedState: 'Everything is up to date.',
		unsaved: 'Your notification settings have not been saved yet.',
		saved: 'Notification settings saved.',
	},

	servers: {
		signedOutTitle: 'Your Discord workspace',
		signedOutLede: 'Sign in to choose a server, manage Megu, or adjust your own voice and reminder preferences.',

		// This page is the Discord bot's console, not the activities half, so
		// being signed in to Megu with Google is not enough on its own — it needs
		// a Discord authorisation to know which servers you manage. Say which of
		// those is missing rather than showing "Sign in" to somebody who is.
		discordNeededTitle: 'This part needs Discord',
		discordNeededLede: 'This is the console for Megu’s Discord bot, so it needs your Discord account to know which servers you manage. The account you are signed in with has not connected Discord yet.',
		discordNeededAction: 'Connect Discord',
		discordExpiredTitle: 'Connect Discord again',
		discordExpiredLede: 'Your account has Discord connected, but Megu could not ask Discord for your server list — the permission has expired or been withdrawn. Connecting again puts it back.',
		discordExpiredAction: 'Reconnect Discord',
		workspaceEyebrow: 'Discord workspace',
		title: 'Choose where to work',
		lede: 'Open a server to manage Megu, or adjust your own preferences anywhere Megu is already active.',
		directoryEyebrow: 'Server directory',
		directoryTitle: 'Your Discord servers',
		summaryLabel: 'Server overview',
		activeSummary: 'with Megu',
		manageableSummary: 'you can manage',
		totalSummary: 'visible servers',
		botConnected: 'Live status connected',
		botUnavailable: 'Live status unavailable',
		activeCount: n => `${n} ${n === 1 ? 'server has' : 'servers have'} Megu`,
		missingCount: n => `${n} ${n === 1 ? 'server has' : 'servers have'} not invited Megu yet`,
		managedCount: n => `${n} ${n === 1 ? 'server' : 'servers'} you manage`,
		owner: 'Owner',
		manager: 'Manager',
		member: 'Member',
		unknown: 'Status unavailable',
		ready: 'Ready',
		notInstalled: 'Megu not installed',
		members: count => `${count} members`,
		serverId: id => `Server ID ${id}`,
		invite: 'Invite Megu',
		configure: 'Open workspace',
		mySettings: 'Open my settings',
		inviteHint: 'Add Megu to unlock welcome messages, moderation, voice tools, and more.',
		configureHint: 'Manage server-wide features, members, roles, safety, and voice tools.',
		personalHint: 'Manage the voice name and reminders that only apply to you here.',
		filterAll: 'All',
		filterManageable: 'I manage',
		filterMember: 'I’m a member',
		filterNeedsMegu: 'Needs Megu',
		filterLabel: 'Filter servers',
		searchLabel: 'Search servers',
		searchPlaceholder: 'Search by server name or ID',
		clearSearch: 'Clear server search',
		statusUnavailableTitle: 'Megu status is unavailable',
		statusUnavailableBody: 'The dashboard cannot currently verify which servers have Megu. Your server list is still available, and no server has been marked as missing.',
		statusUnavailableHelpBefore: 'This usually happens when',
		statusUnavailableHelpMiddle: 'runs alone or the bot is stopped. Run',
		statusUnavailableHelpAfter: 'to start the bot and website together.',
		loadingServers: 'Gathering your servers',
		loadingServersLede: 'Matching your Discord access with Megu’s current server state.',
		loadFailed: 'Megu could not load your server list.',
		loadFailedTitle: 'Your servers did not load',
		retry: 'Try again',
		emptyTitle: 'No shared servers yet',
		emptyLede: 'When you share a Discord server with Megu—or can invite Megu to one—it will appear here.',
		emptyFilteredTitle: 'No servers match this view',
		emptyFilteredLede: 'Try another name, server ID, or permission filter.',
		clearFilters: 'Clear filters',
		backToServerList: 'All servers',
		accessForbiddenTitle: 'This workspace is not available to you',
		accessForbiddenLede: 'Megu could not confirm that you still belong to this server. Return to your server list to choose another workspace.',
		backToServerSelector: 'Return to your servers',
		fallbackServerName: 'Discord server',
		loadingServer: 'Opening server workspace',
		loadingServerLede: 'Loading server tools and the settings Megu already uses.',
		loadServerFailed: 'Megu could not load this server workspace.',
		loadServerFailedTitle: 'This server did not load',
		adminWorkspace: 'Server workspace',
		memberWorkspace: 'Your space in this server',
		meguConnected: 'Megu is connected',
		meguUnavailable: 'Megu status unavailable',
		quickSwitch: 'Switch server',
		channelsLabel: 'Channels',
		rolesLabel: 'Roles',
		membersLabel: 'Members loaded',
		workspaceStatusLabel: 'Changes',
		savedShort: 'Up to date',
		unsavedShort: 'Unsaved',
		personalEyebrow: 'Personal preferences',
		personalWorkspaceTitle: 'Make Megu work for you',
		personalWorkspaceLede: 'These choices affect only your experience in this server and never change server-wide settings.',
		navigationLabel: 'Server tools',
		toolsEyebrow: 'Workspace navigation',
		toolsTitle: 'Server tools',
		searchToolsLabel: 'Search server tools',
		searchToolsPlaceholder: 'Find a tool',
		noToolsFound: 'No tools match that search.',
		clearToolSearch: 'Clear search',
		currentToolLabel: 'Current tool',
		serverDetails: 'Server details',
		serverDetailsDescription: 'Counts reflect the server data available when this workspace loaded.',
		serverIdentifier: 'Server ID',
		meguPresent: 'Megu is in this server',
		noPendingChanges: 'No pending changes in this tool',
		settingsSaved: 'Server settings saved.',
		saveFailed: 'Megu could not save these settings. Your changes are still on this page.',
		partialSaveFailed: 'Some server settings were saved, but others still need attention. Review the remaining changes and try again.',
		changesDiscarded: 'Unsaved changes discarded.',
		leaveUnsaved: 'Leave this server without saving your changes?',
		unsavedTitle: 'Changes ready to save',
		unsavedLede: 'These server-wide settings are staged until you save them.',
		pendingTools: tools => `${Array.isArray(tools) && tools.length ? `Pending in: ${tools.join(', ')}` : `Server settings have pending changes${tools ? ` (${tools})` : ''}`}.`,
		discardChanges: 'Discard',
		saveChanges: 'Save changes',
		savingChanges: 'Saving…',
		leaveDialogTitle: 'Save your server changes?',
		leaveDialogDescription: 'You have server-wide settings that have not been saved yet.',
		leaveLocalDraftTitle: 'Leave with an unfinished draft?',
		leaveLocalDraftDescription: 'Unsent editor drafts cannot be saved by the server settings action. Stay to keep working, or discard them before leaving.',
		switchDraftTitle: 'Discard this unfinished edit?',
		switchDraftDescription: 'This editor keeps its work while you stay here. Switching tools will discard it.',
		discardAndSwitch: 'Discard and switch',
		stayHere: 'Stay here',
		discardAndLeave: 'Discard and leave',
		saveAndLeave: 'Save and leave',
		saveServerOnly: 'Save server settings',
		pendingLocalDrafts: tools => `Unsent draft in: ${Array.isArray(tools) ? tools.join(', ') : tools}.`,
		tabGroups: {
			community: 'Community',
			people: 'People & roles',
			safety: 'Safety',
			voice: 'Voice & audio',
			tools: 'Tools',
			you: 'You',
		},
		tabs: {
			personal: 'My preferences',
			welcome: 'Welcome & goodbye',
			autorole: 'Automatic roles',
			roles: 'Roles',
			members: 'Members',
			nicknames: 'Nicknames',
			tts: 'Voice TTS',
			honeypot: 'Honeypot protection',
			automod: 'Auto moderation',
			reactionroles: 'Reaction Roles',
			audioqueue: 'Audio queue',
			audit: 'Activity history',
			embeds: 'Message builder',
		},
		tabDescriptions: {
			personal: 'Choose how Megu speaks your name and sends your reminders in this server.',
			welcome: 'Shape the first and final messages members receive.',
			autorole: 'Give new members and bots the right roles automatically.',
			roles: 'Create, edit, order, and remove Discord roles.',
			members: 'Find members and update their assigned roles.',
			nicknames: 'Review and update server nicknames in one place.',
			tts: 'Configure text-to-speech channels, voices, and speaking rules.',
			honeypot: 'Catch suspicious accounts with a protected trap channel.',
			automod: 'Reduce spam, unsafe links, mass mentions, and blocked words.',
			reactionroles: 'Let members assign their own roles from message reactions.',
			audioqueue: 'Monitor, test, and manage the server’s current audio queue.',
			audit: 'Review recent moderation, configuration, and member events.',
			embeds: 'Compose and send a structured message to a server channel.',
		},
		tabSearchAliases: {
			personal: ['preferences', 'reminders', 'nickname'],
			welcome: ['join', 'goodbye', 'leave', 'greeting'],
			autorole: ['new member', 'bot role'],
			roles: ['permissions', 'role order'],
			members: ['users', 'people'],
			nicknames: ['display name', 'rename'],
			tts: ['speech', 'voice channel', 'greeting'],
			honeypot: ['trap', 'suspicious accounts'],
			automod: ['spam', 'invite', 'blocked words'],
			reactionroles: ['self roles', 'emoji'],
			audioqueue: ['playback', 'sound'],
			audit: ['logs', 'events', 'history'],
			embeds: ['message', 'publish'],
		},
		welcomeEditor: {
			intro: 'Preview both messages here before saving the server settings.',
			welcomeTab: 'Welcome',
			goodbyeTab: 'Goodbye',
			unsaved: 'Unsaved changes',
			welcomeConfigured: 'Welcome configured',
			welcomeOff: 'Welcome off',
			goodbyeConfigured: 'Goodbye configured',
			goodbyeOff: 'Goodbye off',
			destinationTitle: 'Destination',
			destinationWelcome: 'Choose where Megu welcomes new members. Select None to turn this message off.',
			destinationGoodbye: 'Choose where Megu posts when a member leaves. Select None to turn this message off.',
			channelLabel: 'Discord channel',
			channelPlaceholder: 'Choose a channel',
			disabledChannel: 'None / disabled',
			unavailableSelection: 'Unavailable channel',
			noChannels: 'No eligible text channels are available in the server data that loaded.',
			messageTitle: 'Message',
			messageDescription: 'Write the message and check the local example before saving.',
			textMode: 'Text message',
			embedMode: 'Rich embed',
			formatLabel: 'Message format',
			messageLabel: 'Message template',
			titleLabel: 'Embed title',
			descriptionLabel: 'Embed description',
			insertVariable: 'Insert a variable',
			appearance: 'Optional appearance',
			accentColor: 'Accent color',
			thumbnailUrl: 'Thumbnail URL',
			bannerUrl: 'Banner image URL',
			footerText: 'Footer text',
			includeTimestamp: 'Include timestamp',
			previewTitle: 'Example preview',
			previewNote: 'Uses example member and count values. Nothing is sent to Discord.',
			exampleMember: 'NewMember',
			exampleDepartedMember: 'DepartedMember',
			exampleTime: 'Today at 12:00',
		},
	},

	personalSettings: {
		tabTitle: 'Personal Settings',
		headerSubtitle: 'Customize your personal experience for this server. These settings only apply to you and don’t require admin rights.',
		ttsNickTitle: 'TTS Spoken Nickname',
		ttsNickDesc: 'Customize how Megu speaks your name in voice channels and announcements in this server.',
		ttsNickPlaceholder: 'e.g. Alice, Bob',
		ttsNickCurrent: 'Current TTS Nickname',
		ttsNickDefault: 'Not set (using Discord name)',
		ttsNickSave: 'Save Nickname',
		ttsNickReset: 'Reset to Default',
		ttsNickSaved: 'Custom TTS nickname saved.',
		ttsNickResetDone: 'TTS nickname reset to default.',
		announceTitle: 'Voice Channel Announcement',
		announceDesc: 'Choose whether Megu announces your name out loud when you join or leave a voice channel in this server.',
		announceStatusActive: 'Announcing (Sound On)',
		announceStatusMuted: 'Muted (Silent)',
		announceToggleOn: 'Announce my arrival and departure',
		announceToggleOff: 'Stay silent when joining or leaving',
		announceSaved: 'Voice announcement preference updated.',
		remindersTitle: 'Your Reminders in this Server',
		remindersDesc: 'Active reminders scheduled to ping you in this server.',
		remindersEmpty: 'No active reminders in this server yet.',
		reminderNewBtn: '+ Set Reminder',
		reminderModalTitle: 'Set a New Reminder',
		reminderMessageLabel: 'Reminder Message',
		reminderMessagePlaceholder: 'What should Megu remind you about?',
		reminderTimeLabel: 'When to remind',
		reminderTimePlaceholder: 'e.g. 10m, 2h, 1d, 18:00 everyday',
		reminderTimeHint: 'Supports relative time (e.g. 10m, 1h, 2d) or everyday time (e.g. 15:00 everyday).',
		reminderTimezoneHint: 'Daily times use Indochina Time (UTC+7). One-time reminders show in your device timezone after they are scheduled.',
		personalScope: 'These actions save only your preferences for this server.',
		reminderChannelLabel: 'Notification Channel',
		reminderChannelSelect: 'Select a text channel',
		reminderChannelHint: 'Megu will mention you in this channel when the time arrives.',
		reminderCreateBtn: 'Create Reminder',
		reminderCancelBtn: 'Cancel',
		reminderCreated: 'Reminder scheduled successfully.',
		reminderDeleted: 'Reminder deleted.',
		reminderDeleteConfirm: 'Are you sure you want to delete this reminder?',
		recurringBadge: 'Daily',
		oneOffBadge: 'Once',
		targetTime: 'Scheduled for',
		deleteBtn: 'Delete',
		dueNow: 'Due now',
		inSeconds: s => `in ${s}s`,
		inMinutes: m => `in ${m}m`,
		inHoursMinutes: (h, m) => `in ${h}h ${m}m`,
		inDays: d => `in ${d}d`,
		inChannel: ch => `in ${ch}`,
		loadError: 'Failed to load personal settings.',
		saveNickError: 'Failed to save nickname.',
		saveAnnounceError: 'Failed to update announcement preference.',
		saveReminderError: 'Failed to set reminder.',
		deleteReminderError: 'Failed to delete reminder.',
	},

	serverTabs: {
		shared: {
			selectOption: 'Select an option', unavailableSelection: 'Unavailable selection', searchOptions: 'Search options', searchOptionsPlaceholder: 'Search options…', noMatchingOptions: 'No matching options',
			working: 'Working…', cancel: 'Cancel', save: 'Save', delete: 'Delete', remove: 'Remove', edit: 'Edit', refresh: 'Refresh', retry: 'Retry', clearFilters: 'Clear filters', previous: 'Previous', next: 'Next', paginationLabel: 'Pagination', closeDialog: 'Close dialog', immediateImpact: 'This action affects the current Discord server immediately.', unknownMember: 'Unknown member', unknownUsername: 'unknown', bot: 'Bot',
			unavailableRole: id => `Unavailable role · ${id}`,
			unavailableChannel: id => `Unavailable channel · ${id}`,
			loadedMatches: count => `${count} matching loaded results`,
			showing: (start, end, total) => `Showing ${start}–${end} of ${total}`,
		},
		autorole: {
			scope: 'Saved with server settings', available: count => `${count} roles available`, configured: count => `${count} automatic assignments configured`,
			humansTitle: 'New human members', humansDescription: 'Choose roles Megu assigns when a human member joins.', humansSelect: 'Add a human member role', humansPlaceholder: 'Choose a role', humansEmpty: 'Choose roles to assign when a human member joins.',
			botsTitle: 'New bot accounts', botsDescription: 'Choose roles Megu assigns when a bot integration joins.', botsSelect: 'Add a bot account role', botsPlaceholder: 'Choose a role', botsEmpty: 'Choose roles to assign when a bot account joins.',
			removeRole: name => `Remove ${name}`,
		},
		automod: {
			scope: 'Saved with server settings', enabled: count => `${count} detection rules enabled`,
			rulesTitle: 'Detection rules', rulesDescription: 'Enable only the checks this community needs.',
			spam: 'Rapid message spam', spamHelp: 'Detect repeated messages sent in a short period.', invite: 'Unauthorized invites', inviteHelp: 'Block Discord invitation links.', words: 'Blocked words and phrases', wordsHelp: 'Match messages against your custom block list.', mentions: 'Mass mentions', mentionsHelp: 'Block messages that mention more than five members.',
			blockList: 'Words or phrases', blockListHelp: 'Separate entries with commas. Matching follows the existing moderation rules.', blockListPlaceholder: 'blocked phrase, another phrase',
			responseTitle: 'Response to violations', responseDescription: 'This response applies to every enabled detection rule.', responseLabel: 'Action after a violation', deleteMessage: 'Delete message', warnMember: 'Warn member', timeoutMember: 'Timeout member', kickMember: 'Kick member', banMember: 'Ban member', consequence: 'Kick and ban remove a member from the server immediately when the configured rule is enforced.',
		},
		honeypot: {
			scope: 'Saved with server settings', title: 'Decoy channel', description: 'Choose one channel that legitimate members should never use.', label: 'Honeypot channel', placeholder: 'Choose a decoy channel', disabled: 'Disabled', active: name => `Draft destination: #${name}`, inactive: 'Draft is disabled', warningTitle: 'High-impact automation', warning: 'Posting in this channel triggers the existing honeypot enforcement. Confirm the channel and bot permissions before saving.',
		},
		tts: {
			voices: { thaiMale: 'Thai male — Niwat Neural', thaiFemale: 'Thai female — Premwadee Neural', englishFemale: 'English female — Jenny Neural', englishMale: 'English male — Christopher Neural', japaneseFemale: 'Japanese female — Nanami Neural', koreanFemale: 'Korean female — SunHi Neural' },
			scope: 'Saved with server settings', destinationTitle: 'Text channel', destinationDescription: 'Choose where messages are converted to speech.', channelLabel: 'Dedicated TTS text channel', channelPlaceholder: 'Choose a text channel', disabled: 'Disabled',
			voiceTitle: 'Voice and speech', voiceDescription: 'Choose the default voice and speaking behavior.', voiceLabel: 'Default language and voice', voicePlaceholder: 'Choose a voice',
			engine: 'Speech engine', edgeEngine: 'Microsoft Edge neural voices', googleEngine: 'Google Translate speech',
			greetingsTitle: 'Greetings and announcements', greetingsDescription: 'Control what Megu says when people move through voice channels.', roomGreeting: 'Greet the room when Megu joins', roomGreetingHelp: 'Speak once when Megu joins an occupied voice channel.', afkBringback: 'Follow members back from AFK', afkBringbackHelp: 'When a previous speaker returns from the server AFK channel, Megu follows them to their voice channel.', joinAnnouncement: 'Announce when a member joins voice', joinAnnouncementHelp: 'Speak when a member connects to a voice channel.', leaveAnnouncement: 'Announce when a member leaves voice', leaveAnnouncementHelp: 'Speak when a member disconnects from a voice channel.', messageLabel: 'Message template', variables: 'Message variables',
			limitsTitle: 'Limits and behavior', limitsDescription: 'Keep speech useful and prevent unusually long messages.', antiSpam: 'TTS rate limit', antiSpamHelp: 'Throttle repeated speech requests from the same member.', burst: 'Messages before throttling', burstHelp: 'Maximum requests inside the cooldown window.', cooldown: 'Cooldown window', cooldownHelp: 'Seconds before the member’s request count resets.', characters: 'Maximum spoken characters', charactersHelp: value => `${value} characters per message`, ignorePrefix: 'Ignore command messages', ignorePrefixHelp: 'Skip messages beginning with common command prefixes such as !, ?, -, /, or .',
		},
		reactionRoles: {
			count: count => `${count} mappings`, add: 'Add reaction role', existingTitle: 'Existing mappings', existingDescription: 'Each mapping updates Discord immediately.', emptyTitle: 'No reaction roles yet', emptyDescription: 'Add a mapping so members can choose a role from a message reaction.',
			formTitle: 'New reaction role', formDescription: 'Provide a Discord message and the role assigned by its reaction.', message: 'Message link or ID', messagePlaceholder: 'Paste a Discord message link or ID', channel: 'Target channel', channelPlaceholder: 'Choose a channel when using a message ID', resolvedChannel: name => `Resolved from link: #${name}`, emoji: 'Reaction emoji', emojiPlaceholder: 'Example: ⭐', role: 'Assigned role', rolePlaceholder: 'Choose a role', mode: 'Reaction behavior', toggle: 'Toggle role', addOnly: 'Add only', removeOnly: 'Remove only', submit: 'Add reaction role', effect: 'This saves the mapping and asks Megu to add the reaction on Discord.', close: 'Close form', clearAll: 'Clear all mappings', clearTitle: 'Clear every reaction role?', clearDescription: 'This removes every configured mapping from this server.', enabled: 'Enabled', disabled: 'Disabled', enable: 'Enable', disable: 'Disable', messageId: 'Message ID', status: 'Status', actions: 'Actions',
			requiredError: 'Enter a message link or ID, emoji, and assigned role.', channelError: 'Choose a target channel or paste a complete Discord message link.', serverError: 'That message link belongs to another server.', channelConflictError: 'The selected channel does not match the pasted message link.', addSuccess: 'Reaction role added on Discord.', addError: 'Could not add the reaction role.', updateSuccess: 'Reaction role status updated.', updateError: 'Could not update the reaction role.', removeSuccess: 'Reaction role removed.', removeError: 'Could not remove the reaction role.', clearSuccess: 'All reaction roles were removed.', clearError: 'Could not clear the reaction roles.',
		},
		members: {
			count: count => `${count} members loaded`, search: 'Search members', searchPlaceholder: 'Name, username, or user ID', filter: 'Member type', all: 'All members', humans: 'Humans', bots: 'Bots', sort: 'Sort', nameAsc: 'Name A–Z', nameDesc: 'Name Z–A', idAsc: 'User ID ascending', idDesc: 'User ID descending', rolesDesc: 'Most roles', perPage: 'Members per page', member: 'Member', roles: 'Roles', actions: 'Actions', manage: 'Manage roles', showAll: count => `Show all ${count} roles`, showLess: 'Show fewer roles', copyId: 'Copy user ID', copied: 'Copied', emptyTitle: 'No matching members', emptyDescription: 'Change the current search or filters.', editorTitle: name => `Manage roles for ${name}`, editorDescription: 'Select the roles this member should have.', roleSearch: 'Search roles', changes: (added, removed) => `${added} to add · ${removed} to remove`, apply: 'Apply roles', refreshSuccess: 'Member roster refreshed.', updateSuccess: name => `Roles updated for ${name}.`, updateError: 'Could not update this member’s roles.', unexpectedError: 'The server returned an unexpected response.',
			managedRoleReason: 'Discord or an integration manages this role.', everyoneRoleReason: 'The base server role cannot be assigned or removed here.', hierarchyRoleReason: 'Megu cannot manage roles at or above its highest role.',
		},
		roles: {
			count: count => `${count} server roles`, search: 'Search roles', searchPlaceholder: 'Role name or ID', create: 'Create role', role: 'Role', properties: 'Properties', actions: 'Actions', hoisted: 'Shown separately', mentionable: 'Mentionable', managed: 'Managed by integration', everyone: 'Base server role', noProperties: 'Standard role', emptyTitle: 'No matching roles', emptyDescription: 'Change the search or create a new role.', createTitle: 'Create role', editTitle: name => `Edit ${name}`, name: 'Role name', namePlaceholder: 'Example: Moderator', color: 'Role color', display: 'Display separately from online members', allowMentions: 'Allow anyone to mention this role', createAction: 'Create role', saveAction: 'Save role', deleteAction: 'Delete role', deleteTitle: name => `Delete ${name}?`, deleteDescription: 'This removes the role from the current Discord server.', managedReason: 'Discord manages this role, so it cannot be edited here.', everyoneReason: 'Discord requires the base server role, so it cannot be edited or deleted here.', pageSize: 'Rows per page', copyId: 'Copy role ID', copied: 'Copied', required: 'Enter a role name.', createSuccess: name => `${name} was created.`, createError: 'Could not create the role.', updateSuccess: name => `${name} was updated.`, updateError: 'Could not update the role.', deleteSuccess: name => `${name} was deleted.`, deleteError: 'Could not delete the role.',
			restricted: 'Above Megu’s role', hierarchyReason: 'Megu cannot edit or delete roles at or above its highest role.',
		},
		nicknames: {
			count: count => `${count} members loaded`, description: 'Spoken names change how Megu reads a member’s name; they do not change the Discord profile.', search: 'Search members', searchPlaceholder: 'Name, spoken name, or user ID', filter: 'Nickname state', all: 'All members', custom: 'Custom spoken name', default: 'Uses Discord name', humans: 'Humans', bots: 'Bots', sort: 'Sort', customFirst: 'Custom names first', nameAsc: 'Name A–Z', nameDesc: 'Name Z–A', idAsc: 'User ID ascending', idDesc: 'User ID descending', perPage: 'Members per page', member: 'Member', discordName: 'Discord name', spokenName: 'Custom spoken name', actions: 'Actions', none: 'Uses Discord name', edit: 'Edit spoken name', reset: 'Reset to Discord name', input: 'Spoken name', inputPlaceholder: 'How Megu should pronounce this name', save: 'Save spoken name', emptyTitle: 'No matching members', emptyDescription: 'Change the search or filter.', copyId: 'Copy user ID', copied: 'Copied', required: 'Enter a spoken name.', tooLong: 'Spoken names must be 100 characters or fewer.', saveSuccess: name => `Spoken name saved for ${name}.`, saveError: 'Could not save the spoken name.', resetSuccess: name => `${name} now uses their Discord name.`, resetError: 'Could not reset the spoken name.', refreshSuccess: 'Spoken names and members refreshed.', loadError: 'Could not load spoken names.',
		},
		audio: {
			queueTab: 'Queue', historyTab: 'History', tabsLabel: 'Audio queue views', playing: 'Playing', idleStatus: 'Idle', waiting: count => `${count} waiting`, events: count => `${count} events`, destination: name => `Playback destination: ${name.startsWith('#') ? name : `#${name}`}`, destinationUnknown: 'Playback uses Megu’s currently connected voice channel.',
			nowPlaying: 'Now playing', nowPlayingDescription: 'Current server playback and its requester.', idle: 'Nothing is playing', idleDescription: 'Add a spoken message or sound when Megu is connected to a voice channel.', upcoming: 'Upcoming audio', upcomingDescription: 'Waiting items play in this order.', emptyQueue: 'The audio queue is empty', emptyQueueDescription: 'There are no clips waiting after the current item.',
			skip: 'Skip current item', clear: 'Clear queue', clearTitle: 'Clear the audio queue?', clearDescription: 'This removes every waiting item from the current server queue.', addTitle: 'Add to queue', addDescription: 'Choose a supported spoken message or preset sound.', addTts: 'Add spoken message', addSound: 'Add sound', immediate: 'These actions affect server playback immediately.',
			historyTitle: 'Playback history', historyDescription: 'Search the most recently loaded audio events.', search: 'Search history', searchPlaceholder: 'Speaker or spoken text', status: 'Status', all: 'All statuses', noHistory: 'No history matches the current filters', noHistoryDescription: 'Change the search or status filter.', stale: 'The last refresh failed. Showing previously loaded data.',
			timestamp: 'Time', speaker: 'Speaker', type: 'Engine / type', content: 'Sound / spoken content', system: 'System', untitledAudio: 'Untitled audio', requestedBy: name => `Requested by ${name}`, soundType: 'Sound preset', neuralVoice: 'Neural voice', googleVoice: 'Google Standard', unknownType: 'Unknown type',
			ttsDialogTitle: 'Add a spoken message', soundDialogTitle: 'Add a preset sound', spokenText: 'Spoken message', spokenTextPlaceholder: 'Type the message Megu should speak', engine: 'Speech engine', voice: 'Voice model', sender: 'Sender display name (optional)', senderPlaceholder: 'Dashboard Admin', soundPreset: 'Sound preset', enqueueTts: 'Add spoken message', enqueueSound: 'Add sound',
			voiceOption: (name, gender, language) => `${name} (${gender}, ${language})`, genders: { male: 'Male', female: 'Female' }, languages: { thai: 'Thai', english: 'English', japanese: 'Japanese' }, edgeVoice: 'Edge neural voice', fallbackVoice: 'Fallback voice',
			soundNames: { ball_megu: 'Ball Megu', lingangu: 'Lin Gan Gu', megatron: 'Megatron', megu_racist: 'Megu Racist', momoi: 'Momoi Racist', phone: 'Your Phone Is Ringing', smort: '9999 IQ', viktor: 'Viktor', wolf: 'Wolf', spinning_cat: 'OIIA OIIA (Spinning Cat)' },
			queueLoading: 'Loading the current audio queue', historyLoading: 'Loading playback history', queueLoadError: 'Could not refresh the audio queue.', historyLoadError: 'Could not refresh playback history.', textRequired: 'Enter a message to speak.', soundRequired: 'Choose a sound preset.', skipSuccess: 'Current audio skipped.', skipError: 'Could not skip the current audio.', removeSuccess: 'Queue item removed.', removeError: 'Could not remove the queue item.', clearSuccess: 'Audio queue cleared.', clearError: 'Could not clear the audio queue.', addTtsSuccess: 'Spoken message added to the queue.', addTtsError: 'Could not add the spoken message.', addSoundSuccess: 'Sound added to the queue.', addSoundError: 'Could not add the sound.',
			statuses: { PLAYING: 'Playing', COMPLETED: 'Completed', ENQUEUED: 'Queued', SKIPPED: 'Skipped', REMOVED: 'Removed', ERROR: 'Playback error', CLEARED: 'Queue cleared' },
		},
		embeds: {
			imageUnavailable: 'Preview image unavailable',
			scope: 'Sends to Discord immediately', coreTitle: 'Message content', coreDescription: 'Write the title, description, and fields members should read.', title: 'Title', titlePlaceholder: 'Server announcement', description: 'Description', descriptionPlaceholder: 'Write the embed message', fields: 'Fields', addField: 'Add field', fieldName: 'Field name', fieldValue: 'Field value', inline: 'Show inline', removeField: 'Remove field', fieldLabel: index => `Field ${index}`, appearance: 'Appearance and media', appearanceHelp: 'Optional author, links, color, images, footer, and timestamp.', authorName: 'Author name', authorIcon: 'Author icon URL', authorUrl: 'Author link URL', titleUrl: 'Title link URL', color: 'Accent color', thumbnail: 'Thumbnail URL', image: 'Main image URL', footer: 'Footer text', footerIcon: 'Footer icon URL', timestamp: 'Include the current timestamp', destinationTitle: 'Destination and send', destinationDescription: 'Confirm the current server and channel before sending.', server: 'Server', channel: 'Text channel', channelPlaceholder: 'Choose a text channel', send: 'Send embed', sending: 'Sending…', preview: 'Local preview', previewHelp: 'Approximate Discord appearance. Nothing is sent until you choose Send embed.', emptyPreview: 'Add message content to see the local preview.', untitledField: 'Untitled field', fieldLimit: 'Discord embeds support up to 25 fields.', destinationError: 'Choose a target text channel.', contentError: 'Add a title, description, image, author, or complete field.', incompleteFields: 'Complete or remove every partially filled field before sending.', sendSuccess: 'Embed sent to the selected Discord channel.', sendError: 'Could not send the embed.', deliveryUnknown: 'Delivery could not be confirmed. Check Discord before trying again.',
			totalLimit: 'Discord embeds can contain up to 6,000 text characters in total.',
		},
		audit: {
			count: count => `${count} events loaded`, description: 'Search applies to the 150 most recently loaded events.', search: 'Search activity', searchPlaceholder: 'Actor, action, target, or details', type: 'Event type', all: 'All events', time: 'Time', actor: 'Actor', action: 'Action', details: 'Target and details', system: 'System', emptyTitle: 'No matching events', emptyDescription: 'Change the search or event filter.', loadError: 'Could not load recent activity.',
			eventTypes: { MESSAGE_DELETE: 'Deleted messages', MEMBER_BAN: 'Bans and unbans', MEMBER_KICK: 'Member kicks', MEMBER_TIMEOUT: 'Member timeouts', MEMBER_UPDATE: 'Member changes', ROLE_ASSIGN: 'Role assignments', ROLE_UPDATE: 'Role changes', CHANNEL_UPDATE: 'Channel changes', INVITE_CREATE: 'Invite changes', AUTOMOD: 'Auto moderation', WELCOME_LEAVE: 'Welcome and goodbye', VOICE_TTS: 'Voice TTS', HONEYPOT: 'Honeypot', REACTION_ROLE: 'Reaction roles', NICKNAME: 'Spoken names' },
		},
	},

	footer: {
		tagline: 'Your Discord server companion',
	},

	theme: {
		modes: { system: 'System', light: 'Light', dark: 'Dark' },
		title: mode => `Theme: ${mode}`,
		change: mode => `Change theme — currently ${mode}`,
	},

	common: {
		loading: 'Loading…',
		save: 'Save',
		saving: 'Saving…',
		cancel: 'Cancel',
		edit: 'Edit',
		done: 'Done',
		remove: 'Remove',
		add: 'Add',
		copy: 'Copy',
		copied: 'Copied',
		close: 'Close',
		you: 'you',
	},

	errors: {
		title_required: 'Enter an activity name.',
		participant_required: 'Add at least one participant, or choose that you are joining.',
		display_name_required: 'Enter the name you want to use.',
		display_name_too_long: 'Names can be up to 80 characters.',
		currency_not_supported: 'That currency is not supported yet.',
		owner_only: 'Only the organizer can change this.',
		defer_reason_required: 'Add a short reason so the organizer knows.',
		defer_reason_too_long: 'Reasons can be up to 200 characters.',
		payment_due_at_invalid: 'That payment deadline is not a valid date.',
		starts_at_invalid: 'That is not a valid date and time.',
		period_not_in_activity: 'That month does not belong to this activity.',
		payment_option_invalid: 'Check the payment option and try again.',
		payment_link_invalid: 'Enter a valid http or https payment link.',
		payment_destination_required: 'Enter the bank or account destination.',
		notFound: 'No activity with that code',
		notFoundHint: 'The link may have expired, or the code was mistyped',
		failed: 'That did not go through',
		offline: 'Could not reach Megu — try again',
		promptpay_missing: 'No PromptPay number saved yet',
		promptpay_unrecognised: 'That does not look like a PromptPay number',
		slip_duplicate: 'This slip has already been used for another payment',
		slip_too_large: 'That image is too big — try again from your photo library',
		slip_unreadable: 'Could not read that file as an image',
		participant_has_money: 'There is money attached to this person — remove their expenses first',
		participant_paid_out: 'This person fronted money for the group — delete that expense first',
		participant_is_creditor: 'Someone has already paid this person — that payment has to be removed first',
		creditor_not_in_activity: 'That person is not on this activity, so they cannot be paid here',
		cannot_pay_yourself: 'Choose someone else to pay — you cannot send money to yourself',
		choose_who_to_pay: 'You owe more than one person here — choose who this payment is for',
		participant_not_in_activity: 'That person is not on this activity',
		device_already_claimed: 'This browser has already chosen a different name.',
		participant_already_claimed: 'That name has already been chosen. Ask the organizer to reset it if it is yours.',
		expense_not_found: 'No such expense.',
		not_on_this_activity: 'You are not on this activity',
		claim_your_name_first: 'Tap your own name first',
		nothing_outstanding: 'Nothing outstanding to pay',
		payment_not_found: 'No such payment',
		not_your_payment: 'That payment belongs to someone else',
		not_your_slip: 'Only the sender and the person being paid can open this',
		no_slip: 'No slip attached to this payment',
		poll_not_ready: 'Wait until everyone has answered before locking a time',
		time_not_set: 'Choose a date and time before confirming this activity',
		split_people_required: 'Choose who shares this expense',
		split_mode_invalid: 'That way of dividing an expense is not supported.',
		split_values_required: 'Fill in how much each person takes.',
		split_person_missing: 'Every person sharing this expense needs an amount.',
		split_person_not_sharing: 'That person is not sharing this expense.',
		split_amount_invalid: 'Amounts must be zero or more.',
		split_does_not_sum: 'The amounts do not add up to the total — adjust one of them.',
		split_percent_invalid: 'Percentages take up to two decimal places.',
		split_percent_does_not_total: 'The percentages must add up to 100%.',
		split_weight_invalid: 'Shares must be whole numbers, and at least one above zero.',
		slot_required: 'Add at least one possible time.',
		amount_invalid: 'Enter an amount greater than zero.',
		attendance_not_ready: 'Finish the activity before recording attendance',
		attendance_invalid: 'Attendance must be came, did not come, or not marked',
		session_expired: 'Your sign-in expired. Sign in again to continue.',
		last_identity: 'You cannot remove the only sign-in method on this account.',
		identity_not_linked: 'That sign-in method is not connected.',
		notification_mode_invalid: 'Choose a valid notification option.',
		notification_discord_unavailable: 'Connect Discord before choosing Discord notifications.',
		notification_email_unavailable: 'Connect a Google account with a verified email before choosing email notifications.',
		data_conflict: 'The data changed while saving. Reload and try again.',
		recurring_only: 'This action is only available for recurring activities.',
		decision_invalid: 'Choose confirm, reject, or undo.',
	},

	plan: {
		open: 'Waiting on answers',
		confirmed: 'Confirmed',
		done: 'Finished',
		cancelled: 'Cancelled',
	},

	money: {
		none: 'Nothing owed yet',
		open: 'Payment due',
		settled: 'Everyone has paid',
	},

	activity: {
		notScheduled: 'No time set yet',
		noPeriodYet: 'No month opened yet',
		dueOn: day => `due on the ${day}`,
		payBy: when => `Pay by ${when}`,
		payByNone: 'No payment deadline set',
		peopleGoing: (going, total) => `${going}/${total} going`,
		members: total => `${total} ${total === 1 ? 'member' : 'members'}`,
		membersPaid: (paid, total) => `${paid} of ${total} paid`,
		perMonth: amount => `${amount} / month`,
		eachPerMonth: amount => `${amount} each`,
	},

	// The organizer's own list, at /activities. Everything an organizer reads
	// before they have created anything lives here, which makes this section
	// the product's first description of itself — the examples are load-bearing
	// and not filler. A single example ("badminton") taught readers that Megu
	// was a court-booking tool, so the range is stated deliberately and in more
	// than one place.
	projects: {
		joinTitle: "Share a join link",
		joinHint: "Share this link with your team. People sign in and request access; only the project owner can approve them as members. Links expire after 7 days.",
		createJoinLink: "Create / replace join link",
		revokeJoinLink: "Disable join link",
		joinActive: "A join link is active. Replacing it disables the previous link.",
		joinRequests: "Requests to join",
		noJoinRequests: "No pending requests.",
		approveJoin: "Approve",
		rejectJoin: "Decline",
		requestJoinTitle: "Request to join",
		requestJoinHint: "Sign in and send a request. The project owner must approve you before you can view this project.",
		requestJoin: "Request access",
		joinPending: "Your request is waiting for the owner’s approval.",
		joinRejected: "The owner declined this request. Contact them for an invitation.",
		checkJoin: "Check request status",
		dmEnabled: "Send personal notifications (Discord DM / email)",
		dmHint: "Assignees receive deadline reminders and project leads receive blocker alerts through their account notification preferences. Discord DMs require a linked Discord account and DMs enabled.",
		joinFailed: "Could not complete this request. Please try again.",
		title: 'Projects',
		lede: 'Keep ownership, deadlines, and progress in one shared view.',
		newProject: 'Create project',
		createTitle: 'Start a project',
		createHint: 'Name the outcome first. You can add people and topics next.',
		name: 'Project name',
		namePlaceholder: 'Community website',
		description: 'Description (optional)',
		descriptionPlaceholder: 'What will this team deliver?',
		timezone: 'Project timezone',
		timezoneChangeTitle: 'How should existing schedules move?',
		keepLocalDates: 'Keep the same local dates and times', keepExactTimes: 'Keep the same exact moments',
		keepLocalPreview: (start, end) => `Project, topic, and milestone dates stay on their local calendar dates. Project start: ${start}; target: ${end}.`,
		keepExactPreview: (start, end) => `Stored moments do not move. In the new timezone the project reads: ${start} — ${end}.`,
		deadline: 'Target deadline (optional)',
		deadlineHint: 'Ends at the close of this day in the project timezone.',
		create: 'Create project',
		creating: 'Creating…',
		cancel: 'Cancel',
		search: 'Search projects',
		searchPlaceholder: 'Search by title or code',
		filters: { active: 'Active', closed: 'Closed', mine: 'Assigned to me' },
		role: { owner: 'Owner', lead: 'Lead', member: 'Member', viewer: 'Viewer' },
		state: { planning: 'Planning', active: 'Active', paused: 'Paused', completed: 'Completed', cancelled: 'Cancelled' },
		workflow: { not_started: 'Not started', in_progress: 'In progress', in_review: 'In review', completed: 'Completed' },
		noDeadline: 'No deadline',
		noUpdates: 'No updates yet',
		nextDue: 'Next due', lastUpdated: 'Updated',
		topicsCount: n => `${n} ${n === 1 ? 'topic' : 'topics'}`,
		peopleCount: n => `${n} ${n === 1 ? 'person' : 'people'}`,
		progress: 'reported progress',
		emptyTitle: 'Give the work a shared shape',
		emptyBody: 'Create a private project, divide it into topics, and let Megu keep each update beside the plan.',
		filteredEmpty: 'No projects match these filters.',
		clearFilters: 'Clear filters',
		loadFailed: 'Projects could not be loaded. Try again.',
		loadMoreProjects: 'Load more projects',
		retry: 'Try again',
		private: 'Private',
		reportProgress: 'Report progress',
		more: 'More',
		manage: 'Project settings',
		manageLede: 'Manage the project, its people, and lifecycle.',
		manageTabs: { general: 'General', people: 'People', notifications: 'Discord & notifications', lifecycle: 'Lifecycle' },
		backToProject: 'Back to project',
		generalTitle: 'Project details',
		saveProject: 'Save project details',
		projectSaved: 'Project details saved.',
		unsavedTitle: 'Unsaved changes',
		unsavedDetail: 'Save this section or discard its draft before leaving.',
		keepEditing: 'Keep editing',
		discardChanges: 'Discard and continue',
		peopleTitle: 'People with access',
		peopleHint: 'Everyone here can read project topics and progress reports. Viewers cannot make changes.',
		inviteTitle: 'Invite someone',
		inviteHint: 'Invitations are private, expire after 7 days, and only work for the Discord account or verified email you name.',
		inviteProvider: 'Find them by',
		inviteProviders: { discord: 'Discord user ID', email: 'Verified email' },
		inviteRecipient: 'Discord user ID or email',
		inviteRole: 'Project role',
		sendInvite: 'Create invite link',
		inviting: 'Creating link…',
		inviteReady: 'Invite link ready',
		inviteReadyHint: 'Send this private link to the person you invited. It is shown only this once.',
		copyLink: 'Copy link',
		copied: 'Copied',
		pendingInvites: 'Pending invitations',
		noPendingInvites: 'No pending invitations.',
		expires: 'Expires',
		revoke: 'Revoke',
		removeMember: 'Remove',
		leaveProject: 'Leave project',
		memberSince: 'Member since',
		notificationsTitle: 'Discord & notifications',
		notificationsEnabled: 'Enable project notifications',
		deadlineReminders: 'Topic deadline reminders',
		reminder48h: '48 hours before the deadline',
		reminder24h: '24 hours before the deadline',
		reminderHint: zone => `Scheduled from each topic deadline in ${zone}. Completed, archived, revised, or inaccessible work is skipped before delivery.`,
		deliveryFailure: 'A recent notification could not be delivered',
		deliveryFailureDetail: (channel, error) => `${channel}: ${error}`,
		channelDelivery: 'Discord channel delivery',
		channelEnabled: 'Share minimal blocker and deadline status in a server channel',
		channelServer: 'Server you manage', channelName: 'Channel',
		channelDisclosure: 'Megu validates access before saving and again before every send. No report summary, blocker reason, or automatic mention is posted.',
		channelPreview: 'Disclosure preview', channelPreviewPrivate: 'The project link still requires project membership.',
		blockerNotifications: 'Let contributors notify leads when a new blocker is reported',
		notificationPrivacy: 'Megu uses each recipient’s account delivery preference. Notifications include the project and topic name, never the report summary or blocker reason.',
		saveNotifications: 'Save notification settings',
		notifyLeads: 'Notify project leads about this new blocker',
		lifecycleTitle: 'Project lifecycle',
		lifecycleHint: 'State changes affect reporting immediately and are recorded in the project updates.',
		transferTitle: 'Transfer ownership',
		transferHint: 'The recipient must accept within 7 days. After acceptance, you become a lead and they become the only owner.',
		newOwner: 'New owner',
		proposeTransfer: 'Propose transfer',
		transferPending: name => `Waiting for ${name} to accept ownership.`,
		acceptTransfer: 'Accept ownership',
		cancelTransfer: 'Cancel transfer',
		ownershipAccepted: 'Ownership transferred.',
		stateReason: 'Reason or context',
		changeState: 'Change state',
		confirmStateTitle: state => `Confirm ${state.toLowerCase()}`,
		confirmStateHint: 'This immediately changes reporting and reminders. The reason is kept in project history.',
		changingState: 'Changing…',
		stateActions: { active: 'Activate', paused: 'Pause', completed: 'Complete project', cancelled: 'Cancel project' },
		acceptInviteTitle: 'Join this project',
		acceptInviteLede: 'This private invitation is bound to your verified Discord account or email.',
		acceptInvite: 'Accept invitation',
		acceptingInvite: 'Joining…',
		inviteAccepted: 'You joined the project.',
		myWork: 'My work',
		assigned: n => `${n} assigned`,
		awaitingReview: n => `${n} awaiting review`,
		chooseTopic: 'Choose topic',
		chooseReportTopic: 'Choose work to report', chooseReportTopicHint: 'Only your assigned, unfinished topics appear here.',
		views: { timeline: 'Timeline', topics: 'Topics', updates: 'Updates' },
		addTopic: 'Add topic',
		filter: 'Filter',
		today: 'Today',
		fitProject: 'Fit project',
		previousRange: 'Previous date range', nextRange: 'Next date range',
		zoom: { day: 'Day', week: 'Week', month: 'Month' },
		topic: 'Topic',
		owner: 'Owner',
		status: 'Status',
		blocked: 'Blocked',
		overdue: 'Overdue',
		unassigned: 'Unassigned',
		unscheduled: 'Unscheduled',
		due: 'Due',
		projectTimezone: 'Project timezone',
		topicDetails: 'Topic details',
		primaryAssignee: 'Primary assignee',
		editAssignees: 'Edit assignees',
		editTopic: 'Edit topic',
		saveTopicChanges: 'Save topic changes',
		assignees: 'Assignees',
		primary: 'Primary',
		saveAssignees: 'Save assignees',
		schedule: 'Schedule',
		scheduleTools: 'Schedule structure',
		scheduleToolsHint: 'Milestones mark shared targets. Dependencies describe which topic should finish before another starts; they do not block reporting or move dates automatically.',
		milestones: 'Milestones',
		milestone: 'Milestone',
		milestoneTitle: 'Milestone name',
		milestoneDate: 'Target date',
		addMilestone: 'Add milestone',
		noMilestones: 'No milestones yet.',
		markReached: 'Mark reached',
		markOpen: 'Reopen milestone',
		milestoneState: { open: 'Open', reached: 'Reached' },
		dependencies: 'Dependencies',
		dependencyHint: 'Finish-to-start guidance',
		predecessor: 'Finish this first',
		successor: 'Then start this',
		addDependency: 'Add dependency',
		noDependencies: 'No dependencies yet.',
		dependencyStatus: { aligned: 'Dates align', warning: 'Schedule overlaps', not_evaluated: 'Dates not evaluated' },
		remove: 'Remove',
		confirmRemove: 'Remove now',
		keep: 'Keep',
		reportedProgress: 'Reported progress',
		latestReport: 'Latest report',
		viewHistory: 'View report history',
		reportHistoryTitle: 'Progress history',
		reportBy: name => `Reported by ${name}`,
		noReport: 'No report has been submitted yet.',
		closeDetails: 'Close topic details',
		topicTitle: 'Topic title',
		topicDescription: 'Description (optional)',
		startDate: 'Start date (optional)',
		dueDate: 'Due date (optional)',
		deadlineOverride: 'This topic finishes after the project target. I understand and want to keep this later date.',
		scheduleChangeTitle: 'Confirm schedule change',
		scheduleChangeHint: 'Review the shared project dates before saving this one versioned change.',
		applySchedule: 'Apply schedule',
		scheduleSaved: (start, end) => `Schedule saved. Start ${start}; due ${end}.`,
		latestSchedule: 'Latest saved schedule', reapplySchedule: 'Review proposal against latest',
		dragSchedule: 'Drag to move this schedule. Use the edge handles to resize it.',
		assignToMe: 'Assign this topic to me',
		saveTopic: 'Add topic',
		saving: 'Saving…',
		reportTitle: 'Progress update',
		progressField: 'Progress (0–99%)',
		summary: 'What changed?',
		summaryPlaceholder: 'Share the result, decision, or next step.',
		requestReview: 'Request completion review',
		blocker: 'This work is blocked',
		blockerReason: 'What is blocking it?',
		decreaseReason: 'Why did the estimate decrease?',
		clearBlockerReason: 'How was the blocker cleared?',
		submitReport: 'Save update',
		reviewUpdate: 'Review update',
		reportPreview: 'Preview of the saved state',
		editUpdate: 'Back to editing',
		resultingState: 'Resulting state',
		reportSaved: 'Progress update saved.',
		sortTopics: 'Sort topics',
		topicSort: { number: 'Topic number', title: 'Title A–Z', deadline: 'Due date', status: 'Status', progress: 'Progress: high to low' },
		approve: 'Approve completion',
		returnWork: 'Return to in progress',
		reopenTopic: 'Reopen topic', reopenProgress: 'Restart at progress (0–99%)', reviewReason: 'Reason', confirmReviewAction: 'Confirm change',
		archiveTopic: 'Archive topic', archivedTopics: 'Archived topics', restoreTopic: 'Restore', archiveHint: 'Archive removes this topic from current work and the progress rollup. Its reports and history remain.',
		startProject: 'Activate project',
		starting: 'Activating…',
		planningNote: 'Finish the topic outline, then activate reporting for the team.',
		noTopicsTitle: 'No topics yet',
		noTopicsLead: 'Add the first piece of work to make the timeline useful.',
		noTopicsMember: 'The project lead has not added work yet.',
		noAssignedWork: 'Nothing is assigned to you right now.',
		updatesEmpty: 'Project changes will appear here.',
		filteredUpdatesEmpty: 'No updates match these filters.', filterTopic: 'Topic', filterPerson: 'Person', allTopics: 'All topics', allPeople: 'All people',
		loadMore: 'Load earlier updates',
		loadingMore: 'Loading…',
		loadEarlierReports: 'Load earlier reports',
		correctWithUpdate: 'Correct with a new update',
		correctingReport: 'Correcting this earlier report',
		correctionReference: 'Correction to an earlier report',
		event: {
			project_created: 'Project created', project_state_changed: 'Project state changed',
			project_updated: 'Project details updated', topic_created: 'Topic added', topic_updated: 'Topic updated',
			topic_archived: 'Topic archived', topic_restored: 'Topic restored', progress_reported: 'Progress reported',
			topic_completed: 'Topic completed', topic_returned: 'Topic returned', topic_reopened: 'Topic reopened',
			member_invited: 'Member invited', invitation_revoked: 'Invitation revoked', member_joined: 'Member joined',
			member_role_changed: 'Member role changed', member_removed: 'Member removed', member_left: 'Member left',
			assignments_changed: 'Assignments changed',
			ownership_transfer_proposed: 'Ownership transfer proposed', ownership_transfer_cancelled: 'Ownership transfer cancelled',
			ownership_transferred: 'Ownership transferred',
			notification_settings_changed: 'Notification settings changed',
			dependency_added: 'Dependency added', dependency_removed: 'Dependency removed',
			milestone_created: 'Milestone added', milestone_updated: 'Milestone updated', milestone_removed: 'Milestone removed',
		},
		signedOutTitle: 'Your project work',
		signedOutLede: 'Sign in with Discord to open private projects and report progress.',
			errors: {
			project_not_found: 'This project is unavailable or you no longer have access.',
			project_forbidden: 'Your project role does not allow that action.',
			revision_conflict: 'Someone changed this work first. Your draft is still here; review the latest values and try again.',
			project_not_active: 'Activate the project before submitting progress.',
			project_closed: 'This project is closed.',
			timezone_change_mode_required: 'Timezone changes need a schedule-preservation choice.',
			timezone_schedule_invalid: 'That timezone change lands on a local time that does not exist. Choose another timezone or keep exact moments.',
			reason_required: 'Add a reason for this change.',
			title_required: 'Enter a project name.',
			topic_title_required: 'Enter a topic title.',
			topic_deadline_override_required: 'Acknowledge that this topic ends after the project target.',
			summary_required: 'Describe what changed.',
			progress_decrease_reason_required: 'Explain why the progress estimate decreased.',
			blocker_clear_reason_required: 'Explain how the blocker was cleared.',
			blocker_reason_required: 'Describe the blocker.',
			blocked_review_invalid: 'Clear the blocker before requesting completion review.',
			invitation_recipient_invalid: 'Enter a valid Discord user ID or email address.',
			invitation_recipient_mismatch: 'This invitation belongs to a different account.',
			invitation_pending: 'A current invitation already exists for this person.',
			invitation_not_found: 'This invitation is unavailable.',
			invitation_expired: 'This invitation has expired. Ask the project lead for a new one.',
			invitation_revoked: 'This invitation was revoked.',
			invitation_used: 'This invitation has already been used.',
			member_exists: 'This person already belongs to the project.',
			member_limit: 'This project has reached its 50-person pilot limit.',
			ownership_transfer_pending: 'A current ownership transfer is already awaiting acceptance.',
			ownership_transfer_expired: 'This ownership transfer has expired.',
			ownership_transfer_stale: 'The project owner changed before this transfer was accepted.',
			ownership_transfer_self: 'Choose another project member as the new owner.',
			assignee_invalid: 'Only active project members who can contribute may be assigned.',
			dependency_topics_required: 'Choose both topics for this dependency.',
			dependency_self: 'A topic cannot depend on itself.',
			dependency_topic_invalid: 'Choose two active topics from this project.',
			dependency_exists: 'That dependency already exists.',
			dependency_cycle: 'That dependency would create a cycle. Choose a different order.',
			milestone_title_required: 'Enter a milestone name.',
			milestone_due_required: 'Choose a target date for the milestone.',
			due_at_invalid: 'Choose a valid milestone date.',
			milestone_limit: 'This project has reached its 100-milestone limit.',
			milestone_state_invalid: 'Choose a valid milestone state.',
			project_channel_invalid: 'Choose a Discord server you manage and a valid channel.',
			project_channel_unavailable: 'Megu cannot view or send messages in that channel.',
			failed: 'The change could not be saved. Your input is still here.',
		},
	},

	activities: {
		title: 'Your activities',
		liveCount: n => `${n} still running`,
		pastCount: n => `${n} finished`,
		newActivity: 'New activity',
		liveTitle: 'Running now',
		pastTitle: 'Earlier',
		monthly: 'Monthly',
		openMenu: 'Open',
		standing: {
			awaitingConfirmation: (n, amount) => amount
				? `${n} to confirm · ${amount} due`
				: `${n} to confirm`,
			outstanding: (n, amount) => `${amount} due · ${n} ${n === 1 ? 'person' : 'people'}`,
			answered: (answered, total) => `${answered}/${total} answered`,
			allAnswered: total => `${total}/${total} answered`,
			settled: 'Paid in full',
		},

		empty: {
			says: 'Nothing here yet. Shall we start one?',
			lede: 'Anything with more than one person and some money in it. Megu can hold all of these:',
			examples: [
				'Dinner, split when the bill lands',
				'A trip somebody books and pays for up front',
				'A grocery run for the house',
				'Rent and wifi, collected every month',
				'A group gift everyone chips in on',
			],
		},

		kind: {
			legend: 'What kind',
			event: 'One time',
			eventHint: 'Dinner, a trip, a shopping run, badminton — happens once, gets split, done.',
			recurring: 'Every month',
			recurringHint: 'Wifi, Netflix, rent — the same amount each month, and Megu opens the round herself.',
		},

		saysEvent: 'What are we doing, and who with? I will go and ask them.',
		saysRecurring: 'Something to collect every month. Tell me how much, and from whom.',

		titleField: 'What should we call it',
		titlePlaceholderEvent: 'Hotpot on Saturday',
		titlePlaceholderRecurring: 'Home wifi',
		examplesLabel: 'For example',
		exampleTitlesEvent: ['Dinner', 'Weekend trip', 'Badminton', 'House groceries', 'Birthday gift'],
		exampleTitlesRecurring: ['Wifi', 'Netflix', 'Rent', 'Electricity'],

		whenField: 'When',
		whenAsk: 'Let Megu ask',
		whenKnown: 'I know the time',
		whenAskHint: 'Megu collects everyone’s free days first, then calls it.',

		whereField: 'Where',
		wherePlaceholder: 'Place or address',

		yourParticipation: {
			legend: 'Are you joining?',
			joins: 'Yes, I’m joining',
			organizes: 'No, I’m organizing',
			joinsHint: 'You will be added to the roster using the name you choose below.',
			organizesHint: 'You will still own and manage the activity, but you will not be counted as a participant.',
			nameField: 'Your name in this activity',
			nameHint: 'Use any name or writing system. This is separate from your sign-in username.',
			saveDefault: 'Use this as my default name for future activities',
		},
		currencyField: 'Currency',
		currencyHint: 'Everyone in this activity sees and settles the same currency.',
		peopleField: 'Who else is in',
		peoplePlaceholder: 'Alex, Sam, Mint',
		peopleHint: 'Commas or new lines. Nobody has to sign up for anything — you just send them the link.',

		amountField: currency => `How much a month (${currency})`,
		initialPayerField: 'Who paid this first?',
		initialPayerHint: 'This person fronts the recurring charge and is the one the group pays back.',
		dueDayField: 'Collect on day',
		dueDayHint: 'of every month (1–28)',

		// The day it happens and the day it is paid for are rarely the same:
		// the court is played on the 20th and settled on the 21st. This is a
		// separate field for that reason.
		payByField: 'Pay by',
		payByHint: 'On this day Megu reminds whoever has not paid. Optional.',

		serverField: 'Discord server',
		serverNone: 'Not linked to a server',

		optional: 'optional',
		create: 'Create it and give me the link',
		creating: 'Creating…',

		signedOutTitle: 'Your activities and plans',
		signedOutLede: 'Sign in to return to schedules, participants, and the shared expenses attached to each activity.',
		signIn: 'Sign in with Discord',
	},

	headline: {
		youOwe: 'You owe',
		youGetBack: 'You get back',
		yourTotal: 'Your total',
		clear: 'All clear',
		pay: 'Pay this',
		claimed: 'Told them — waiting for confirmation',
	},

	// The second button on a reminder.
	//
	// A reminder with one button collects one answer: everybody who cannot pay
	// today presses nothing, and the organizer is left with a blank where an
	// explanation should be. This gives the honest answer — "not yet, because…"
	// — somewhere to go.
	defer: {
		button: 'Not now',
		title: 'Not ready to pay yet?',
		reasonLabel: 'Tell them why, briefly',
		hint: 'Megu passes it on to the organizer so nobody has to chase you. The amount stays outstanding.',
		submit: 'Send it to the organizer',
		done: when => `Noted. Megu will not ask again until ${when}.`,
		badge: 'Asked to delay',
		reasonBy: (name, reason) => `${name}: ${reason}`,
		snoozedUntil: when => `Asking again ${when}`,
	},

	claim: {
		title: 'Which one are you?',
		hint: 'Tap your own name. No signup, no app to install.',
		takenByThisDevice: name => `This device is already "${name}"`,
	},

	rsvp: {
		question: name => `${name}, are you coming?`,
		going: 'Going',
		notGoing: 'Not going',
	},

	// ── the four screens ────────────────────────────────────────────────────
	//
	// One activity, four things a person might have come to do. Each screen is
	// named after the job rather than the section, because the name is what the
	// reader is deciding between when they look at the summary.
	screens: {
		back: 'Back',
		summary: 'Overview',
		payTitle: 'Pay',
		payFor: title => `for ${title}`,
		payNothing: 'You are all paid up for this one.',
		payClaimFirst: 'Tap your own name on the overview first, then Megu knows which amount is yours.',
		claimFirst: 'Tap your own name on the overview first, then Megu knows whose answer this is.',
		answerTitle: 'Your answer',
		answerFor: title => `for ${title}`,
		answered: 'Answered',
		manageTitle: 'Organizer tools',
		manageFor: title => `for ${title}`,
		manageDenied: 'Only the organizer can open this.',
		openManage: 'Organizer tools',
	},

	// The single thing this reader should do next, printed once, at the top.
	// The old page showed every panel to everybody and let them find it.
	next: {
		oweLabel: 'You owe',
		settledLabel: 'Your total',
		pendingLabel: 'Told them — waiting for confirmation',
		title: 'Your turn',
		claim: 'Which one are you?',
		claimAction: 'Pick your name',
		owe: amount => `You owe ${amount}`,
		oweAction: 'Pay now',
		waitingConfirm: 'You said you paid — waiting for the organizer',
		deferred: when => `You asked to pay later. Megu will ask again on ${when}.`,
		vote: 'Megu is asking when everyone is free',
		voteAction: 'Choose a time',
		rsvp: 'Say whether you are coming',
		rsvpAction: 'Answer',
		review: n => `${n} ${n === 1 ? 'payment is' : 'payments are'} waiting for you to check`,
		reviewAction: 'Review them',
		clear: 'Nothing needs you right now.',
		// The state every activity starts in, and the one the summary used to
		// answer with "nothing needs you" — while the single thing that needed
		// doing had no control anywhere on the page.
		setTime: 'This has no time yet. Nobody can answer until it does.',
		setTimeAction: 'Set a time',
		waitingForTime: 'Megu is waiting for the organizer to pick a time.',
	},

	schedule: {
		title: 'Choose a time first',
		ownerHint: 'Add a few options. Megu will ask everyone when they are free before anyone commits to coming.',
		waitingHint: 'The organizer is still choosing times. You can answer as soon as the options arrive.',
	},

	roster: {
		titleEvent: 'Who is coming',
		titleRecurring: 'Members',
		going: 'Going',
		notGoing: 'Not going',
		noAnswer: 'Has not answered',
		notLinked: 'Has not claimed their name',
		paidUp: 'Paid up',
		clear: 'Clear',
		getsBack: amount => `Gets back ${amount}`,
		paidFor: period => `Paid for ${period}`,
		owesFor: (amount, period) => `Owes ${amount} for ${period}`,
		leftOn: period => `Left in ${period}`,
		addPerson: 'Add someone…',
		nameOf: name => `Name for ${name}`,
		returnName: 'Un-claim',
		confirmRemove: name => `Take ${name} off this activity?`,
	},

	attendance: {
		title: 'Who actually came',
		hint: 'Mark attendance after the activity so the record reflects what happened, not only what people planned.',
		came: 'Came',
		absent: 'Did not come',
		marked: (done, total) => `${done}/${total} marked`,
	},

	expenses: {
		title: 'Costs',
		total: 'Total',
		frontedBy: name => `${name} paid up front`,
		labelField: 'What was it for',
		amountField: 'Amount',
		payerField: 'Who paid up front',
		payerOption: name => `${name} paid up front`,
		splitField: 'Split between',
		splitHint: 'These names will owe a share. Check them before adding the cost.',
		splitHow: 'How to divide it',
		splitModes: {
			even: 'Evenly',
			exact: 'Amounts',
			percent: 'Percent',
			shares: 'Shares',
		},
		splitValueFor: (name, mode) => `${mode} for ${name}`,
		splitBalanced: 'That adds up.',
		splitLeft: amount => `${amount} still to assign.`,
		splitOver: amount => `${amount} more than the total.`,
		splitSharesReady: 'Divided by these shares.',
		splitSharesMissing: 'Give everyone a number of shares.',
		splitNotANumber: 'One of those is not a number.',
		forPerson: name => `For ${name}`,
		splitBetween: names => `Split between ${names}`,
		viewSplit: 'view each share',
		confirmDelete: (label, amount) => `Delete "${label}" ${amount}?`,
	},

	pending: {
		title: 'Waiting for you to confirm',
		saidTheyPaid: 'Says they have paid',
		received: 'Got it',
		notYet: 'Not arrived',
		confirmedTitle: 'Already confirmed',
		historyTitle: 'Reversed and rejected payment history',
		undo: 'Undo confirmation',
		reversalReason: 'Why are you reversing this payment? The payer will see this note.',
		rejectionReason: 'Why are you rejecting this payment? The payer will see this note.',
		rejectedNotice: reason => `Payment rejected: ${reason}`,
		reversedNotice: reason => `Payment confirmation reversed: ${reason}`,
		allocatedFromTransfer: (allocated, total) => `${allocated} allocated to this period from a ${total} transfer`,
		autoMatched: 'Slip matched automatically',
		ownerConfirmed: 'Checked and confirmed by owner',
		cashConfirmed: 'Owner confirmed an offline payment',
		confirmDeletePayment: 'Void this record while keeping its history?',
	},

	cash: {
		title: 'Received outside Megu',
		hint: 'Use this for cash or a transfer you checked yourself. It has no slip and is confirmed under your name.',
		person: 'Received from',
		amount: 'Amount (baht)',
		received: 'Record as received',
		reason: 'Owner confirmed receiving payment outside Megu',
	},

	poll: {
		title: 'When are you free',
		allAnswered: 'Everyone has answered',
		waitingFor: n => `Waiting on ${n} more`,
		free: 'Free',
		maybe: 'Maybe',
		busy: 'Busy',
		freeCount: n => `Free ${n}`,
		maybeCount: n => `Maybe ${n}`,
		busyCount: n => `Busy ${n}`,
		meguSuggests: 'Megu says it should be',
		lockIt: 'Lock this one in',
		option: i => `Option ${i}`,
		anotherOption: '+ another option',
		askForMe: 'Have Megu ask everyone',
	},

	owner: {
		findTime: 'Have Megu find a time that works',
		proposeAgain: 'Propose different times',
		confirmTime: 'Confirm the date and time',
		finish: 'Mark it finished',
		openMonth: 'Open this month',
		monthAlreadyOpen: period => `${period} is already open`,
		monthOpened: period => `${period} opened`,
		payByLabel: 'Payment deadline',
		startsAtLabel: 'When it happens',
		startsAtSave: 'Save the time',
		startsAtHint: 'Everyone sees this on the activity page, and Megu reminds them from it.',
		startsAtMissing: 'No time set yet — nobody can say whether they are coming until there is one.',
		payByHint: 'On that day Megu reminds whoever has not paid — on Discord or by email, whichever each person chose.',
		payBySave: 'Save deadline',
		payByClear: 'Clear',
		addExpense: 'Add a cost',
		typeItIn: 'Or type it in',
		addAndSplit: 'Add it and split it',
		planTitle: 'Where this activity is up to',
		planNothing: 'Nothing left to change here.',
		cancelActivity: 'Cancel this activity',
		confirmCancel: 'Cancel this activity?',
		// What it actually does, said before the button rather than after it:
		// `plan_state = 'cancelled'` stamps `closed_at`, drops the activity out
		// of both reminder queries, and can be undone by reopening it. No row
		// is removed, so nobody loses their record of what they paid.
		cancelHint: 'Reminders stop and the activity closes. Nothing is deleted — everyone keeps their record of what was paid, and you can reopen it later.',
	},

	// ── the organizer's console ─────────────────────────────────────────────
	//
	// One screen used to hold every organizer job in one scroll: the roster,
	// the costs, three separate payment panels, the payout details, the
	// schedule, the receipt scanner and the button that cancels the activity —
	// 4.7 phone screens of it, with the scanner three screens down. These are
	// the names of the jobs, now that each one has a place of its own.
	console: {
		tabs: {
			people: 'People',
			costs: 'Costs',
			payments: 'Payments',
			payout: 'Getting paid',
			settings: 'Settings',
		},
		// The strip under the title. It replaces a count of who had answered an
		// RSVP, which was printed on the settings panel and measured nothing
		// anybody had come here to find out.
		outstanding: 'Still owed',
		waiting: 'Waiting on you',
		settled: 'All settled',
		payBy: when => `Due ${when}`,
		noMoneyYet: 'Nothing to collect yet',
		noPaymentRecords: 'No payments recorded yet, and nobody has an amount outstanding to record one against.',
	},

	// ── one person's side of it ─────────────────────────────────────────────
	//
	// The roster used to print one number per person, and that number was a
	// net: somebody who owed ฿550 and was owed ฿100 showed as ฿450, which is an
	// amount nobody will ever transfer. Both directions are printed now, as the
	// transfers they actually are.
	ledger: {
		open: 'Breakdown',
		close: 'Close',
		sends: (name, amount) => `Sends ${name} ${amount}`,
		receives: (name, amount) => `Gets ${amount} from ${name}`,
		sendsShort: name => `to ${name}`,
		receivesShort: name => `from ${name}`,
		bothWays: 'Owes and is owed',
		// Leg labels for a row that points both ways. The figure column used to
		// show that person one red number — what they send — and the money coming
		// back was a chip underneath, which reads as a footnote to a debt rather
		// than as half of the answer.
		outLeg: 'Sends',
		inLeg: 'Gets',
		share: 'Their share',
		fronted: 'Paid up front',
		confirmed: 'Confirmed paid',
		awaiting: 'Waiting to be confirmed',
		overpaid: 'Overpaid',
		toSend: 'Still to send',
		toReceive: 'Still to receive',
		inCosts: 'Costs they are in',
		noCosts: 'Not in any cost yet',
		paymentsTitle: 'Their payments',
		noPayments: 'No payments yet',
		estimated: 'Reconstructed from payments recorded before Megu tracked who they were sent to.',
		nothingOwed: 'Nothing owed either way',
	},

	invite: {
		title: 'Bring the others in',
		hint: 'Drop this link in the group chat. Nobody needs an account.',
		linkLabel: 'Activity link',
		networkOnly: 'Test mode: this link works for devices on the same Wi-Fi or local network.',
		deviceOnly: 'This link still works only on this device. Set FRONTEND_URL to an address other people can reach before sharing.',
		copyFailed: 'Automatic copy was blocked. The link is selected—long-press it or press Ctrl+C to copy.',
	},

	// ── paying ──────────────────────────────────────────────────────────────
	//
	// The one screen where a wrong word costs real money, so it says the
	// amount, the destination and the person out loud rather than relying on
	// the reader having understood the page above it.
	pay: {
		title: 'Pay',
		payTo: name => `Transfer to ${name}`,
		organizerRecipient: 'the organizer',
		chooseCreditor: 'Who are you paying?',
		chooseCreditorHint: 'More than one person covered something for this group, so there is more than one transfer to make.',
		chooseSomeoneElse: 'Pay someone else instead',
		amountLabel: 'Amount',
		scanHint: 'Scan this with your banking app',
		// The participant is almost always on the same phone they would scan
		// with, so this is the primary path, not a fallback.
		sameDeviceHint: 'On your phone? Save the QR, then use "scan from gallery" in your banking app.',
		saveImage: 'Save QR image',
		saved: 'Saved',
		orTransferTo: 'Or transfer to this PromptPay',
		copyNumber: 'Copy number',
		copyAmount: 'Copy amount',
		numberCopied: 'Number copied',
		amountCopied: 'Amount copied',
		choosePeriods: 'Choose periods and amounts',
		selectAllOutstanding: 'Select everything outstanding',
		amountFor: period => `Amount for ${period}`,
		allocationHint: 'Partial payments and several months on one transfer are supported.',
		baht: 'baht',
		iHavePaid: 'I have transferred it',
		attachSlip: 'Attach the slip',
		attachSlipHint: 'Attach transfer proof to help the organizer verify it. Only the minimum dispute evidence is retained.',
		slipAttached: 'Slip attached',
		replaceSlip: 'Use a different slip',
		viewSlip: 'View slip',
		reading: 'Reading the slip…',
		noPromptPay: name => `${name} has not added a PromptPay number yet`,
		noPromptPayOwner: 'Add your PromptPay number and everyone gets a QR with the exact amount already in it.',
		waitingConfirm: 'Attach the slip so Megu can check and record this payment.',
		waitingOwnerConfirm: 'The organizer will confirm this payment.',
		chooseMethod: 'How would you like to pay?',
		noPaymentMethod: name => `${name} has not added payment instructions yet. Ask them which method to use before marking this paid.`,
		openPaymentLink: 'Open payment link',
		copyDestination: 'Copy details',
		destinationCopied: 'Payment details copied',
		currencyUnit: currency => currency,
	},

	paymentMethods: {
		title: 'Payment options',
		hint: 'PromptPay is optional. Add bank details, a payment link, cash, or any instructions that work for this group.',
		typeField: 'Method',
		labelField: 'Name shown to participants',
		labelPlaceholder: 'e.g. Wise, bank transfer, pay in cash',
		destinationField: 'Bank or account details',
		destinationPlaceholder: 'Bank, account number, routing details',
		accountNameField: 'Account holder',
		urlField: 'Payment link',
		instructionsField: 'Instructions (optional)',
		instructionsPlaceholder: 'Anything participants need to know',
		add: 'Add this option',
		save: 'Save payment options',
		types: {
			promptpay: 'PromptPay',
			bank_transfer: 'Bank transfer',
			payment_link: 'Payment link',
			cash: 'Cash',
			custom: 'Something else',
		},
		// The account screen asks a different question from the activity screen:
		// not "how does this group settle up" but "where do my friends send my
		// money", which is a fact about a person and travels with them.
		accountTitle: 'Where people can pay you',
		accountHint: 'These follow you into every activity. Whoever owes you sees them when they come to pay.',
		empty: 'Nothing here yet. Add somewhere people can send money and Megu will show it to them.',
		addTitle: 'Add a payment method',
		editTitle: 'Edit this payment method',
		defaultTag: 'Offered first',
		makeDefault: 'Offer this first',
		removeConfirm: label => `Remove ${label}? People will no longer see it when they pay you.`,
		destinationFieldFor: {
			promptpay: 'PromptPay number or ID',
			bank_transfer: 'Account number',
			custom: 'Where to send it',
		},
		destinationPlaceholderFor: {
			promptpay: 'Phone number or national ID',
			bank_transfer: 'e.g. 123-4-56789-0',
			custom: 'Anything the payer needs to send it to',
		},
		accountNamePlaceholder: 'The name their banking app will show',
		previewTitle: 'What they will see',
		previewEmpty: 'Add the details and they will appear here.',
	},

	promptpay: {
		title: 'Where the money goes',
		field: 'Your PromptPay (phone number or ID)',
		nameField: 'Account name',
		nameHint: 'Shown so people can check they are paying the right person',
		hint: 'Money goes straight from them to your bank. Megu never holds it and never sees it.',
		saved: 'Saved',
		payee: 'Everyone pays',
		payeeField: 'Who collects the money',
		organizerOption: name => `Organizer${name ? ` — ${name}` : ''}`,
		notSet: 'Not set yet',
		remove: 'Remove this number',
		fromQr: 'Read it from my QR',
		fromQrHint: 'Pick the PromptPay QR your banking app saved. It is read on this device and never uploaded.',
		reading: 'Reading the code…',
		qrRead: masked => `Read from the code: ${masked}`,
		qrAmountIgnored: amount => `That code also carried ${amount}. Only the account is kept — Megu puts the right amount in each time.`,
	},

	slip: {
		verdictUnread: 'Slip attached — could not read its reference',
		verdictReview: 'Slip attached — waiting for owner review',
		verdictMatched: 'Slip attached',
		verdictDuplicate: 'This slip was already used',
		expected: amount => `Asked for ${amount}`,
		uploaded: when => `Attached ${when}`,
		privacyNote: 'Only you and the person who sent it can open this.',
		readingImage: 'Reading the slip…',
		sentFrom: bank => `Sent from ${bank}`,
		readAmount: amount => `The slip reads ${amount}`,
		readDiffers: (read, expected) => `The slip reads ${read}, but ${expected} was asked for`,
		readNote: 'Read from the picture, not from a bank. Worth a look before you confirm.',
		// Why Megu stopped short of confirming it by itself.
		//
		// Each one names the thing to look at, because the reader is about to
		// press a button that says the money arrived. "receiver_mismatch" is a
		// label for a log; "the name on the slip is not the account you set up"
		// is something an organizer can act on without knowing how any of this
		// works.
		heldTitle: 'Megu did not confirm this one:',
		held: {
			reference_missing: 'No bank reference in the picture — it may not be a transfer slip.',
			amount_unreadable: 'Could not read an amount off the picture.',
			amount_mismatch: 'The amount on the slip is not the amount asked for.',
			receiver_not_configured: 'No payout account is set up yet, so there was nothing to check the receiver against.',
			receiver_unreadable: 'Could not read who the money went to.',
			receiver_mismatch: 'The name on the slip is not the account you set up.',
			time_unreadable: 'Could not read a date and time.',
			time_in_future: 'The slip is dated in the future.',
		},
		flags: {
			uploaded_late: 'Sent more than a month after the transfer is dated.',
		},
	},

	// The record of one payment. Kept apart from `receipt`, which is about
	// photographing a restaurant bill — two different things that English
	// unhelpfully gives the same word.
	receiptPage: {
		title: 'Payment receipt',
		fromTo: (from, to) => `${from} → ${to}`,
		status: 'Status',
		method: 'Payment method',
		reference: 'Reference',
		asked: 'Amount asked for',
		reason: 'Reason',
		export: 'Save as PDF',
		viewSlip: 'View payment slip',
		disclaimer: 'Recorded by Megu. This is a record of what the group agreed, not proof of a bank transfer.',
		statuses: {
			pending: 'Waiting for confirmation',
			confirmed: 'Confirmed',
			rejected: 'Rejected',
			reversed: 'Confirmation cancelled',
			voided: 'Withdrawn',
		},
	},

	receipt: {
		scan: 'Scan a receipt',
		hint: 'Photograph the bill and Megu will read the lines off it. You check them before anything is added.',
		reading: 'Reading the bill…',
		found: count => (count === 1 ? 'Read 1 line' : `Read ${count} lines`),
		checkNote: 'This is read off a photograph, so check it. Edit anything, untick what should not be here.',
		selected: count => (count === 1 ? '1 line selected' : `${count} lines selected`),
		matchesPrinted: total => `Adds up to the ${total} printed on the bill`,
		differsFromPrinted: (total, gap) => `The bill says ${total} — that is ${gap} apart`,
		addAll: (count, total) => (count === 1 ? `Add 1 expense · ${total}` : `Add ${count} expenses · ${total}`),
		asOneLine: total => `Add the whole bill as one expense instead (${total})`,
		wholeBill: 'Whole bill',
		untitled: 'Item',
		serviceLine: 'Service charge',
		taxLine: 'VAT',
		addService: amount => `Add service charge ${amount}`,
		addTax: amount => `Add VAT ${amount}`,
		includeLine: label => `Include ${label}`,
		nothingFound: 'Nothing readable in that photo. Try again with the bill flat and the whole of it in frame.',
		failed: 'Could not read that picture',
		partial: (added, total) => `Added ${added} of ${total} and then stopped — the rest are not in`,
		unavailable: 'The reader is not installed on this server yet',
	},
};

module.exports = en;
