// Thai. Same keys as en.js, in the same order, so a missing one is visible by
// reading the two side by side.
//
// Most of these were already in the pages and are kept word for word — they
// were written in Megu's register, and a translation round-trip through
// English would have flattened them into something politer and colder than
// she is.

const th = {
	code: 'th',
	label: 'ไทย',
	nav: {
		home: 'หน้าแรก',
		activities: 'กิจกรรม',
		servers: 'เซิร์ฟเวอร์',
		account: 'บัญชี',
		signOut: 'ออก',
		signIn: 'เข้าสู่ระบบ',
	},

	auth: {
		google: 'ดำเนินการต่อด้วย Google',
		discord: 'ดำเนินการต่อด้วย Discord',
	},

	account: {
		title: 'บัญชีของคุณ',
		lede: 'บัญชี Megu เดียว จะเลือกเข้าสู่ระบบด้วยช่องทางไหนก็ได้',
		signInTitle: 'เข้าสู่ระบบ Megu',
		signInLede: 'ใช้ Google หรือ Discord แล้วค่อยเชื่อมอีกช่องทางภายหลังเพื่อเข้าถึงกิจกรรมและประวัติชุดเดิม',
		profileHint: 'นี่คือชื่อเริ่มต้นใน Megu แต่ในแต่ละกิจกรรมคุณยังใช้ nameplate คนละชื่อได้',
		connectedTitle: 'ช่องทางเข้าสู่ระบบที่เชื่อมไว้',
		connectedHint: 'ช่องทางที่เชื่อมจะพาเข้าบัญชี Megu เดิม ไม่ได้สร้างบัญชีซ้ำ',
		providers: { google: 'Google', discord: 'Discord' },
		connected: 'เชื่อมแล้ว', notConnected: 'ยังไม่เชื่อม', connect: 'เชื่อม', unlink: 'ยกเลิกการเชื่อม',
		unlinkConfirm: provider => `ยกเลิกการเชื่อม ${provider}?`,
		unlinked: 'ยกเลิกช่องทางเข้าสู่ระบบแล้ว',
		noMergeNote: 'ถ้าช่องทางเข้าสู่ระบบนี้อยู่กับบัญชี Megu อีกบัญชีของคุณเอง Megu จะเสนอให้รวมสองบัญชี หลังจากยืนยันครบทั้งสองฝั่งแล้ว และจะยังไม่ย้ายอะไรจนกว่าคุณจะกดยืนยัน',
		linkConflict: 'ช่องทางนี้อยู่กับบัญชี Megu ที่รวมกับบัญชีนี้ไม่ได้ เพราะหนึ่งบัญชี Megu มีได้หนึ่งช่องทางต่อหนึ่ง provider กรุณายกเลิกการเชื่อมช่องทางเดิมก่อน ระบบยังไม่เปลี่ยนข้อมูลใด ๆ',
		linkSuccess: 'เชื่อมช่องทางสำเร็จ ต่อไปใช้ provider ไหนก็เข้าบัญชีนี้ได้',
		profileSourceTitle: 'ชื่อและรูปโปรไฟล์',
		profileSourceHint: 'เลือกว่าชื่อและรูปใน Megu จะตามช่องทางไหน ไม่มีผลกับการเข้าสู่ระบบ ทุก provider ที่เชื่อมไว้ยังใช้ล็อกอินได้เหมือนเดิม',
		profileSources: { google: 'ตาม Google', discord: 'ตาม Discord', manual: 'ใช้ชื่อที่พิมพ์เอง' },
		profileSourceSaved: 'บันทึกที่มาของโปรไฟล์แล้ว',

		merge: {
			title: 'รวมสองบัญชีนี้',
			lede: 'ช่องทางนี้อยู่กับบัญชี Megu อีกบัญชีของคุณเอง ตอนนี้ยืนยันครบทั้งสองฝั่งแล้ว Megu จึงรวมให้เป็นบัญชีเดียวได้',
			checking: 'กำลังตรวจว่าอะไรจะถูกย้ายบ้าง…',
			movesTitle: 'สิ่งที่จะถูกย้าย',
			movesHint: 'ทุกอย่างข้างล่างจะย้ายไปอยู่บัญชีเดียว ไม่มีอะไรถูกลบ และไม่มียอดไหนเปลี่ยน',
			counts: {
				owned_activities: n => `กิจกรรมที่คุณเป็นคนจัด ${n} รายการ`,
				participant_rows: n => `ชื่อในรายชื่อผู้เข้าร่วม ${n} รายการ`,
				payments: n => `การจ่ายเงิน ${n} รายการ`,
				identities: n => `ช่องทางเข้าสู่ระบบ ${n} ช่องทาง`,
			},
			ledgerNote: 'ประวัติการจ่ายเงินจะถูกย้าย ไม่ถูกคำนวณใหม่ ใครค้างเท่าไรยังเท่าเดิมทุกบาท',
			duplicatesTitle: 'คุณจะปรากฏสองชื่อ',
			duplicatesHint: 'ทั้งสองบัญชีอยู่ในกิจกรรมเหล่านี้ Megu เก็บทั้งสองรายการไว้ เพราะการรวมเป็นรายการเดียวต้องบวกยอดสองก้อนเข้าด้วยกัน ซึ่งจะเปลี่ยนบัญชีที่ปิดไปแล้ว เปลี่ยนชื่อรายการใดรายการหนึ่งทีหลังได้',
			duplicatesIn: (title, code) => `${title} · ${code}`,
			notificationTitle: 'การแจ้งเตือนหลังรวมบัญชี',
			notificationNote: mode => `ช่องทางที่คุณใช้อยู่แล้วทั้งสองฝั่งจะยังเปิดไว้: ${mode} เปลี่ยนได้ทุกเมื่อในหน้านี้`,
			profileTitle: 'จะใช้ชื่อและรูปจากที่ไหน',
			profileHint: 'ไม่มีผลกับการเข้าสู่ระบบ คุณยังล็อกอินได้ทั้ง Google และ Discord เหมือนเดิม',
			irreversible: 'การรวมบัญชีย้อนกลับไม่ได้ Megu จะบันทึกว่าใครทำ และแจ้งไปทั้งอีเมลและ Discord ของคุณ โดยแต่ละช่องทางจะบอกชื่ออีกช่องทางหนึ่ง',
			confirm: 'รวมบัญชี',
			merging: 'กำลังรวม…',
			cancel: 'ยกเลิก ไม่เปลี่ยนอะไร',
			blocked: providers => `สองบัญชีนี้ใช้ ${providers} ทั้งคู่ และหนึ่งบัญชี Megu มีได้หนึ่งช่องทางต่อหนึ่ง provider กรุณายกเลิกการเชื่อมฝั่งหนึ่งก่อน`,
			expired: 'คำขอรวมบัญชีนี้หมดอายุแล้ว เริ่มใหม่ได้จากการกดเชื่อมช่องทางในหน้าบัญชี',
			done: 'รวมบัญชีเรียบร้อย ตอนนี้ทั้งสองช่องทางเข้าสู่บัญชีเดียวกันแล้ว',
		},
		notificationsTitle: 'การแจ้งเตือนกิจกรรม',
		notificationsHint: 'เลือกช่องทางที่ Megu ใช้แจ้งผลกิจกรรมและการจ่ายเงิน อีเมลส่งจาก Megu ไม่ได้ส่งในนาม Gmail ของคุณ',
		modes: { discord: 'Discord เท่านั้น', email: 'อีเมลเท่านั้น', both: 'Discord + อีเมล', off: 'ปิด' },
		modeHints: { discord: 'ส่งผ่านบอท Megu ใน Discord', email: 'ส่งไปยังอีเมล Google ที่ยืนยันแล้ว', both: 'ส่งแยกกันทั้งสองช่องทาง', off: 'ไม่ส่งการแจ้งเตือนกิจกรรมที่เลือกปิดได้' },
		connectFirst: 'เชื่อม provider นี้ก่อน',
		saved: 'บันทึกการแจ้งเตือนแล้ว',
	},

	servers: {
		signedOutTitle: 'เซิร์ฟเวอร์ของคุณ',
		signedOutLede: 'เข้าสู่ระบบเพื่อดูเซิร์ฟเวอร์ที่คุณดูแล แล้วตั้งค่าให้ Megu ทำงานในนั้น',

		// หน้านี้คือคอนโซลของบอทใน Discord ไม่ใช่ส่วนกิจกรรม — การล็อกอิน Megu
		// ด้วย Google อย่างเดียวจึงเปิดไม่ได้ ต้องมี Discord ที่อนุญาตให้ Megu
		// อ่านรายชื่อเซิร์ฟเวอร์ ข้อความเลยต้องบอกให้ชัดว่าติดอะไร ไม่ใช่บอกว่า
		// "เข้าสู่ระบบ" กับคนที่ล็อกอินอยู่แล้ว
		discordNeededTitle: 'ส่วนนี้ต้องใช้ Discord',
		discordNeededLede: 'หน้านี้คือคอนโซลของบอท Megu ใน Discord จึงต้องเชื่อมบัญชี Discord ก่อน จะได้รู้ว่าคุณดูแลเซิร์ฟเวอร์ไหนบ้าง บัญชีที่คุณใช้อยู่ตอนนี้ยังไม่ได้เชื่อม',
		discordNeededAction: 'ไปเชื่อม Discord',
		discordExpiredTitle: 'เชื่อม Discord อีกครั้ง',
		discordExpiredLede: 'บัญชีของคุณเชื่อม Discord ไว้แล้ว แต่ Megu ขอรายชื่อเซิร์ฟเวอร์จาก Discord ไม่ได้ตอนนี้ — สิทธิ์อาจหมดอายุหรือถูกถอนไป เชื่อมอีกครั้งแล้วจะกลับมาเหมือนเดิม',
		discordExpiredAction: 'เชื่อม Discord อีกครั้ง',
		title: 'เลือกเซิร์ฟเวอร์ที่จะตั้งค่า',
		activeCount: n => `${n} เซิร์ฟเวอร์ที่มี Megu อยู่`,
		missingCount: n => `${n} เซิร์ฟเวอร์ที่ยังไม่ได้เชิญ`,
		managedCount: n => `${n} เซิร์ฟเวอร์ที่คุณดูแล`,
		owner: 'เจ้าของ',
		manager: 'ผู้ดูแล',
		unknown: 'ตรวจสอบไม่ได้',
		ready: 'พร้อมใช้งาน',
		notInstalled: 'ยังไม่มี Megu',
		members: (count, id) => `${count} คน · ID ${id}`,
		invite: '+ เชิญ Megu',
		configure: 'ตั้งค่า',
		statusUnavailableTitle: 'ตรวจสอบสถานะ Megu ไม่ได้',
		statusUnavailableBody: 'เว็บติดต่อโพรเซสบอทไม่สำเร็จ จึงยังบอกไม่ได้ว่าเซิร์ฟเวอร์ไหนมี Megu แล้ว ไม่ได้แปลว่าไม่มี',
		statusUnavailableHelpBefore: 'มักเกิดจากรัน',
		statusUnavailableHelpMiddle: 'เดี่ยวๆ หรือโพรเซสบอทไม่ได้ทำงาน — รัน',
		statusUnavailableHelpAfter: 'เพื่อเปิดทั้งบอทและเว็บพร้อมกัน',
		empty: 'ไม่พบเซิร์ฟเวอร์ที่คุณดูแล — หน้านี้แสดงเฉพาะเซิร์ฟเวอร์ที่คุณเป็นเจ้าของหรือมีสิทธิ์จัดการเซิร์ฟเวอร์',
	},

	footer: {
		tagline: 'ผู้จัดการกิจกรรมของกลุ่มคุณ',
	},

	theme: {
		modes: { system: 'ตามเครื่อง', light: 'กลางวัน', dark: 'กลางคืน' },
		title: mode => `ธีม: ${mode}`,
		change: mode => `เปลี่ยนธีม — ตอนนี้${mode}`,
	},

	common: {
		loading: 'กำลังโหลด…',
		save: 'บันทึก',
		saving: 'กำลังบันทึก…',
		cancel: 'ยกเลิก',
		edit: 'แก้ไข',
		done: 'เสร็จแล้ว',
		remove: 'เอาออก',
		add: 'เพิ่ม',
		copy: 'คัดลอก',
		copied: 'คัดลอกแล้ว',
		close: 'ปิด',
		you: 'คุณ',
	},

	errors: {
		title_required: 'กรุณาใส่ชื่อกิจกรรม',
		participant_required: 'เพิ่มผู้เข้าร่วมอย่างน้อยหนึ่งคน หรือเลือกว่าคุณเข้าร่วมด้วย',
		display_name_required: 'กรุณาใส่ชื่อที่ต้องการใช้',
		display_name_too_long: 'ชื่อยาวได้ไม่เกิน 80 ตัวอักษร',
		currency_not_supported: 'ยังไม่รองรับสกุลเงินนี้',
		owner_only: 'เฉพาะเจ้าของกิจกรรมเท่านั้นที่เปลี่ยนส่วนนี้ได้',
		payment_option_invalid: 'ตรวจสอบช่องทางการจ่ายเงินแล้วลองอีกครั้ง',
		payment_link_invalid: 'กรุณาใส่ลิงก์ชำระเงินแบบ http หรือ https ที่ถูกต้อง',
		payment_destination_required: 'กรุณาใส่ธนาคารหรือบัญชีปลายทาง',
		notFound: 'ไม่พบกิจกรรมนี้',
		notFoundHint: 'ลิงก์อาจหมดอายุ หรือรหัสพิมพ์ผิด',
		failed: 'ทำรายการไม่สำเร็จ',
		offline: 'เชื่อมต่อไม่ได้ ลองใหม่อีกครั้ง',
		promptpay_missing: 'ยังไม่ได้ใส่เลขพร้อมเพย์',
		promptpay_unrecognised: 'เลขนี้ไม่เหมือนพร้อมเพย์',
		slip_duplicate: 'สลิปนี้ถูกใช้ไปกับรายการอื่นแล้ว',
		slip_too_large: 'รูปใหญ่เกินไป ลองเลือกจากคลังภาพอีกที',
		slip_unreadable: 'อ่านไฟล์นี้เป็นรูปไม่ได้',
		participant_has_money: 'คนนี้มีรายการเงินอยู่ ลบค่าใช้จ่ายที่เกี่ยวข้องก่อน',
		participant_paid_out: 'คนนี้ออกเงินให้กลุ่มอยู่ ลบรายการค่าใช้จ่ายก่อน',
		participant_not_in_activity: 'ไม่พบคนนี้ในกิจกรรม',
		device_already_claimed: 'เบราว์เซอร์นี้เลือกเป็นชื่ออื่นไปแล้ว',
		participant_already_claimed: 'ชื่อนี้ถูกเลือกไปแล้ว ถ้าเป็นคุณจริงให้เจ้าของกิจกรรมรีเซ็ตชื่อให้',
		expense_not_found: 'ไม่พบรายการค่าใช้จ่ายนี้',
		not_on_this_activity: 'คุณไม่ได้อยู่ในกิจกรรมนี้',
		claim_your_name_first: 'เลือกชื่อตัวเองก่อน',
		nothing_outstanding: 'ไม่มียอดค้างที่ต้องจ่าย',
		payment_not_found: 'ไม่พบรายการจ่ายนี้',
		not_your_payment: 'รายการจ่ายนี้เป็นของคนอื่น',
		not_your_slip: 'เปิดดูได้เฉพาะคนที่ส่งกับคนที่รับเงิน',
		no_slip: 'รายการนี้ไม่ได้แนบสลิป',
		poll_not_ready: 'รอให้ทุกคนตอบก่อน แล้วค่อยฟันธงเวลา',
		time_not_set: 'เลือกวันเวลาก่อนยืนยันกิจกรรม',
		split_people_required: 'เลือกก่อนว่าค่าใช้จ่ายนี้หารกับใครบ้าง',
		slot_required: 'เพิ่มช่วงเวลาที่เป็นไปได้อย่างน้อยหนึ่งช่วง',
		amount_invalid: 'กรุณาใส่ยอดเงินที่มากกว่าศูนย์',
		attendance_not_ready: 'จบกิจกรรมก่อน แล้วค่อยบันทึกว่าใครมาจริง',
		attendance_invalid: 'สถานะการเข้าร่วมต้องเป็น มา ไม่ได้มา หรือยังไม่เช็ก',
		session_expired: 'สถานะเข้าสู่ระบบหมดอายุ เข้าสู่ระบบอีกครั้งแล้วลองใหม่',
		last_identity: 'ยกเลิกช่องทางเข้าสู่ระบบสุดท้ายของบัญชีไม่ได้',
		identity_not_linked: 'บัญชีนี้ไม่ได้เชื่อมช่องทางดังกล่าว',
		notification_mode_invalid: 'เลือกช่องทางแจ้งเตือนที่ถูกต้อง',
		notification_discord_unavailable: 'เชื่อม Discord ก่อนเลือกการแจ้งเตือนผ่าน Discord',
		notification_email_unavailable: 'เชื่อมบัญชี Google ที่มีอีเมลยืนยันแล้วก่อนเลือกการแจ้งเตือนผ่านอีเมล',
		data_conflict: 'ข้อมูลเปลี่ยนไประหว่างบันทึก โหลดหน้าใหม่แล้วลองอีกครั้ง',
		recurring_only: 'ใช้คำสั่งนี้ได้เฉพาะกิจกรรมแบบรายเดือน',
		decision_invalid: 'เลือก confirm, reject หรือ undo',
	},

	plan: {
		open: 'รอคำตอบ',
		confirmed: 'ยืนยันแล้ว',
		done: 'เสร็จสิ้น',
		cancelled: 'ยกเลิก',
	},

	money: {
		none: 'ยังไม่มีค่าใช้จ่าย',
		open: 'รอชำระ',
		settled: 'จ่ายครบแล้ว',
	},

	activity: {
		notScheduled: 'ยังไม่กำหนดเวลา',
		noPeriodYet: 'ยังไม่เริ่มรอบ',
		dueOn: day => `ครบกำหนดวันที่ ${day}`,
		peopleGoing: (going, total) => `ไป ${going}/${total} คน`,
		members: total => `${total} คน`,
		membersPaid: (paid, total) => `จ่ายแล้ว ${paid} จาก ${total} คน`,
		perMonth: amount => `${amount} ต่อเดือน`,
		eachPerMonth: amount => `คนละ ${amount}`,
	},

	// รายการของเจ้าของกิจกรรม ที่ /activities — ทุกคำที่คนอ่านเห็นก่อนจะสร้าง
	// อะไรสักอย่างอยู่ในนี้ มันเลยเป็นคำอธิบายตัวเองอันแรกของโปรดักต์
	// ตัวอย่างในนี้จึงมีหน้าที่จริง ไม่ใช่ของประดับ ตอนที่เหลือตัวอย่างเดียว
	// ("ตีแบด") คนอ่านเข้าใจว่า Megu เอาไว้จองคอร์ทแบดอย่างเดียว
	activities: {
		title: 'กิจกรรมของคุณ',
		liveCount: n => `${n} รายการที่ยังเดินอยู่`,
		pastCount: n => `${n} รายการที่จบแล้ว`,
		newActivity: 'เปิดกิจกรรมใหม่',
		liveTitle: 'กำลังเดินอยู่',
		pastTitle: 'ที่ผ่านมา',
		monthly: 'รายเดือน',
		openMenu: 'เปิด',
		standing: {
			awaitingConfirmation: (n, amount) => amount
				? `รอยืนยัน ${n} รายการ · ค้าง ${amount}`
				: `รอยืนยัน ${n} รายการ`,
			outstanding: (n, amount) => `ค้าง ${amount} · ${n} คน`,
			answered: (answered, total) => `ตอบแล้ว ${answered}/${total}`,
			allAnswered: total => `ตอบครบ ${total}/${total}`,
			settled: 'จ่ายครบแล้ว',
		},

		empty: {
			says: 'ยังไม่มีอะไรเลย เริ่มอันแรกกันไหม',
			lede: 'อะไรก็ได้ที่มีคนหลายคนกับเงินเข้ามาเกี่ยว Megu ดูให้ได้หมด:',
			examples: [
				'กินข้าวกัน แล้วหารตอนบิลมา',
				'ทริปที่มีคนจองจ่ายไปก่อน',
				'ซื้อของเข้าบ้านรวมกัน',
				'ค่าห้อง ค่าเน็ต ที่เก็บทุกเดือน',
				'ของขวัญที่ลงขันกัน',
			],
		},

		kind: {
			legend: 'แบบไหน',
			event: 'ครั้งเดียวจบ',
			eventHint: 'กินข้าว ไปเที่ยว ซื้อของ ตีแบด — นัดกันครั้งเดียว หารกันแล้วจบ',
			recurring: 'เก็บทุกเดือน',
			recurringHint: 'ค่าเน็ต Netflix ค่าห้อง — ยอดเดิมทุกเดือน Megu เปิดรอบให้เอง',
		},

		saysEvent: 'จะทำอะไร กับใครบ้าง เดี๋ยวเราไปถามให้เอง',
		saysRecurring: 'ของที่ต้องเก็บทุกเดือน บอกมาว่าเท่าไหร่ กับใครบ้าง',

		titleField: 'เรียกว่าอะไรดี',
		titlePlaceholderEvent: 'กินหมูกระทะเสาร์นี้',
		titlePlaceholderRecurring: 'ค่าเน็ตบ้าน',
		examplesLabel: 'เช่น',
		exampleTitlesEvent: ['กินข้าว', 'ทริปเขาใหญ่', 'ตีแบด', 'ซื้อของเข้าบ้าน', 'ของขวัญวันเกิด'],
		exampleTitlesRecurring: ['ค่าเน็ต', 'Netflix', 'ค่าห้อง', 'ค่าน้ำค่าไฟ'],

		whenField: 'เมื่อไหร่',
		whenAsk: 'ให้ Megu ถามให้',
		whenKnown: 'รู้วันเวลาแล้ว',
		whenAskHint: 'Megu จะไปถามก่อนว่าใครว่างวันไหน แล้วค่อยฟันธงให้',

		whereField: 'ที่ไหน',
		wherePlaceholder: 'ร้าน หรือสถานที่',

		yourParticipation: {
			legend: 'คุณเข้าร่วมกิจกรรมนี้ด้วยไหม',
			joins: 'เข้าร่วมด้วย',
			organizes: 'สร้างให้คนอื่น',
			joinsHint: 'ระบบจะเพิ่มคุณลงในรายชื่อด้วยชื่อที่คุณกำหนดด้านล่าง',
			organizesHint: 'คุณยังเป็นเจ้าของและจัดการกิจกรรมได้ แต่จะไม่ถูกนับเป็นผู้เข้าร่วม',
			nameField: 'ชื่อของคุณในกิจกรรมนี้',
			nameHint: 'ใช้ชื่อและภาษาใดก็ได้ ชื่อนี้แยกจาก username ที่ใช้เข้าสู่ระบบ',
			saveDefault: 'ใช้ชื่อนี้เป็นค่าเริ่มต้นสำหรับกิจกรรมครั้งต่อไป',
		},
		currencyField: 'สกุลเงิน',
		currencyHint: 'ทุกคนในกิจกรรมนี้จะเห็นและเคลียร์ยอดด้วยสกุลเงินเดียวกัน',
		peopleField: 'มีใครเข้าร่วมอีกบ้าง',
		peoplePlaceholder: 'โอม, นัท, ฟิก',
		peopleHint: 'คั่นด้วยลูกน้ำหรือขึ้นบรรทัดใหม่ — เพื่อนไม่ต้องสมัครอะไรทั้งนั้น แค่ส่งลิงก์ให้',

		amountField: currency => `เดือนละเท่าไหร่ (${currency})`,
		initialPayerField: 'ใครเป็นคนจ่ายก้อนนี้ก่อน',
		initialPayerHint: 'คนนี้เป็นผู้สำรองจ่าย และเป็นคนที่กลุ่มจะจ่ายคืนให้',
		dueDayField: 'เก็บเงินทุกวันที่',
		dueDayHint: 'ของทุกเดือน (1–28)',

		serverField: 'เซิร์ฟเวอร์ Discord',
		serverNone: 'ไม่ผูกกับเซิร์ฟเวอร์',

		optional: 'ไม่ใส่ก็ได้',
		create: 'สร้างแล้วเอาลิงก์ไปแปะ',
		creating: 'กำลังสร้าง…',

		signedOutTitle: 'สวัสดี เราชื่อ Megu',
		signedOutLede: 'เราจะช่วยจัดกิจกรรมให้กลุ่มคุณ ตั้งแต่ถามว่าใครไป จนถึงตามเงินให้ครบ',
		signIn: 'เข้าสู่ระบบด้วย Discord',
	},

	headline: {
		youOwe: 'คุณต้องจ่าย',
		youGetBack: 'คุณจะได้คืน',
		yourTotal: 'ยอดของคุณ',
		clear: 'เคลียร์แล้ว',
		pay: 'จ่ายเลย',
		claimed: 'แจ้งจ่ายแล้ว รอยืนยัน',
	},

	claim: {
		title: 'คุณคือใครในกิจกรรมนี้',
		hint: 'กดชื่อตัวเองได้เลย ไม่ต้องสมัคร ไม่ต้องโหลดแอป',
		takenByThisDevice: name => `เครื่องนี้ถูกใช้เป็น "${name}" ไปแล้ว`,
	},

	rsvp: {
		question: name => `${name} ไปไหม`,
		going: 'ไป',
		notGoing: 'ไม่ไป',
	},

	schedule: {
		title: 'เลือกเวลาก่อน',
		ownerHint: 'ใส่เวลาที่เป็นไปได้สักสองสามตัวเลือก แล้ว Megu จะถามทุกคนให้ ก่อนเปิดให้ตอบว่าไปไหม',
		waitingHint: 'เจ้าของกำลังเตรียมตัวเลือกเวลา พอส่งมาแล้วคุณจะตอบได้ทันที',
	},

	roster: {
		titleEvent: 'ใครไปบ้าง',
		titleRecurring: 'สมาชิก',
		going: 'ไป',
		notGoing: 'ไม่ไป',
		noAnswer: 'ยังไม่ตอบ',
		notLinked: 'ยังไม่ได้เลือกชื่อตัวเอง',
		paidUp: 'ครบแล้ว',
		clear: 'เคลียร์',
		getsBack: amount => `ได้คืน ${amount}`,
		paidFor: period => `จ่าย${period}แล้ว`,
		owesFor: (amount, period) => `ค้าง ${amount} ของ${period}`,
		leftOn: period => `ออกไปตอน${period}`,
		addPerson: 'เพิ่มคน…',
		nameOf: name => `ชื่อของ ${name}`,
		returnName: 'คืนชื่อ',
		confirmRemove: name => `เอา ${name} ออกจากกิจกรรม?`,
	},

	attendance: {
		title: 'ใครมาจริง',
		hint: 'เช็กหลังจบกิจกรรม เพื่อให้ประวัติบอกสิ่งที่เกิดขึ้นจริง ไม่ใช่แค่สิ่งที่ตอบไว้',
		came: 'มา',
		absent: 'ไม่ได้มา',
		marked: (done, total) => `เช็กแล้ว ${done}/${total}`,
	},

	expenses: {
		title: 'ค่าใช้จ่าย',
		total: 'รวม',
		frontedBy: name => `${name} ออกให้ก่อน`,
		labelField: 'ค่าอะไร',
		amountField: 'จำนวนเงิน',
		payerField: 'ใครออกให้ก่อน',
		payerOption: name => `${name} ออกให้ก่อน`,
		splitField: 'หารกับใครบ้าง',
		splitHint: 'คนที่ติ๊กจะมียอดต้องจ่าย ตรวจรายชื่อก่อนเพิ่มค่าใช้จ่าย',
		forPerson: name => `ของ ${name}`,
		splitBetween: names => `หารกับ ${names}`,
		viewSplit: 'ดูยอดต่อคน',
		confirmDelete: (label, amount) => `ลบ "${label}" ${amount}?`,
	},

	pending: {
		title: 'รอคุณยืนยัน',
		saidTheyPaid: 'แจ้งว่าจ่ายแล้ว',
		received: 'ได้รับแล้ว',
		notYet: 'ยังไม่เข้า',
		confirmedTitle: 'ที่ยืนยันไปแล้ว',
		historyTitle: 'ประวัติการชำระที่ถูกย้อนผล',
		undo: 'ยกเลิกการยืนยัน',
		reversalReason: 'เหตุผลที่ยกเลิกผลการชำระ (ลูกหนี้จะเห็นข้อความนี้)',
		rejectionReason: 'เหตุผลที่ปฏิเสธการชำระ (ลูกหนี้จะเห็นข้อความนี้)',
		rejectedNotice: reason => `การชำระถูกปฏิเสธ: ${reason}`,
		reversedNotice: reason => `ผลการชำระถูกยกเลิก: ${reason}`,
		allocatedFromTransfer: (allocated, total) => `ส่วนของรอบนี้ ${allocated} จากยอดโอนรวม ${total}`,
		autoMatched: 'ระบบจับคู่สลิปให้อัตโนมัติ',
		ownerConfirmed: 'เจ้าของตรวจและยืนยันแล้ว',
		cashConfirmed: 'เจ้าของยืนยันรับเงินนอกระบบ',
		confirmDeletePayment: 'ยกเลิกรายการนี้โดยเก็บประวัติไว้?',
	},

	cash: {
		title: 'รับเงินนอกระบบ',
		hint: 'ใช้เมื่อได้รับเงินสดหรือเช็คยอดเองแล้ว รายการนี้ไม่มีสลิปและจะยืนยันด้วยชื่อคุณ',
		person: 'รับจาก',
		amount: 'จำนวนเงิน (บาท)',
		received: 'บันทึกว่าได้รับเงินแล้ว',
		reason: 'เจ้าของยืนยันว่าได้รับเงินนอกระบบแล้ว',
	},

	poll: {
		title: 'ว่างช่วงไหน',
		allAnswered: 'ตอบครบแล้ว',
		waitingFor: n => `รออีก ${n} คน`,
		free: 'ว่าง',
		maybe: 'อาจจะ',
		busy: 'ไม่ว่าง',
		freeCount: n => `ว่าง ${n}`,
		maybeCount: n => `อาจจะ ${n}`,
		busyCount: n => `ไม่ว่าง ${n}`,
		meguSuggests: 'Megu ว่าควรเป็น',
		lockIt: 'ฟันธงเวลานี้',
		option: i => `ตัวเลือกที่ ${i}`,
		anotherOption: '+ อีกตัวเลือก',
		askForMe: 'ให้ Megu ไปถามให้',
	},

	owner: {
		title: 'ตัวจัดการ',
		findTime: 'ให้ Megu หาเวลาที่ตรงกัน',
		proposeAgain: 'เสนอเวลาใหม่',
		confirmTime: 'ยืนยันวันเวลา',
		finish: 'จบกิจกรรมแล้ว',
		openMonth: 'เปิดรอบเดือนนี้',
		monthAlreadyOpen: period => `เปิดรอบ${period}ไปแล้ว`,
		monthOpened: period => `เปิดรอบ${period}แล้ว`,
		addExpense: 'เพิ่มค่าใช้จ่าย',
		addAndSplit: 'เพิ่มแล้วหารให้เลย',
		cancelActivity: 'ยกเลิกกิจกรรม',
		confirmCancel: 'ยกเลิกกิจกรรมนี้?',
	},

	invite: {
		title: 'ชวนคนอื่น',
		hint: 'ส่งลิงก์นี้ในกลุ่มได้เลย เพื่อนไม่ต้องสมัครอะไร',
		linkLabel: 'ลิงก์กิจกรรม',
		networkOnly: 'โหมดทดสอบ: ลิงก์นี้เปิดได้จากอุปกรณ์ที่อยู่ใน Wi-Fi หรือเครือข่ายเดียวกัน',
		deviceOnly: 'ลิงก์นี้ยังเปิดได้เฉพาะเครื่องนี้ ตั้ง FRONTEND_URL เป็น URL ที่คนอื่นเข้าถึงได้ก่อนแชร์',
		copyFailed: 'คัดลอกอัตโนมัติไม่ได้ ลิงก์ถูกเลือกไว้แล้ว—แตะค้างหรือกด Ctrl+C เพื่อคัดลอก',
	},

	pay: {
		title: 'จ่ายเงิน',
		payTo: name => `โอนให้ ${name}`,
		organizerRecipient: 'เจ้าของกิจกรรม',
		amountLabel: 'ยอดที่ต้องโอน',
		scanHint: 'สแกนด้วยแอปธนาคาร',
		sameDeviceHint: 'อยู่บนมือถือใช่ไหม กดบันทึกรูป QR แล้วใช้ “สแกนจากคลังภาพ” ในแอปธนาคารได้เลย',
		saveImage: 'บันทึกรูป QR',
		saved: 'บันทึกแล้ว',
		orTransferTo: 'หรือโอนไปที่พร้อมเพย์',
		copyNumber: 'คัดลอกเลข',
		copyAmount: 'คัดลอกยอด',
		numberCopied: 'คัดลอกเลขแล้ว',
		amountCopied: 'คัดลอกยอดแล้ว',
		choosePeriods: 'เลือกงวดและยอดที่จะจ่าย',
		selectAllOutstanding: 'เลือกที่ค้างทั้งหมด',
		amountFor: period => `ยอดสำหรับ ${period}`,
		allocationHint: 'จ่ายบางส่วนได้ และเลือกหลายเดือนได้ในสลิปเดียว',
		baht: 'บาท',
		iHavePaid: 'โอนแล้ว',
		attachSlip: 'แนบสลิป',
		attachSlipHint: 'แนบหลักฐานการโอนเพื่อช่วยให้เจ้าของตรวจ ระบบจะเก็บเฉพาะข้อมูลหลักฐานที่จำเป็น',
		slipAttached: 'แนบสลิปแล้ว',
		replaceSlip: 'เปลี่ยนสลิป',
		viewSlip: 'ดูสลิป',
		reading: 'กำลังอ่านสลิป…',
		noPromptPay: name => `${name} ยังไม่ได้ใส่เลขพร้อมเพย์`,
		noPromptPayOwner: 'ใส่เลขพร้อมเพย์ไว้ เพื่อนจะได้ QR ที่ใส่ยอดมาให้แล้ว ไม่ต้องพิมพ์เอง',
		waitingConfirm: 'แนบสลิปเพื่อให้ระบบตรวจและบันทึกการชำระ',
		waitingOwnerConfirm: 'รอเจ้าของกิจกรรมยืนยันการชำระนี้',
		chooseMethod: 'ต้องการจ่ายด้วยช่องทางไหน',
		noPaymentMethod: name => `${name} ยังไม่ได้เพิ่มวิธีรับเงิน ถามช่องทางให้เรียบร้อยก่อนแจ้งว่าจ่ายแล้ว`,
		openPaymentLink: 'เปิดลิงก์ชำระเงิน',
		copyDestination: 'คัดลอกรายละเอียด',
		destinationCopied: 'คัดลอกรายละเอียดแล้ว',
		currencyUnit: currency => currency,
	},

	paymentMethods: {
		title: 'ช่องทางจ่ายเงิน',
		hint: 'PromptPay เป็นเพียงตัวเลือกหนึ่ง เพิ่มบัญชีธนาคาร ลิงก์ชำระ เงินสด หรือคำแนะนำที่เหมาะกับกลุ่มนี้ได้',
		typeField: 'ประเภท',
		labelField: 'ชื่อที่จะแสดงให้ผู้เข้าร่วม',
		labelPlaceholder: 'เช่น Wise, โอนธนาคาร, จ่ายเงินสด',
		destinationField: 'ธนาคารหรือรายละเอียดบัญชี',
		destinationPlaceholder: 'ชื่อธนาคาร เลขบัญชี หรือ routing details',
		accountNameField: 'ชื่อเจ้าของบัญชี',
		urlField: 'ลิงก์ชำระเงิน',
		instructionsField: 'คำแนะนำเพิ่มเติม (ถ้ามี)',
		instructionsPlaceholder: 'ข้อมูลที่ผู้จ่ายจำเป็นต้องรู้',
		add: 'เพิ่มช่องทางนี้',
		save: 'บันทึกช่องทางจ่ายเงิน',
		types: {
			bank_transfer: 'โอนธนาคาร',
			payment_link: 'ลิงก์ชำระเงิน',
			cash: 'เงินสด',
			custom: 'คำแนะนำแบบกำหนดเอง',
		},
	},

	promptpay: {
		title: 'เงินเข้าที่ไหน',
		field: 'พร้อมเพย์ของคุณ (เบอร์โทร หรือเลขบัตร)',
		nameField: 'ชื่อบัญชี',
		nameHint: 'โชว์ให้คนโอนเช็คว่าโอนถูกคน',
		hint: 'เงินโอนจากเขาเข้าบัญชีคุณโดยตรง Megu ไม่ถือเงินและไม่เห็นเงิน',
		saved: 'บันทึกแล้ว',
		payee: 'ทุกคนโอนให้',
		payeeField: 'ใครเป็นคนรับเงิน',
		organizerOption: name => `เจ้าของกิจกรรม${name ? ` — ${name}` : ''}`,
		notSet: 'ยังไม่ได้ตั้ง',
		remove: 'เอาเลขนี้ออก',
		fromQr: 'อ่านจากรูป QR ของฉัน',
		fromQrHint: 'เลือกรูป QR พร้อมเพย์ที่แอปธนาคารบันทึกไว้ อ่านในเครื่องนี้ ไม่ได้ส่งรูปขึ้นเซิร์ฟเวอร์',
		reading: 'กำลังอ่านรูป…',
		qrRead: masked => `อ่านได้จากรูป: ${masked}`,
		qrAmountIgnored: amount => `ใน QR นั้นมียอด ${amount} ติดมาด้วย เก็บไว้แต่เลขบัญชี — ยอดเงิน Megu ใส่ให้ใหม่ทุกครั้ง`,
	},

	slip: {
		verdictUnread: 'แนบสลิปแล้ว — อ่านรหัสอ้างอิงไม่ออก',
		verdictReview: 'แนบสลิปแล้ว — รอเจ้าของตรวจ',
		verdictMatched: 'แนบสลิปแล้ว',
		verdictDuplicate: 'สลิปนี้เคยใช้ไปแล้ว',
		expected: amount => `ยอดที่ขอไป ${amount}`,
		uploaded: when => `แนบเมื่อ ${when}`,
		privacyNote: 'เปิดดูได้เฉพาะคุณกับคนที่ส่งมา',
		readingImage: 'กำลังอ่านสลิป…',
		sentFrom: bank => `โอนจาก ${bank}`,
		readAmount: amount => `ในสลิปอ่านได้ ${amount}`,
		readDiffers: (read, expected) => `ในสลิปอ่านได้ ${read} แต่ยอดที่ขอไปคือ ${expected}`,
		readNote: 'อ่านจากรูป ไม่ได้เช็คกับธนาคาร ดูอีกรอบก่อนกดยืนยัน',
	},

	receipt: {
		scan: 'สแกนใบเสร็จ',
		hint: 'ถ่ายรูปใบเสร็จ Megu จะอ่านรายการออกมาให้ ตรวจก่อนค่อยเพิ่มเข้าไป',
		reading: 'กำลังอ่านใบเสร็จ…',
		found: count => `อ่านได้ ${count} รายการ`,
		checkNote: 'อ่านมาจากรูป ตรวจอีกทีนะ แก้ได้ทุกช่อง อันไหนไม่เอาก็ติ๊กออก',
		selected: count => `เลือกไว้ ${count} รายการ`,
		matchesPrinted: total => `รวมแล้วตรงกับยอด ${total} ที่พิมพ์บนใบเสร็จ`,
		differsFromPrinted: (total, gap) => `บนใบเสร็จเขียน ${total} — ต่างกันอยู่ ${gap}`,
		addAll: (count, total) => `เพิ่ม ${count} รายการ · ${total}`,
		asOneLine: total => `หรือเพิ่มทั้งบิลเป็นรายการเดียว (${total})`,
		wholeBill: 'ทั้งบิล',
		untitled: 'รายการ',
		serviceLine: 'ค่าบริการ',
		taxLine: 'ภาษีมูลค่าเพิ่ม',
		addService: amount => `เพิ่มค่าบริการ ${amount}`,
		addTax: amount => `เพิ่มภาษี ${amount}`,
		includeLine: label => `เอา ${label} ด้วย`,
		nothingFound: 'อ่านอะไรจากรูปนี้ไม่ได้เลย ลองใหม่ วางใบเสร็จให้เรียบและถ่ายให้ครบทั้งใบ',
		failed: 'อ่านรูปนี้ไม่ได้',
		partial: (added, total) => `เพิ่มไปแล้ว ${added} จาก ${total} รายการ แล้วติดขัด — ที่เหลือยังไม่ได้เพิ่ม`,
		unavailable: 'เซิร์ฟเวอร์นี้ยังไม่ได้ติดตั้งตัวอ่านใบเสร็จ',
	},
};

module.exports = th;
