'use strict';

const assert = require('node:assert/strict');
const { isDisposableTestDatabase } = require('./test-database');
const { installCompanySchema } = require('../core/company-schema');
const companies = require('../core/companies');
const teams = require('../core/teams');
const projects = require('../core/projects');
const accountMerge = require('../core/account-merge');
const express = require('express');
const cookieParser = require('cookie-parser');
const meguApi = require('../adapters/http/megu-api');
const db = require('../core/db');
const { initCoreSchema } = require('../core/schema');

async function main() {
	const url = process.env.MEGU_TEST_DATABASE_URL || process.env.MEGU_DATABASE_URL;
	assert.ok(isDisposableTestDatabase(url), 'Explicit local *_test database required');
	process.env.MEGU_DATABASE_URL = url;
	process.env.MEGU_COMPANIES_ENABLED = '1';
	await initCoreSchema();
	await db.transaction(installCompanySchema);
	const suffix = `${Date.now()}`;
	const owner = `company_owner_${suffix}`;
	const outsider = `company_outsider_${suffix}`;
	const member = `company_member_${suffix}`;
	const guildId = `9999${suffix}`;
	let companyId;
	let server;
	const teamIds = [`company_test_a_${suffix}`, `company_test_b_${suffix}`];
	try {
		await db.query('INSERT INTO users(id,display_name) VALUES ($1,$1),($2,$2),($3,$3)', [owner, outsider, member]);
		const verify = async (userId, id) => ({ available: true, guildId: id, userId, isOwner: true, botPresent: true, name: 'Test company' });
		await assert.rejects(companies.claimCompany(owner, { guildId }), { code: 'discord_verification_unavailable' });
		await assert.rejects(companies.claimCompany(owner, { guildId }, async () => ({ available: true, isOwner: false })), { code: 'company_claim_forbidden' });
		await assert.rejects(companies.claimCompany(owner, { guildId, role: 'owner' }, verify), { code: 'unknown_field' });
		const [first, retried] = await Promise.all([companies.claimCompany(owner, { guildId }, verify), companies.claimCompany(owner, { guildId }, verify)]);
		companyId = first.company.id;
		assert.equal(retried.company.id, companyId);
		assert.equal(first.company.lifecycle, 'active');
		assert.equal(first.capabilities.canCreateTeam, true);
		assert.equal((await db.query("SELECT count(*)::int AS n FROM company_events WHERE company_id=$1 AND event_type='company_claimed'", [companyId])).rows[0].n, 1);
		await assert.rejects(companies.claimCompany(outsider, { guildId }, verify), { code: 'company_already_claimed' });
		await assert.rejects(companies.getCompany(companyId, outsider), { code: 'company_not_found' });
		assert.equal((await companies.listCompanies(outsider)).companies.length, 0);
		await db.query("INSERT INTO company_memberships(company_id,user_id,role) VALUES ($1,$2,'member')", [companyId, member]);
		await db.query(`INSERT INTO teams(id,name,created_by,company_id) VALUES ($1,'A team',$3,$4),($2,'B team',$3,$4)`, [...teamIds, owner, companyId]);
		await db.query("INSERT INTO team_memberships(team_id,user_id,role) VALUES ($1,$2,'owner')", [teamIds[0], member]);
		await require('../core/team-membership-sources').grantManualSource(db, teamIds[0], member, member, 'test_fixture');
		const project = await projects.createProject({ ownerUserId: member, title: 'Private company project', teamId: teamIds[0] });
		await assert.rejects(projects.getProjectByCode(project.code, owner), { code: 'project_not_found' });
		const ownTeams = await companies.listCompanyTeams(companyId, member);
		assert.deepEqual(ownTeams.teams.map(t => t.id), [teamIds[0]]);
		const directory = await companies.listCompanyTeams(companyId, owner, { limit: 1 });
		assert.equal(directory.teams.length, 1);
		assert.equal(directory.teams[0].canOpen, false, 'Company ownership does not imply private team membership');
		assert.deepEqual((await companies.listCompanyTeams(companyId, owner, { ownOnly: 'true' })).teams, [], 'Overview excludes structural-only teams before pagination');
		assert.deepEqual((await companies.listCompanyTeams(companyId, member, { ownOnly: 'false' })).teams.map(t => t.id), [teamIds[0]], 'Query options never expand ordinary member visibility');
		assert.ok(directory.nextCursor);
		const next = await companies.listCompanyTeams(companyId, owner, { limit: 1, cursor: directory.nextCursor });
		assert.equal(next.teams[0].id, teamIds[1]);
		assert.equal(next.nextCursor, null);
		await assert.rejects(companies.updateCompany(companyId, member, { name: 'Wrong', expectedRevision: first.company.revision }), { code: 'company_forbidden' });
		const updated = await companies.updateCompany(companyId, owner, { name: 'Renamed', expectedRevision: first.company.revision });
		assert.equal(updated.company.name, 'Renamed');
		await assert.rejects(companies.updateCompany(companyId, owner, { name: 'Stale', expectedRevision: first.company.revision }), { code: 'company_revision_conflict' });
		await db.query("UPDATE companies SET lifecycle='archived',archived_at=now() WHERE id=$1", [companyId]);
		assert.equal((await projects.getProjectByCode(project.code, member)).project.code, project.code);
		await assert.rejects(projects.createProject({ ownerUserId: member, title: 'Blocked', teamId: teamIds[0] }), { code: 'company_archived' });
		await assert.rejects(teams.updateTeam(teamIds[0], member, { name: 'Blocked', expectedRevision: 0 }), { code: 'company_archived' });
		await db.query("UPDATE companies SET lifecycle='active',archived_at=NULL WHERE id=$1", [companyId]);
		await db.query('UPDATE company_memberships SET revoked_at=now() WHERE company_id=$1 AND user_id=$2', [companyId, member]);
		await assert.rejects(companies.listCompanyTeams(companyId, member), { code: 'company_not_found' });
		await assert.rejects(teams.getTeam(teamIds[0], member), { code: 'team_not_found' });
		await assert.rejects(projects.getProjectByCode(project.code, member), { code: 'project_not_found' });
		assert.equal((await teams.listTeamsForUser(member)).teams.length, 0);
		assert.equal((await projects.listProjectsForUser(member)).length, 0);
		const hiddenDirectory = await projects.listProjectDirectory(member);
		assert.equal(hiddenDirectory.projects.length, 0);
		assert.equal(hiddenDirectory.hasAnyProjects, false);
		assert.equal((await accountMerge.planMerge(owner, member)).blockedBy.reason, 'company-membership-conflict');
		await assert.rejects(accountMerge.mergeAccounts({ userIdA: owner, userIdB: member }), /merge_company_membership_conflict/);
		assert.equal((await db.query('SELECT count(*)::int AS n FROM users WHERE id=ANY($1::text[])', [[owner, member]])).rows[0].n, 2);
		const app = express();
		app.use(express.json());
		app.use(cookieParser());
		app.use((req, res, next) => { req.session = { meguUserId: req.headers['x-test-user'] }; next(); });
		let serverMembership = { available: true, isMember: true, isBot: false };
		let requestedManagement = false;
		let discovery = { available: true, guilds: [{ id: guildId, name: 'Member server', icon: null, permissions: '0', privateField: 'not public' }] };
		let roleLookup = { available: true, guildId, roles: [
			{ id: '123456789012345678', guildId, name: 'Development', color: '#abcdef', position: 2, managed: false },
			{ id: guildId, guildId, name: '@everyone' },
			{ id: '123456789012345679', guildId, name: 'Integration', managed: true },
			{ id: '123456789012345680', guildId: '998877665544332211', name: 'Other server' },
		] };
		app.use('/api/megu', meguApi.router({ verifyCompanyGuildOwner: verify,
			verifyDiscordGuildMember: async (userId, id, options) => { requestedManagement = options?.management === true; return { userId, guildId: id, ...serverMembership }; },
			listDiscordGuildRoles: async () => roleLookup,
			listDiscordGuildCandidates: async ({ guildId: id }) => ({ available: true, guildId: id, members: [{ id: `7777${suffix}`, displayName: 'Registered owner', isBot: false }], nextOffset: null }),
			listWorkspaceDiscordGuilds: async session => { assert.ok(session.meguUserId); return discovery; },
		}));
		server = await new Promise(resolve => { const listening = app.listen(0, '127.0.0.1', () => resolve(listening)); });
		const base = `http://127.0.0.1:${server.address().port}/api/megu`;
		assert.equal((await fetch(`${base}/teams/${teamIds[0]}/summary`)).status,401);
		assert.equal((await fetch(`${base}/teams/${teamIds[0]}/summary`,{headers:{'x-test-user':outsider}})).status,404);
		assert.equal((await fetch(`${base}/teams/${teamIds[0]}/summary`,{headers:{'x-test-user':owner}})).status,404,'Legacy Company authority cannot reveal private team metadata');
		const restoreTeam = (await teams.createTeam({ ownerUserId: owner, name: 'HTTP restoration' })).team;
		const summaryResponse=await fetch(`${base}/teams/${restoreTeam.id}/summary`,{headers:{'x-test-user':owner}});
		assert.equal(summaryResponse.status,200);
		const summaryBody=await summaryResponse.json();
		assert.equal(summaryBody.team.id,restoreTeam.id);
		assert.equal(Object.hasOwn(summaryBody,'projects'),false);
		teamIds.push(restoreTeam.id);
		const restoreLink = await teams.createJoinLink(restoreTeam.id, owner);
		await teams.requestTeamJoin(restoreLink.token, outsider);
		const restoreRequest = (await teams.listJoinRequests(restoreTeam.id, owner)).requests[0];
		await teams.reviewJoinRequest(restoreTeam.id, restoreRequest.id, owner, { action: 'approve' });
		await teams.removeTeamMember(restoreTeam.id, outsider, owner, { expectedRevision: (await teams.getTeam(restoreTeam.id, owner)).team.revision });
		await teams.requestTeamJoin(restoreLink.token, outsider);
		const restoreEndpoint = `${base}/teams/${restoreTeam.id}/join-requests/${restoreRequest.id}`;
		const restoreHeaders = { 'x-test-user': owner, 'Content-Type': 'application/json' };
		const restoreList = await fetch(`${base}/teams/${restoreTeam.id}/join-requests`, { headers: restoreHeaders });
		assert.match(restoreList.headers.get('cache-control'), /no-store/);
		const restoreMetadata = await restoreList.json();
		assert.equal(restoreMetadata.requests[0].restoreRequired, true); assert.ok(Number.isInteger(restoreMetadata.teamRevision));
		assert.equal((await fetch(restoreEndpoint, { method: 'POST', headers: { ...restoreHeaders, 'Sec-Fetch-Site': 'cross-site' }, body: '{"action":"approve","confirmRestore":true}' })).status, 403);
		assert.equal((await fetch(restoreEndpoint, { method: 'POST', headers: { 'x-test-user': owner, 'Content-Type': 'text/plain' }, body: '{"action":"approve","confirmRestore":true}' })).status, 415);
		assert.equal((await fetch(restoreEndpoint, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: '{"action":"approve","confirmRestore":true}' })).status, 401);
		const unconfirmed = await fetch(restoreEndpoint, { method: 'POST', headers: restoreHeaders, body: '{"action":"approve"}' });
		assert.equal(unconfirmed.status, 409); assert.equal((await unconfirmed.json()).code, 'team_member_restore_confirmation_required');
		assert.match(unconfirmed.headers.get('cache-control'), /no-store/);
		assert.equal((await fetch(restoreEndpoint, { method: 'POST', headers: restoreHeaders, body: '{"action":"approve","confirmRestore":"true"}' })).status, 422);
		assert.equal((await fetch(restoreEndpoint, { method: 'POST', headers: { ...restoreHeaders, 'x-test-user': outsider }, body: '{"action":"approve","confirmRestore":true}' })).status, 404);
		assert.equal((await fetch(restoreEndpoint, { method: 'POST', headers: restoreHeaders, body: '{"action":"approve","confirmRestore":true}' })).status, 409, 'Restoration requires the reviewed team revision');
		assert.equal((await fetch(restoreEndpoint, { method: 'POST', headers: restoreHeaders, body: JSON.stringify({ action: 'approve', confirmRestore: true, expectedRevision: (await teams.listJoinRequests(restoreTeam.id, owner)).teamRevision }) })).status, 200);
		const serverWorkspace = `${base}/teams/discord-guilds/${guildId}/workspace`;
		const discoveryEndpoint = `${base}/teams/workspace-guilds`;
		assert.equal((await fetch(discoveryEndpoint)).status, 401);
		const discoveredServers = await fetch(discoveryEndpoint, { headers: { 'x-test-user': owner } });
		assert.equal(discoveredServers.status, 200);
		assert.deepEqual(await discoveredServers.json(), { guilds: [{ id: guildId, name: 'Member server', icon: null }] }, 'Discovery exposes identity only, not permission claims');
		discovery = { available: false };
		assert.equal((await fetch(discoveryEndpoint, { headers: { 'x-test-user': owner } })).status, 503);
		process.env.MEGU_PROJECT_TEAMS_DISCORD_ENABLED = '0';
		assert.equal((await fetch(discoveryEndpoint, { headers: { 'x-test-user': owner } })).status, 404);
		delete process.env.MEGU_PROJECT_TEAMS_DISCORD_ENABLED;
		discovery = { available: true, guilds: [{ id: guildId, name: 'Old snapshot' }] };
		serverMembership = { available: true, isMember: false };
		assert.equal((await fetch(discoveryEndpoint, { headers: { 'x-test-user': owner } })).status, 200);
		assert.equal((await fetch(serverWorkspace, { headers: { 'x-test-user': owner } })).status, 403, 'Discovery snapshots never grant workspace membership');
		serverMembership = { available: true, isMember: true, isBot: false };
		assert.equal((await fetch(serverWorkspace)).status, 401);
		assert.equal((await fetch(serverWorkspace, { headers: { 'x-test-user': owner } })).status, 200, 'Fresh verification works without a cached session guild list');
		serverMembership = { available: false };
		assert.equal((await fetch(serverWorkspace, { headers: { 'x-test-user': owner } })).status, 503);
		serverMembership = { available: true, isMember: false };
		assert.equal((await fetch(serverWorkspace, { headers: { 'x-test-user': owner } })).status, 403);
		serverMembership = { available: true, isMember: true, guildId: '999999999999999999' };
		assert.equal((await fetch(serverWorkspace, { headers: { 'x-test-user': owner } })).status, 403);
		serverMembership = { available: true, isMember: true, isBot: true };
		assert.equal((await fetch(serverWorkspace, { headers: { 'x-test-user': owner } })).status, 403);
		serverMembership = { available: true, isMember: true, isBot: false };
		for (const section of ['teams', 'projects']) {
			const endpoint = `${serverWorkspace}/${section}`;
			assert.equal((await fetch(endpoint)).status, 401);
			const response = await fetch(`${endpoint}?limit=1`, { headers: { 'x-test-user': owner } });
			assert.equal(response.status, 200);
			const page = await response.json();
			assert.equal(page.section, section);
			assert.equal(page.nextOffset, null);
			assert.deepEqual(page[section], []);
			assert.equal(page.canManageTitles, false, 'Ordinary server members receive no title management capability');
			assert.equal(requestedManagement, true, 'Workspace capability requires fresh permission definitions');
			serverMembership.canManageServer = true;
			assert.equal((await (await fetch(endpoint, { headers: { 'x-test-user': owner } })).json()).canManageTitles, true);
			serverMembership.canManageServer = false;
			assert.equal((await fetch(`${endpoint}?limit=101`, { headers: { 'x-test-user': owner } })).status, 422);
			serverMembership = { available: true, isMember: false };
			assert.equal((await fetch(endpoint, { headers: { 'x-test-user': owner } })).status, 403);
			serverMembership = { available: true, isMember: true, isBot: false };
		}
		// The old feature flag cannot expose the retired organization API.
		const mappedTeam = await teams.createTeam({ ownerUserId: member, name: 'Role mapping HTTP test', discordGuildId: guildId, discordGuildName: 'Server workspace' });
		teamIds.push(mappedTeam.team.id);
		serverMembership = { available: true, isMember: true, isBot: false, canManageServer: true };
		const mappingUrl = `${base}/teams/discord-guilds/${guildId}/role-mappings/${mappedTeam.team.id}`;
		const requestMapping = (url, actor, body) => fetch(url, { method: 'POST', headers: { 'Content-Type': 'application/json', ...(actor ? { 'x-test-user': actor } : {}) }, body: JSON.stringify(body) });
		const retainUrl = `${base}/teams/${mappedTeam.team.id}/members/${member}/manual-grant`;
		const retainBody = { confirmed: true, expectedRevision: 0 };
		assert.equal((await requestMapping(retainUrl, null, retainBody)).status, 401);
		assert.equal((await requestMapping(retainUrl, owner, retainBody)).status, 404, 'Discord management is not private team authority');
		assert.equal((await fetch(retainUrl, { method: 'POST', headers: { 'x-test-user': member, 'Content-Type': 'text/plain' }, body: '{}' })).status, 415);
		assert.equal((await fetch(retainUrl, { method: 'POST', headers: { 'x-test-user': member, 'Content-Type': 'application/json', 'Sec-Fetch-Site': 'cross-site' }, body: '{}' })).status, 403);
		assert.equal((await requestMapping(retainUrl, member, { ...retainBody, confirmed: 'true' })).status, 409);
		assert.equal((await requestMapping(retainUrl, member, { ...retainBody, expectedRevision: -1 })).status, 409);
		assert.equal((await requestMapping(retainUrl, member, { ...retainBody, role: 'owner' })).status, 422);
		const retainedResponse = await requestMapping(retainUrl, member, retainBody);
		assert.equal(retainedResponse.status, 200);
		assert.equal(retainedResponse.headers.get('cache-control'), 'private, no-store');
		assert.equal((await retainedResponse.json()).alreadyManual, true);
		const creationBase = `${base}/teams/discord-guilds/${guildId}/role-teams`;
		for (const action of ['preview', 'create']) {
			assert.equal((await requestMapping(`${creationBase}/${action}`, null, {})).status, 401);
			assert.equal((await fetch(`${creationBase}/${action}`, { method: 'POST', headers: { 'x-test-user': owner, 'Content-Type': 'text/plain' }, body: '{}' })).status, 415);
			assert.equal((await fetch(`${creationBase}/${action}`, { method: 'POST', headers: { 'x-test-user': owner, 'Content-Type': 'application/json', 'Sec-Fetch-Site': 'cross-site' }, body: '{}' })).status, 403);
			assert.equal((await requestMapping(`${creationBase}/${action}`, owner, {})).status, 422);
		}
		await db.query("INSERT INTO identities(id,user_id,provider,provider_uid) VALUES ($1,$2,'discord',$3)", [`creation_owner_${suffix}`, member, `7777${suffix}`]);
		const ownersUrl = `${creationBase}/owners`;
		assert.equal((await fetch(ownersUrl)).status, 401);
		const ownersResponse = await fetch(ownersUrl, { headers: { 'x-test-user': owner } });
		assert.equal(ownersResponse.status, 200);
		assert.equal(ownersResponse.headers.get('cache-control'), 'private, no-store');
		assert.deepEqual((await ownersResponse.json()).candidates.map(candidate => candidate.userId), [member]);
		assert.equal((await fetch(`${ownersUrl}?offset=-1`, { headers: { 'x-test-user': owner } })).status, 422);
		serverMembership.canManageServer = false;
		assert.equal((await fetch(ownersUrl, { headers: { 'x-test-user': owner } })).status, 403);
		serverMembership.canManageServer = true;
		const extraRole = { id: '123456789012345699', guildId, name: 'New department' };
		roleLookup.roles.push(extraRole);
		const creationInput = { teams: [{ roleId: extraRole.id, ownerUserId: member, name: 'New department' }] };
		serverMembership.canManageServer = false;
		assert.equal((await requestMapping(`${creationBase}/preview`, owner, creationInput)).status, 403);
		serverMembership.canManageServer = true;
		const creationPreviewResponse = await requestMapping(`${creationBase}/preview`, owner, creationInput);
		assert.equal(creationPreviewResponse.status, 200);
		assert.equal(creationPreviewResponse.headers.get('cache-control'), 'private, no-store');
		const creationPreview = await creationPreviewResponse.json();
		const creationBody = { ...creationInput, requestKey: `http_creation_${suffix}`, expectedPreview: creationPreview.preview };
		const creationResponse = await requestMapping(`${creationBase}/create`, owner, creationBody);
		assert.equal(creationResponse.status, 200);
		const creationResult = await creationResponse.json();
		teamIds.push(...creationResult.teams.map(team => team.id));
		assert.deepEqual(await (await requestMapping(`${creationBase}/create`, owner, creationBody)).json(), creationResult);
		assert.equal((await requestMapping(`${creationBase}/create`, owner, { ...creationBody, teams: [{ ...creationInput.teams[0], name: 'Changed' }] })).status, 409);
		assert.equal((await teams.listTeamsForUser(owner)).teams.some(team => team.id === creationResult.teams[0].id), false, 'Creation grants no private team access to the server administrator');
		roleLookup.roles.pop();
		assert.equal((await requestMapping(mappingUrl, null, {})).status, 401);
		const proposalResponse = await requestMapping(mappingUrl, owner, { roleIds: ['123456789012345678'], expectedRevision: 0 });
		assert.equal(proposalResponse.status, 200);
		const proposed = await proposalResponse.json();
		assert.equal(proposed.enabled, false);
		assert.equal((await fetch(mappingUrl)).status,401);
		const managedMapping=await fetch(mappingUrl,{headers:{'x-test-user':owner}});
		assert.equal(managedMapping.status,200);assert.equal(managedMapping.headers.get('cache-control'),'private, no-store');
		const managedBody=await managedMapping.json();assert.deepEqual(Object.keys(managedBody),['mapping']);
		assert.equal(managedBody.mapping.id,proposed.id);assert.equal(managedBody.mapping.enabled,false);
		assert.equal((await fetch(`${base}/teams/${mappedTeam.team.id}/summary`,{headers:{'x-test-user':owner}})).status,404,'Configuration management cannot reveal private team metadata');
		for(const evidence of [
			{available:false}, {available:true,isMember:true,isBot:false,canManageServer:false},
			{available:true,isMember:false,isBot:false,canManageServer:true},
			{available:true,isMember:true,isBot:true,canManageServer:true},
			{available:true,isMember:true,isBot:false,canManageServer:true,guildId:'999999999999999999'},
			{available:true,isMember:true,isBot:false,canManageServer:true,userId:outsider},
		]) {
			serverMembership=evidence;
			assert.equal((await fetch(mappingUrl,{headers:{'x-test-user':owner}})).status,evidence.available?403:503);
		}
		serverMembership={available:true,isMember:true,isBot:false,canManageServer:true};
		assert.equal((await fetch(mappingUrl.replace(guildId,'999999999999999999'),{headers:{'x-test-user':owner}})).status,404);
		assert.equal((await fetch(`${base}/teams/discord-guilds/${guildId}/role-mappings/missing`,{headers:{'x-test-user':owner}})).status,404);
		await db.query("UPDATE server_role_mappings SET mode='automatic' WHERE id=$1",[proposed.id]);
		assert.equal((await requestMapping(mappingUrl,owner,{roleIds:['123456789012345678'],expectedRevision:proposed.revision})).status,409,'Approval proposal cannot silently retire automatic grants');
		assert.equal((await requestMapping(`${base}/teams/${mappedTeam.team.id}/role-mapping/approve`,member,{expectedRevision:proposed.revision})).status,409,'Owner approval cannot activate an unsupported automatic mode');
		assert.equal((await db.query('SELECT mode,revision FROM server_role_mappings WHERE id=$1',[proposed.id])).rows[0].revision,proposed.revision);
		await db.query("UPDATE server_role_mappings SET mode='approval' WHERE id=$1",[proposed.id]);
		const mappingRead = `${base}/teams/${mappedTeam.team.id}/role-mapping`;
		const titlesUrl = `${base}/teams/discord-guilds/${guildId}/title-roles`;
		assert.equal((await fetch(titlesUrl)).status, 401);
		assert.equal((await requestMapping(titlesUrl, owner, { roleIds: ['123456789012345678'], expectedRevision: 0 })).status, 200);
		const titlesResponse = await fetch(titlesUrl, { headers: { 'x-test-user': owner } });
		assert.equal(titlesResponse.headers.get('cache-control'), 'private, no-store');
		assert.equal((await titlesResponse.json()).roles[0].name, 'Development');
		assert.equal((await requestMapping(titlesUrl, owner, { roleIds: [], expectedRevision: 0 })).status, 409);
		assert.equal((await fetch(titlesUrl, { method: 'POST', headers: { 'x-test-user': owner, 'Content-Type': 'text/plain' }, body: '{}' })).status, 415);
		assert.equal((await fetch(titlesUrl, { method: 'POST', headers: { 'x-test-user': owner, 'Content-Type': 'application/json', 'Sec-Fetch-Site': 'cross-site' }, body: '{}' })).status, 403);
		serverMembership.canManageServer = false;
		assert.equal((await fetch(titlesUrl, { headers: { 'x-test-user': owner } })).status, 403);
		serverMembership.canManageServer = true;
		assert.equal((await fetch(mappingRead, { headers: { 'x-test-user': owner } })).status, 404, 'Server authority does not reveal private team configuration');
		const readMapping = await fetch(mappingRead, { headers: { 'x-test-user': member } });
		assert.equal(readMapping.status, 200);
		assert.equal((await readMapping.json()).mapping.roles[0].name, 'Development');
		assert.equal((await requestMapping(`${mappingRead}/approve`, owner, { expectedRevision: 1 })).status, 404);
		assert.equal((await requestMapping(`${mappingRead}/approve`, member, { expectedRevision: 1 })).status, 200);
		assert.equal((await requestMapping(`${mappingRead}/approve`, member, { expectedRevision: 1 })).status, 409);
		assert.equal((await requestMapping(mappingUrl, owner, { roleIds: [guildId], expectedRevision: 2 })).status, 422);
		const suggestionsUrl = `${mappingRead}/suggestions`;
		const suggestionBody = { discordUserId: '223456789012345678', expectedRevision: 2, dismissed: true };
		assert.equal((await requestMapping(suggestionsUrl, null, suggestionBody)).status, 401);
		assert.equal((await requestMapping(suggestionsUrl, owner, suggestionBody)).status, 404);
		assert.equal((await requestMapping(suggestionsUrl, member, { ...suggestionBody, expectedRevision: 1 })).status, 409);
		assert.equal((await requestMapping(suggestionsUrl, member, { ...suggestionBody, discordUserId: 'invalid' })).status, 422);
		assert.equal((await fetch(suggestionsUrl, { method: 'POST', headers: { 'x-test-user': member, 'Content-Type': 'text/plain' }, body: JSON.stringify(suggestionBody) })).status, 415);
		assert.equal((await fetch(suggestionsUrl, { method: 'POST', headers: { 'x-test-user': member, 'Content-Type': 'application/json', 'Sec-Fetch-Site': 'cross-site' }, body: JSON.stringify(suggestionBody) })).status, 403);
		assert.equal((await requestMapping(suggestionsUrl, member, suggestionBody)).status, 200);
		assert.equal((await requestMapping(suggestionsUrl, member, { ...suggestionBody, dismissed: false })).status, 200);
		await db.query("INSERT INTO identities(id,user_id,provider,provider_uid) VALUES ($1,$2,'discord',$3)", [`role_candidate_${suffix}`, outsider, `8888${suffix}`]);
		serverMembership = { available: true, isMember: true, isBot: false, roleIds: ['123456789012345678'] };
		const memberApproval = `${mappingRead}/members`;
		assert.equal((await requestMapping(memberApproval, owner, { userId: outsider, expectedRevision: 2 })).status, 404);
		assert.equal((await requestMapping(memberApproval, member, { userId: outsider, expectedRevision: 2 })).status, 200);
		const badgesUrl = `${base}/teams/${mappedTeam.team.id}/members/${outsider}/titles`;
		assert.equal((await fetch(badgesUrl, { headers: { 'x-test-user': owner } })).status, 404);
		const badgeResponse = await fetch(badgesUrl, { headers: { 'x-test-user': member } });
		assert.equal(badgeResponse.status, 200);
		assert.deepEqual(await badgeResponse.json(), { titles: [{ roleId: '123456789012345678', name: 'Development' }] });
		const batchTitlesUrl = `${base}/teams/${mappedTeam.team.id}/member-titles?userId=${outsider}&userId=${member}`;
		const batchTitlesResponse = await fetch(batchTitlesUrl, { headers: { 'x-test-user': member } });
		assert.equal(batchTitlesResponse.status, 200);
		assert.equal((await batchTitlesResponse.json()).members.length, 2);
		assert.equal((await fetch(batchTitlesUrl, { headers: { 'x-test-user': owner } })).status, 404);
		assert.equal((await fetch(`${base}/teams/${mappedTeam.team.id}/member-titles`, { headers: { 'x-test-user': member } })).status, 422);
		assert.equal((await db.query('SELECT count(*)::int AS n FROM project_memberships WHERE user_id=$1', [outsider])).rows[0].n, 0);
		serverMembership = { available: true, isMember: false, isBot: false, roleIds: ['123456789012345678'] };
		assert.equal((await requestMapping(memberApproval, member, { userId: outsider, expectedRevision: 2 })).status, 403, 'A manager who left Discord cannot approve membership');
		serverMembership = { available: true, isMember: true, isBot: false, roleIds: [] };
		assert.equal((await requestMapping(memberApproval, member, { userId: outsider, expectedRevision: 2 })).status, 422);
		const removeMapping = (actor, expectedRevision) => fetch(mappingRead, { method: 'DELETE', headers: { 'Content-Type': 'application/json', 'x-test-user': actor }, body: JSON.stringify({ expectedRevision }) });
		assert.equal((await removeMapping(owner, 2)).status, 404);
		assert.equal((await removeMapping(member, 1)).status, 409);
		assert.equal((await removeMapping(member, 2)).status, 200);
		assert.equal((await (await fetch(mappingRead, { headers: { 'x-test-user': member } })).json()).mapping, null);
		assert.equal((await db.query("SELECT count(*)::int AS count FROM team_memberships WHERE team_id=$1 AND revoked_at IS NULL", [mappedTeam.team.id])).rows[0].count, 2, 'Unlinking preserves explicitly approved memberships');
		const removalEvent = (await db.query("SELECT payload FROM team_events WHERE team_id=$1 AND event_type='role_mapping_removed'", [mappedTeam.team.id])).rows[0];
		assert.equal(removalEvent.payload.roles[0].name_snapshot, 'Development');
		serverMembership = { available: true, isMember: true, isBot: false };
		const rolesEndpoint = `${base}/teams/discord-guilds/${guildId}/roles`;
		const roleHeaders = { 'x-test-user': owner };
		assert.equal((await fetch(rolesEndpoint)).status, 401);
		assert.equal((await fetch(rolesEndpoint, { headers: roleHeaders })).status, 403, 'Ordinary Discord membership cannot configure role linking');
		serverMembership = { available: true, isMember: true, isBot: false, canManageServer: true };
		const discovered = await fetch(rolesEndpoint, { headers: roleHeaders });
		assert.equal(discovered.status, 200);
		assert.equal(requestedManagement, true, 'Role configuration requires fresh permission definitions, not just a fresh member');
		assert.deepEqual((await discovered.json()).roles.map(role => role.name), ['Development']);
		roleLookup = { available: false };
		assert.equal((await fetch(rolesEndpoint, { headers: roleHeaders })).status, 503);
		roleLookup = { available: true, guildId: '998877665544332211', roles: [] };
		assert.equal((await fetch(rolesEndpoint, { headers: roleHeaders })).status, 503);
		serverMembership = { available: false };
		assert.equal((await fetch(rolesEndpoint, { headers: roleHeaders })).status, 503);
		serverMembership = { available: true, isMember: false, canManageServer: true };
		assert.equal((await fetch(rolesEndpoint, { headers: roleHeaders })).status, 403);
		serverMembership = { available: true, isMember: true, isBot: true, canManageServer: true };
		assert.equal((await fetch(rolesEndpoint, { headers: roleHeaders })).status, 403);
		serverMembership = { available: true, isMember: true, isBot: false };
		for (const [method, path] of [['GET', ''], ['POST', '/claim'], ['GET', `/${companyId}`], ['PATCH', `/${companyId}`], ['POST', `/${companyId}/archive`], ['POST', `/${companyId}/join-links`]]) {
			const response = await fetch(`${base}/companies${path}`, { method, headers: { 'x-test-user': owner } });
			assert.equal(response.status, 404);
			assert.equal((await response.json()).error, 'companies_disabled');
		}
		process.env.MEGU_COMPANIES_ENABLED = '0';
		await assert.rejects(companies.getCompany(companyId, owner), { code: 'companies_disabled' });
		assert.equal((await fetch(`${base}/companies/${companyId}`, { headers: { 'x-test-user': owner } })).status, 404);
		console.log('Legacy company storage safeguards and retired HTTP routes passed.');
	} finally {
		if (server) await new Promise(resolve => server.close(resolve));
		await db.query('DELETE FROM server_role_mappings WHERE team_id=ANY($1::text[])', [teamIds]);
		await db.query('DELETE FROM server_role_mappings WHERE created_by=ANY($1::text[])', [[owner, outsider, member]]);
		await db.query('DELETE FROM server_role_events WHERE actor_id=ANY($1::text[])', [[owner, outsider, member]]);
		await db.query('DELETE FROM server_role_team_creations WHERE actor_id=ANY($1::text[])', [[owner, outsider, member]]);
		await db.query('DELETE FROM projects WHERE team_id=ANY($1::text[])', [teamIds]);
		await db.query('DELETE FROM team_memberships WHERE team_id=ANY($1::text[])', [teamIds]);
		await db.query('DELETE FROM teams WHERE id=ANY($1::text[])', [teamIds]);
		if (companyId) {
			await db.query('DELETE FROM company_events WHERE company_id=$1', [companyId]);
			await db.query('DELETE FROM company_memberships WHERE company_id=$1', [companyId]);
			await db.query('DELETE FROM companies WHERE id=$1', [companyId]);
		}
		await db.query('DELETE FROM users WHERE id=ANY($1::text[])', [[owner, outsider, member]]);
		await db.close();
	}
}
main().catch(error => { console.error(error); process.exitCode = 1; });
