'use strict';
const assert = require('node:assert/strict');
const db = require('../core/db');
const { isDisposableTestDatabase } = require('./test-database');
(async () => {
	assert.ok(isDisposableTestDatabase(process.env.MEGU_TEST_DATABASE_URL)); process.env.MEGU_DATABASE_URL = process.env.MEGU_TEST_DATABASE_URL;
	process.env.MEGU_TEAM_ROLE_SYNC_ENABLED = '1'; await require('../core/schema').initCoreSchema();
	const client = await db.getPool().connect(), originalTransaction = db.transaction, originalQuery = db.query;
	let server;
	try {
		await client.query('BEGIN'); db.transaction = fn => fn(client); db.query = (...args) => client.query(...args);
		const automatic = require('../core/server-role-automatic'), sources = require('../core/team-membership-sources'), sync = require('../core/server-role-sync');
		const prefix = `consent_${Date.now()}`, mappingId = `${prefix}_mapping`, owner = `${prefix}_owner`, manager = `${prefix}_manager`, member = `${prefix}_member`, guildId = '866666666666666666', roleId = '877777777777777777';
		const identities = new Map([[owner,'811111111111111111'],[manager,'822222222222222222'],[member,'833333333333333333']]);
		for (const [user, uid] of identities) { await client.query('INSERT INTO users(id,display_name) VALUES ($1,$1)', [user]); await client.query("INSERT INTO identities(id,user_id,provider,provider_uid) VALUES ($1,$2,'discord',$3)", [`${user}_identity`, user, uid]); }
		await client.query('INSERT INTO teams(id,name,created_by,discord_guild_id) VALUES ($1,$1,$2,$3)', [prefix, owner, guildId]);
		await client.query("INSERT INTO team_memberships(team_id,user_id,role) VALUES ($1,$2,'owner')", [prefix, owner]); await sources.grantManualSource(client, prefix, owner, owner, 'fixture');
		await client.query("INSERT INTO server_role_mappings(id,guild_id,kind,team_id,mode,enabled,revision,created_by,owner_consent_by,owner_consent_at,server_consent_by,server_consent_at) VALUES ($1,$2,'team',$3,'approval',true,1,$4,$4,now(),$5,now())", [mappingId, guildId, prefix, owner, manager]);
		await client.query("INSERT INTO server_role_mapping_roles(mapping_id,role_id,name_snapshot) VALUES ($1,$2,'Delivery')", [mappingId, roleId]);
		const verify = async (userId, guild, { management }) => ({ available: true, userId, guildId: guild, discordUserId: identities.get(userId), isMember: true, isBot: false, canManageServer: management && userId === manager, roleIds: userId === member ? [roleId] : [] });
		const deps = { verify, getCapabilities: async () => ({ available: true }), listRoles: async () => ({ available: true, guildId, roles: [{ id: roleId, guildId, name: 'Delivery', managed: false }] }), listCandidates: async () => ({ available: true, guildId, members: [{ id: identities.get(member), displayName: 'Registered', isBot: false, roles: [roleId] }, { id: '844444444444444444', displayName: 'Not registered', isBot: false, roles: [roleId] }, { id: '855555555555555555', displayName: 'Bot', isBot: true, roles: [roleId] }], nextOffset: 30 }) };
		let key = 0; const requestKey = () => `automatic_request_${++key}_1234567890`;
		const request = revision => ({ expectedRevision: revision, requestKey: requestKey(), delegationVersion: 1, confirmedDelegation: true });
		const confirm = preview => ({ expectedRevision: preview.revision, action: preview.action, previewToken: preview.previewToken, requestKey: requestKey(), delegationVersion: 1, confirmedDelegation: true });
		const state = async () => (await client.query('SELECT * FROM server_role_mappings WHERE id=$1', [mappingId])).rows[0];
		const membership = async () => (await client.query('SELECT * FROM team_memberships WHERE team_id=$1 AND user_id=$2', [prefix, member])).rows[0];
		process.env.MEGU_TEAM_ROLE_SYNC_ENABLED = ''; await assert.rejects(automatic.requestAutomatic(guildId, prefix, manager, request(1), deps), { code: 'role_mapping_automatic_not_supported' }); process.env.MEGU_TEAM_ROLE_SYNC_ENABLED = '1';
		await assert.rejects(automatic.requestAutomatic(guildId, prefix, manager, request(1), { ...deps, getCapabilities: async () => ({ available: false }) }), { code: 'role_sync_capability_unavailable' });
		await assert.rejects(automatic.requestAutomatic(guildId, prefix, manager, { ...request(1), confirmedDelegation: false }, deps), { code: 'role_mapping_delegation_confirmation_required' });
		await assert.rejects(automatic.requestAutomatic(guildId, prefix, owner, request(1), deps), { code: 'team_forbidden' });
		await assert.rejects(automatic.requestAutomatic(guildId, prefix, manager, request(1), { ...deps, verify: async (...args) => ({ ...(await verify(...args)), discordUserId: '899999999999999999' }) }), { code: 'team_forbidden' });
		const firstRequest = request(1), requested = await automatic.requestAutomatic(guildId, prefix, manager, firstRequest, deps);
		assert.equal(requested.revision, 2); assert.equal((await state()).mode, 'approval'); assert.equal((await state()).enabled, true); assert.equal(await membership(), undefined);
		assert.deepEqual(await automatic.requestAutomatic(guildId, prefix, manager, Object.fromEntries(Object.entries(firstRequest).reverse()), deps), requested, 'Canonical replay survives object field ordering');
		await assert.rejects(automatic.requestAutomatic(guildId, prefix, manager, { ...firstRequest, expectedRevision: 2 }, deps), { code: 'idempotency_conflict' });
		await assert.rejects(automatic.previewTransition(prefix, manager, { expectedRevision: 2, action: 'enable' }, deps), { code: 'team_not_found' });
		let preview = await automatic.previewTransition(prefix, owner, { expectedRevision: 2, action: 'enable' }, deps);
		assert.equal(preview.memberPreview.partial, true); assert.equal(preview.memberPreview.candidates.length, 2); assert.equal(preview.memberPreview.candidates.filter(row => !row.userId).length, 1); assert.equal(preview.projectAccessRestored, false);
		await assert.rejects(automatic.confirmTransition(prefix, owner, { ...confirm(preview), confirmedDelegation: false }, deps), { code: 'role_mapping_delegation_confirmation_required' });
		await assert.rejects(automatic.confirmTransition(prefix, owner, { ...confirm(preview), previewToken: 'a'.repeat(64) }, deps), { code: 'revision_conflict' });
		await client.query('UPDATE teams SET revision=revision+1 WHERE id=$1', [prefix]); await assert.rejects(automatic.confirmTransition(prefix, owner, confirm(preview), deps), { code: 'revision_conflict' });
		preview = await automatic.previewTransition(prefix, owner, { expectedRevision: 2, action: 'enable' }, deps); await client.query("UPDATE server_role_mappings SET sync_preview_expires_at=now()-interval '1 second' WHERE id=$1", [mappingId]);
		await assert.rejects(automatic.confirmTransition(prefix, owner, confirm(preview), deps), { code: 'revision_conflict' });
		preview = await automatic.previewTransition(prefix, owner, { expectedRevision: 2, action: 'enable' }, deps);
		await assert.rejects(automatic.confirmTransition(prefix, owner, confirm(preview), { ...deps, verify: async (...args) => ({ ...(await verify(...args)), canManageServer: false }) }), { code: 'team_forbidden' });
		const commitInput = confirm(preview), committed = await automatic.confirmTransition(prefix, owner, commitInput, deps);
		assert.equal(committed.status, 'reconciliation_queued'); assert.equal((await state()).delegation_version, 1); assert.equal((await state()).mode, 'automatic'); assert.equal(await membership(), undefined);
		assert.deepEqual(await automatic.confirmTransition(prefix, owner, commitInput, deps), committed);
		assert.deepEqual(await automatic.confirmTransition(prefix, owner, commitInput, { getCapabilities: async () => ({ available: false }) }), committed, 'Committed enable receipt recovers without repeating unavailable Discord access');
		await sync.runOnce({ verify }); assert.equal((await membership()).role, 'member');
		const unavailableDeps = { verify: () => { throw new Error('Retirement does not require Discord'); } };
		preview = await automatic.previewTransition(prefix, owner, { expectedRevision: 3, action: 'disable' }, unavailableDeps); assert.equal(preview.impact.derivedSources, 1); assert.equal(preview.impact.finalSources, 1);
		await automatic.confirmTransition(prefix, owner, confirm(preview), unavailableDeps); assert.equal((await state()).enabled, false); assert.equal((await membership()).revoked_at, null, 'Retirement is honestly queued, not falsely reported complete');
		await sync.runOnce(); assert.ok((await membership()).revoked_at);
		const enableAgain = async () => { const proposed = await automatic.requestAutomatic(guildId, prefix, manager, request((await state()).revision), deps); const next = await automatic.previewTransition(prefix, owner, { expectedRevision: proposed.revision, action: 'enable' }, deps); return automatic.confirmTransition(prefix, owner, confirm(next), deps); };
		await enableAgain(); await sync.runOnce({ verify }); assert.equal((await membership()).revoked_at, null);
		preview = await automatic.previewTransition(prefix, owner, { expectedRevision: (await state()).revision, action: 'approval' }); await automatic.confirmTransition(prefix, owner, confirm(preview)); assert.equal((await state()).mode, 'approval'); assert.equal((await state()).enabled, false);
		await sync.runOnce(); assert.ok((await membership()).revoked_at); assert.equal((await client.query("SELECT count(*)::int AS n FROM team_membership_sources WHERE team_id=$1 AND user_id=$2 AND kind='manual'", [prefix, member])).rows[0].n, 0);
		await enableAgain(); await sync.runOnce({ verify }); preview = await automatic.previewTransition(prefix, owner, { expectedRevision: (await state()).revision, action: 'unlink' });
		const unlinkInput = confirm(preview), unlinked = await automatic.confirmTransition(prefix, owner, unlinkInput); assert.ok((await state()).retired_at);
		assert.deepEqual(await automatic.confirmTransition(prefix, owner, unlinkInput), unlinked); await sync.runOnce(); assert.ok((await membership()).revoked_at);
		assert.ok((await client.query('SELECT count(*)::int AS n FROM team_membership_sources WHERE mapping_id=$1', [mappingId])).rows[0].n >= 3);
		const express = require('express'), app = express(); app.use(express.json()); app.use((req,res,next)=>{req.session={meguUserId:req.get('x-test-user')};next();});
		app.use('/api/megu',require('../adapters/http/megu-api').router({verifyDiscordGuildMember:verify,listDiscordGuildRoles:deps.listRoles,listDiscordGuildCandidates:deps.listCandidates,getRoleSyncCapabilities:deps.getCapabilities}));
		server=await new Promise(resolve=>{const listening=app.listen(0,'127.0.0.1',()=>resolve(listening));}); const base=`http://127.0.0.1:${server.address().port}/api/megu`;
		const ownerUrl=`${base}/teams/${prefix}/role-mapping/sync`,managerUrl=`${base}/teams/discord-guilds/${guildId}/role-mappings/${prefix}`;
		const call=(url,user,body,headers={})=>fetch(url,{method:body?'POST':'GET',headers:{'Content-Type':'application/json',...(user?{'x-test-user':user}:{}),...headers},...(body?{body:JSON.stringify(body)}:{})});
		assert.equal((await call(ownerUrl)).status,401); assert.equal((await call(ownerUrl,manager)).status,404,'Manager cannot read private owner status');
		let response=await call(`${managerUrl}/sync`,manager); assert.equal(response.status,200); assert.match(response.headers.get('cache-control'),/no-store/); let status=await response.json(); assert.equal(status.retired,true); assert.ok(status.jobs.every(job=>!Object.hasOwn(job,'counts'))); assert.deepEqual(status.blockedRevocations,[]);
		assert.equal((await call(`${base}/teams/${prefix}/summary`,manager)).status,404);
		const replacement=await require('../core/server-role-mappings').proposeTeamMapping(guildId,prefix,manager,{expectedRevision:0,roleIds:[roleId]},deps);
		const httpRequest=request(replacement.revision);
		assert.equal((await call(`${managerUrl}/automatic`,manager,httpRequest,{'Sec-Fetch-Site':'cross-site'})).status,403);
		assert.equal((await call(`${managerUrl}/automatic`,manager,httpRequest,{'Content-Type':'text/plain'})).status,415);
		assert.equal((await call(`${managerUrl}/automatic`,null,httpRequest)).status,401);
		assert.equal((await call(`${managerUrl}/automatic`,manager,{...httpRequest,unexpected:true})).status,422);
		process.env.MEGU_TEAM_ROLE_SYNC_ENABLED=''; assert.equal((await call(`${managerUrl}/automatic`,manager,httpRequest)).status,409); process.env.MEGU_TEAM_ROLE_SYNC_ENABLED='1';
		response=await call(`${managerUrl}/automatic`,manager,httpRequest); assert.equal(response.status,200); const httpProposed=await response.json();
		assert.equal((await call(`${ownerUrl}/preview`,manager,{expectedRevision:httpProposed.revision,action:'enable'})).status,404);
		response=await call(`${ownerUrl}/preview`,owner,{expectedRevision:httpProposed.revision,action:'enable'}); assert.equal(response.status,200); assert.match(response.headers.get('cache-control'),/no-store/); const httpPreview=await response.json();
		assert.equal((await call(`${ownerUrl}/confirm`,owner,{...confirm(httpPreview),previewToken:'0'.repeat(64)})).status,409);
		const httpConfirm=confirm(httpPreview); response=await call(`${ownerUrl}/confirm`,owner,httpConfirm); assert.equal(response.status,200); assert.equal((await response.json()).status,'reconciliation_queued');
		assert.equal((await call(`${ownerUrl}/confirm`,owner,httpConfirm)).status,200);
		response=await call(ownerUrl,owner); assert.equal(response.status,200); status=await response.json(); assert.equal(status.supported,true); assert.equal(status.pendingDelegation,false); assert.ok(!JSON.stringify(status).includes('Delivery'));
		assert.equal(status.canConfirmTransitions,true);
		const reconcile={expectedRevision:status.revision,requestKey:'http_reconcile_receipt_123'};
		assert.equal((await call(`${ownerUrl}/reconcile`,manager,reconcile)).status,404);
		assert.equal((await call(`${ownerUrl}/reconcile`,owner,reconcile,{'Sec-Fetch-Site':'cross-site'})).status,403);
		assert.equal((await call(`${ownerUrl}/reconcile`,owner,{...reconcile,unexpected:true})).status,422);
		const jobBefore=(await client.query('SELECT generation FROM server_role_sync_jobs WHERE mapping_id=$1 AND user_id IS NULL',[status.mappingId])).rows[0].generation;
		response=await call(`${ownerUrl}/reconcile`,owner,reconcile); assert.equal(response.status,200); const reconciliation=await response.json(); assert.equal(reconciliation.status,'reconciliation_queued');
		response=await call(`${ownerUrl}/reconcile`,owner,reconcile); assert.deepEqual(await response.json(),reconciliation);
		assert.equal((await client.query('SELECT generation FROM server_role_sync_jobs WHERE mapping_id=$1 AND user_id IS NULL',[status.mappingId])).rows[0].generation,jobBefore+1,'Receipt replay cannot duplicate a queued sweep');
		assert.equal((await call(`${managerUrl}/sync/reconcile`,manager,{expectedRevision:status.revision,requestKey:'manager_reconcile_receipt_123'})).status,200);
		assert.equal((await call(`${ownerUrl}/reconcile`,owner,{expectedRevision:1,requestKey:'stale_reconcile_receipt_123'})).status,409);
		console.log('Automatic consent passed: default/capability gates, exact server authority, explicit versioned delegation, owner-only partial preview, stale/forged/expired protection, durable canonical replay, queued enable/disable/switch/unlink, no manual conversion and retained source history.');
	} finally { if(server) await new Promise(resolve=>server.close(resolve)); db.transaction = originalTransaction; db.query = originalQuery; await client.query('ROLLBACK'); client.release(); await db.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
