'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const React = require('react');
const { renderToStaticMarkup } = require('react-dom/server');
const babel = require('next/dist/compiled/babel/core');
const filename = path.join(__dirname, '../app/components/teams/ServerTitleSettings.js');
const first = babel.transformSync(fs.readFileSync(filename, 'utf8'), { filename, configFile: false, babelrc: false, presets: ['next/babel'] });
const { code } = babel.transformSync(first.code, { filename, configFile: false, babelrc: false, plugins: ['next/dist/compiled/babel/plugin-transform-modules-commonjs'] });
for (const lang of ['en', 'th']) {
	const t = require(`../app/copy/${lang}`);
	let stateIndex = 0;
	let draft;
	let resource = { data: { revision: 2, roles: [{ id: '123456789012345678', name: 'CEO' }], enabled: true }, loading: false };
	let discovery = { data: { roles: [{ id: '123456789012345678', name: 'CEO' }, { id: '123456789012345679', name: 'Developer' }] }, loading: false };
	const module = { exports: {} };
	vm.runInThisContext(`(function(require,module,exports){${code}\n})`, { filename })(id => {
		if (id === 'react') return { ...React, useEffect() {}, useRef: value => ({ current: value }), useState: initial => [stateIndex++ === 0 && draft !== undefined ? draft : typeof initial === 'function' ? initial() : initial, () => {}] };
		if(id.includes('useDraftGuard')) return {default:()=>()=>{},requestDraftNavigation:()=>true,__esModule:true};
		if (id === '../../copy') return { useCopy: () => ({ t }) };
		if (id.endsWith('.css')) return {};
		if (id === 'next/link') return { default: props => React.createElement('a', props), __esModule: true };
		if (id === 'next/navigation') return { useRouter: () => ({ push() {} }) };
		if (id.includes('AuthGate')) return { default: () => React.createElement('p', null, 'Sign in required'), __esModule: true };
		if (id.includes('ProjectAvatar')) return { default: () => React.createElement('img', { alt: '' }), __esModule: true };
		if (id.includes('discord-guild-icon')) return { guildIconUrl: () => null };
		if (id.includes('useWorkspaceResource')) return { default: url => url.endsWith('/title-roles') ? resource : discovery, __esModule: true };
		if (id.includes('CustomSelect')) return { default: props => React.createElement('div', { 'aria-label': props.ariaLabel, 'data-disabled': props.disabled }, props.options.map(option => React.createElement('span', { key: option.value }, option.label))), __esModule: true };
		return require(id.startsWith('@babel/runtime/') ? `next/dist/compiled/${id}` : id);
	}, module, module.exports);
	const render = () => { stateIndex = 0; return renderToStaticMarkup(React.createElement(module.exports.default, { guildId: '223456789012345678' })); };
	let html = render();
	for (const text of [t.serverTitles.title, t.serverTitles.noAccess, 'CEO', 'Developer', t.serverTitles.clearHint]) assert.ok(html.includes(text), `${lang}: missing ${text}`);
	assert.match(html, /class="btn btn-primary" disabled=""/, 'Unchanged selection cannot be saved');
	resource.data.guild = { id: '223456789012345678', name: 'Design Studio', icon: null };
	assert.ok(render().includes(t.serverTitles.titleFor('Design Studio')), 'Settings identify the actual server');
	draft = { revision: 2, roleIds: [] };
	html = render();
	assert.ok(html.includes(t.serverTitles.none));
	assert.ok(!/class="btn btn-primary" disabled/.test(html), 'Explicit empty selection can turn labels off');
	draft = { revision: 1, roleIds: [] };
	html = render(); assert.ok(html.includes(t.serverTitles.changed)); assert.match(html, /class="btn btn-primary" disabled=""/);
	draft = undefined; discovery = { data: null, error: { status: 503 }, loading: false };
	html = render(); assert.ok(html.includes(t.serverTitles.rolesUnavailable)); assert.ok(html.includes('CEO'), 'Saved labels remain removable during discovery failure');
	resource = { data: null, error: { status: 403 }, loading: false };
	html = render(); assert.ok(html.includes(t.serverTitles.forbidden)); assert.ok(!html.includes('<form'));
	resource = { data: null, error: { status: 401 }, loading: false };
	assert.ok(render().includes('Sign in required'));
}
console.log('Discord title settings UI passed: EN/TH selection, clearing, unchanged/stale guards, outage, permission and sign-in states');
