'use strict';
const assert = require('node:assert/strict');
const { Client } = require('pg');
const { randomBytes } = require('node:crypto');
const { isDisposableTestDatabase } = require('./test-database');
(async () => {
	const source = process.env.MEGU_TEST_DATABASE_URL || process.env.MEGU_DATABASE_URL;
	assert.ok(isDisposableTestDatabase(source));
	const database = `megu_role_race_${randomBytes(8).toString('hex')}_test`, url = new URL(source); url.pathname = '/postgres';
	const admin = new Client({ connectionString: url.toString(), ssl: false }); await admin.connect();
	let created = false, db, release;
	try {
		await admin.query(`CREATE DATABASE "${database}"`); created = true; url.pathname = `/${database}`;
		process.env.MEGU_DATABASE_URL = url.toString(); process.env.MEGU_TEAM_ROLE_SYNC_ENABLED = '1'; process.env.PG_POOL_MAX = '4';
		db = require('../core/db'); await require('../core/schema').initCoreSchema();
		const guildId = '866666666666666666', roleId = '877777777777777777';
		await db.query("INSERT INTO users(id,display_name) VALUES ('owner','Owner'),('manager','Manager'),('member','Member')");
		await db.query("INSERT INTO identities(id,user_id,provider,provider_uid) VALUES ('owner-id','owner','discord','811111111111111111'),('manager-id','manager','discord','822222222222222222'),('member-id','member','discord','833333333333333333')");
		await db.query('INSERT INTO teams(id,name,created_by,discord_guild_id) VALUES ($1,$1,$2,$3)', ['team', 'owner', guildId]);
		await db.query("INSERT INTO team_memberships(team_id,user_id,role) VALUES ('team','owner','owner')");
		await db.transaction(client => require('../core/team-membership-sources').grantManualSource(client, 'team', 'owner', 'owner', 'fixture'));
		await db.query("INSERT INTO server_role_mappings(id,guild_id,kind,team_id,mode,enabled,revision,delegation_version,created_by,owner_consent_by,owner_consent_at,server_consent_by,server_consent_at) VALUES ('mapping',$1,'team','team','automatic',true,1,1,'owner','owner',now(),'manager',now())", [guildId]);
		await db.query("INSERT INTO server_role_mapping_roles(mapping_id,role_id,name_snapshot) VALUES ('mapping',$1,'Delivery')", [roleId]);
		const sync = require('../core/server-role-sync'); await sync.scheduleMissingSweeps();
		await db.query("UPDATE server_role_sync_jobs SET next_attempt_at='infinity' WHERE user_id IS NULL");
		await Promise.all([sync.enqueue('mapping', 'member'), sync.enqueue('mapping', 'member')]);
		const job = (await db.query("SELECT * FROM server_role_sync_jobs WHERE user_id='member'")).rows;
		assert.equal(job.length, 1); assert.equal(job[0].generation, 2);
		const verify = async (userId, guild, { management }) => ({ available: true, userId, guildId: guild, discordUserId: userId === 'manager' ? '822222222222222222' : '833333333333333333', isMember: true, isBot: false, canManageServer: management && userId === 'manager', roleIds: [roleId] });
		const barrier = () => {
			let entered; const ready = new Promise(resolve => { entered = resolve; }); const wait = new Promise(resolve => { release = resolve; });
			return { ready, verify: async (...args) => { entered(); await wait; return verify(...args); } };
		};
		let hold = barrier(); const first = sync.runOnce({ verify: hold.verify }); await hold.ready;
		assert.equal((await sync.runOnce({ verify })).processed, 0, 'Separate worker cannot claim an unexpired lease'); release(); await first;
		assert.equal((await db.query("SELECT count(*)::int AS n FROM team_membership_sources WHERE mapping_id='mapping' AND revoked_at IS NULL")).rows[0].n, 1);
		await sync.enqueue('mapping', 'member'); hold = barrier(); const old = sync.runOnce({ verify: hold.verify }); await hold.ready;
		await sync.enqueue('mapping', 'member');
		assert.equal((await sync.runOnce({ verify: async (...args) => ({ ...(await verify(...args)), roleIds: [] }) })).done, true); release();
		assert.equal((await old).stale, true, 'A late old positive result must not overwrite a newer confirmed removal');
		assert.equal((await db.query("SELECT count(*)::int AS n FROM team_membership_sources WHERE mapping_id='mapping' AND revoked_at IS NULL")).rows[0].n, 0);
		await sync.enqueue('mapping', 'member'); hold = barrier(); const expired = sync.runOnce({ verify: hold.verify }); await hold.ready;
		await db.query("UPDATE server_role_sync_jobs SET lease_until=clock_timestamp()-interval '1 second' WHERE user_id='member'");
		assert.equal((await sync.runOnce({ verify })).done, true); release(); assert.equal((await expired).stale, true);
		assert.equal((await db.query("SELECT count(*)::int AS n FROM team_membership_sources WHERE mapping_id='mapping' AND revoked_at IS NULL")).rows[0].n, 1);
		const automatic = require('../core/server-role-automatic');
		await db.query("UPDATE server_role_mappings SET mode='approval',enabled=false,revision=2,delegation_version=NULL WHERE id='mapping'");
		const nativeVerify = async (...args) => ({ ...(await verify(...args)), discordUserId: { owner: '811111111111111111', manager: '822222222222222222', member: '833333333333333333' }[args[0]] });
		const deps = { verify: nativeVerify, getCapabilities: async () => ({ available: true }), listRoles: async () => ({ available: true, guildId, roles: [{ id: roleId, guildId, name: 'Delivery', managed: false }] }), listCandidates: async () => ({ available: true, guildId, members: [] }) };
		await automatic.requestAutomatic(guildId, 'team', 'manager', { expectedRevision: 2, requestKey: 'automatic_manager_request_123456', delegationVersion: 1, confirmedDelegation: true }, deps);
		const preview = await automatic.previewTransition('team', 'owner', { expectedRevision: 3, action: 'enable' }, deps);
		const generation = (await db.query('SELECT generation FROM server_role_sync_jobs WHERE user_id IS NULL')).rows[0].generation;
		const confirmation = { expectedRevision: 3, action: 'enable', previewToken: preview.previewToken, requestKey: 'automatic_owner_confirm_123456', delegationVersion: 1, confirmedDelegation: true };
		const confirmed = await Promise.all([automatic.confirmTransition('team', 'owner', confirmation, deps), automatic.confirmTransition('team', 'owner', confirmation, deps)]);
		assert.deepEqual(confirmed[0], confirmed[1]);
		assert.equal((await db.query('SELECT generation FROM server_role_sync_jobs WHERE user_id IS NULL')).rows[0].generation, generation + 1, 'Concurrent replay enqueues one new sweep');
		assert.equal((await db.query("SELECT count(*)::int AS n FROM team_events WHERE event_type='role_sync_transition'")).rows[0].n, 1);
		const users = require('../core/users');
		await users.linkIdentity('member', { provider: 'google', providerUid: 'member-google', email: 'fixture@example.invalid', emailVerified: true });
		const unlink = await Promise.all([users.unlinkIdentity('member', 'discord'), users.unlinkIdentity('member', 'google')]);
		assert.equal(unlink.filter(result => result.unlinked).length, 1); assert.equal(unlink.filter(result => result.reason === 'last-identity').length, 1);
		assert.equal((await db.query("SELECT count(*)::int AS n FROM identities WHERE user_id='member'")).rows[0].n, 1, 'Concurrent different-provider unlinks cannot remove the last sign-in identity');
		console.log('Real role sync concurrency passed: simultaneous event coalescing, single lease claim, superseded late-positive rejection, expiry recovery and one active source cycle.');
	} finally {
		release?.(); if (db) await db.close();
		if (created) await admin.query(`DROP DATABASE "${database}"`);
		await admin.end();
	}
})().catch(error => { console.error(error); process.exitCode = 1; });
