'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const React = require('react');
const { renderToStaticMarkup } = require('react-dom/server');
const babel = require('next/dist/compiled/babel/core');
const filename = path.join(__dirname, '../app/components/teams/GoalActionForm.js');
const first = babel.transformSync(fs.readFileSync(filename, 'utf8'), { filename, configFile: false, babelrc: false, presets: ['next/babel'] });
const { code } = babel.transformSync(first.code, { filename, configFile: false, babelrc: false, plugins: ['next/dist/compiled/babel/plugin-transform-modules-commonjs'] });
for (const lang of ['en', 'th']) {
	const t = require(`../app/copy/${lang}`); const module = { exports: {} };
	let index = 0; let draftRevision = null;
	vm.runInThisContext(`(function(require,module,exports){${code}\n})`, { filename })(id => {
		if (id === 'react') return { ...React, useEffect() {}, useState: initial => [index++ === 2 ? draftRevision : initial, () => {}] };
		if(id.includes('useDraftGuard')) return {default:()=>()=>{},requestDraftNavigation:()=>true,__esModule:true};
		if (id === '../../copy') return { useCopy: () => ({ t }) };
		if (id.endsWith('.css')) return {};
		if (id.includes('CustomSelect')) return { default: props => React.createElement('div', { 'aria-label': props.ariaLabel }, props.options.map(option => React.createElement('span', { key: option.value }, option.label))), __esModule: true };
		return require(id.startsWith('@babel/runtime/') ? `next/dist/compiled/${id}` : id);
	}, module, module.exports);
	const goal = { revision: 4, measurement: { kind: 'numeric', unit: 'items' } };
	const render = capabilities => { index = 0; return renderToStaticMarkup(React.createElement(module.exports.default, { goal, capabilities, busy: false, onTransition: async () => false })); };
	assert.equal(render({}), '');
	assert.ok(render({ canAddEvidence: true }).includes(t.teamGoals.note));
	assert.ok(render({ canSubmit: true }).includes(t.teamGoals.selfReview));
	assert.ok(render({ canReview: true }).includes(t.teamGoals.publishConfirm));
	assert.ok(render({ canReturn: true }).includes(t.teamGoals.reason));
	assert.ok(render({ canRespond: true }).includes(t.teamGoals.acknowledge));
	assert.ok(render({ canCancel: true }).includes(t.teamGoals.cancelConfirm));
	assert.ok(render({ canAddEvidence: true }).includes(t.teamGoals.required));
	assert.ok(render({ canAddEvidence: true }).includes(t.teamGoals.optional));
	assert.ok(render({ canAddEvidence: true }).includes('noValidate=""'));
	assert.match(render({ canCancel: true }), /btn-danger/);
	goal.measurement.kind = 'milestone';
	assert.ok(!render({ canAddEvidence: true }).includes('type="number"'));
	assert.ok(!render({ canReview: true }).includes(t.teamGoals.outcome.exceeded));
	draftRevision = 3; const stale = render({ canSubmit: true });
	assert.ok(stale.includes(t.teamGoals.conflict)); assert.match(stale, /type="submit"[^>]*disabled=""/);
	const payload = module.exports.goalActionPayload;
	assert.deepEqual(payload('evidence', { note: 'Evidence', value: '', links: 'https://example.com/a\n\nhttps://example.com/b' }, 'numeric'), { note: 'Evidence', value: null, links: ['https://example.com/a', 'https://example.com/b'] });
	assert.deepEqual(payload('evidence', { note: 'Evidence', value: '', links: '', referenceLink: '/p/abcde?topic=top_123' }, 'numeric').reference, { projectCode: 'ABCDE', topicId: 'top_123' });
	for (const referenceLink of ['https://outside.example/p/ABCDE', '/p/ABCDE?topic=', '/p/ABCDE?topic=one&topic=two', '/teams/team', '/p/ABCDE?topic=bad%2Fid']) assert.throws(() => payload('evidence', { note: 'Evidence', value: '', links: '', referenceLink }, 'numeric'), error => error.field === 'referenceLink');
	assert.ok(render({ canAddEvidence: true }).includes(t.teamGoals.referenceHint));
	assert.throws(() => payload('evidence', { note: '  ', value: '', links: '' }, 'numeric'), error => error.field === 'note' && error.message === 'noteRequired');
	assert.throws(() => payload('evidence', { note: 'Evidence', value: '', links: 'http://example.com' }, 'numeric'), error => error.field === 'links' && error.message === 'linkHttps');
	assert.throws(() => payload('evidence', { note: 'Evidence', value: '', links: 'not a url' }, 'numeric'), error => error.field === 'links' && error.message === 'linkInvalid');
	assert.throws(() => payload('evidence', { note: 'Evidence', value: '', links: 'https://name:password@example.com' }, 'numeric'), error => error.field === 'links' && error.message === 'linkCredentials');
	assert.throws(() => payload('evidence', { note: 'Evidence', value: '', links: Array(11).fill('https://example.com').join('\n') }, 'numeric'), error => error.field === 'links' && error.message === 'linksTooMany');
	assert.throws(() => payload('evidence', { note: 'Evidence', value: 'Infinity', links: '' }, 'numeric'), error => error.field === 'value' && error.message === 'valueInvalid');
	const originalWindow = global.window;
	global.window = { location: { origin: 'http://localhost:3000' } };
	const reproduced = { note: 'hello test', value: '', links: 'http://localhost:3000/teams/tem_e3df5acb25523f28/goals/gol_a0d46824d28cfc07', referenceLink: 'http://localhost:3000/p/2K56DXB' };
	assert.throws(() => payload('evidence', reproduced, 'milestone'), error => error.field === 'links' && error.message === 'linkHttps');
	assert.deepEqual(payload('evidence', { ...reproduced, links: '' }, 'milestone').reference, { projectCode: '2K56DXB', topicId: null });
	if (originalWindow === undefined) delete global.window; else global.window = originalWindow;
	assert.throws(() => payload('review', { confirmed: false }, 'numeric'));
	assert.throws(() => payload('cancel', { reason: 'Stop', confirmed: true, cancelConfirmed: false }));
	assert.throws(() => payload('cancel', { reason: ' ', cancelConfirmed: true }));
	assert.deepEqual(payload('cancel', { reason: 'Scope changed', cancelConfirmed: true }), { reason: 'Scope changed' });
	assert.deepEqual(payload('respond', { response: '', acknowledged: true }), { response: null, acknowledged: true });
	assert.throws(() => payload('respond', { response: ' ', acknowledged: false }));
}
console.log('Goal action UI passed: role-based forms, stale draft gate, publication confirmation, safe evidence payloads');
