'use strict';
const assert = require('node:assert/strict');
const { validateMeasurement, achievement, validateEvidence } = require('../core/team-goal-measurement');
const numeric = { kind: 'numeric', direction: 'increase', unit: 'items', baseline: 10, target: 30, current: 20 };
assert.equal(achievement(numeric), 50);
assert.equal(achievement({ ...numeric, current: null }), null);
assert.equal(achievement({ ...numeric, current: 40 }), 100);
assert.equal(validateMeasurement({ ...numeric, current: 40 }).current, 40, 'Keep actual over-target value');
assert.equal(achievement({ ...numeric, current: 0 }), 0);
assert.equal(achievement({ ...numeric, direction: 'decrease', baseline: 30, target: 10 }), 50);
assert.equal(achievement({ ...numeric, baseline: -Number.MAX_VALUE, target: Number.MAX_VALUE, current: 0 }), 50);
assert.equal(achievement({ kind: 'milestone', criteria: 'Customer accepts delivery' }), null);
for (const current of [NaN, Infinity, -Infinity, '20', true]) assert.throws(() => achievement({ ...numeric, current }), /goal_value_invalid/);
for (const target of [10, 5]) assert.throws(() => achievement({ ...numeric, target }), /goal_target_invalid/);
assert.throws(() => achievement({ ...numeric, direction: 'decrease' }), /goal_target_invalid/);
assert.throws(() => achievement({ kind: 'milestone', criteria: '' }), /goal_criteria_required/);
assert.throws(() => achievement({ kind: 'milestone', criteria: 'Accepted', current: 100 }), /goal_measurement_invalid/);
assert.deepEqual(validateEvidence({ note: ' Report ', value: 0, links: ['https://example.com/evidence'] }, 'numeric'), { note: 'Report', value: 0, links: ['https://example.com/evidence'] });
assert.throws(() => validateEvidence({ note: 'Report', value: 1 }, 'milestone'), /goal_value_invalid/);
for (const link of ['http://example.com', 'javascript:alert(1)', 'https://user:pass@example.com', 'not a URL']) assert.throws(() => validateEvidence({ note: 'Report', links: [link] }, 'numeric'), /goal_evidence_links_invalid/);
assert.throws(() => validateEvidence({ note: 'x'.repeat(4001) }, 'numeric'), /goal_evidence_note_required/);
assert.throws(() => validateEvidence({ note: 'Report', links: Array(11).fill('https://example.com') }, 'numeric'), /goal_evidence_links_invalid/);
console.log('Goal measurements passed: honest numeric/milestone results, finite values, direction and bounded HTTPS evidence');
