'use strict';
const assert = require('node:assert/strict');
let teamRole = 'member';
let revoked = false;
let needsReviewer = false;
let privateReads = 0;
const dbPath = require.resolve('../core/db');
const teamsPath = require.resolve('../core/teams');
const query = async sql => {
	if (sql.startsWith('SELECT team_id')) return { rows: [{ team_id: 'team' }] };
	if (sql.includes('FOR SHARE')) return { rows: [{ id: 'goal', subject_id: 'subject', reviewer_id: 'reviewer', current_version: 1, revision: 0, lifecycle: 'active', needs_reviewer: needsReviewer }] };
	privateReads++;
	if (sql.includes('FROM team_goal_updates') || sql.includes('FROM team_goal_responses')) return { rows: [] };
	if (sql.includes('FROM team_goal_reviews')) return { rows: [{ id: 'review', outcome: 'met', explanation: 'Private explanation', next_step: 'Private next step' }] };
	return { rows: [{ title: 'Private title', success_description: 'Private success', measurement: { kind: 'milestone', criteria: 'Private criteria' } }] };
};
require.cache[dbPath] = { id: dbPath, filename: dbPath, loaded: true, exports: { transaction: fn => fn({ query }) } };
require.cache[teamsPath] = { id: teamsPath, filename: teamsPath, loaded: true, exports: { accessById: async (_client, team, _actor, options) => {
	assert.equal(team, 'team'); assert.equal(options.lock, true); assert.equal(options.allowArchived, false);
	if (revoked) throw Object.assign(new Error('team_not_found'), { code: 'team_not_found' });
	return { role: teamRole };
} } };
const { getGoal } = require('../core/team-goals');
(async () => {
	delete process.env.MEGU_TEAM_GOALS_ENABLED;
	await assert.rejects(getGoal('goal', 'subject'), { code: 'team_goals_disabled' });
	process.env.MEGU_TEAM_GOALS_ENABLED = '1';
	assert.equal((await getGoal('goal', 'subject')).goal.title, 'Private title');
	teamRole = 'admin';
	assert.equal((await getGoal('goal', 'reviewer')).review.explanation, 'Private explanation');
	privateReads = 0;
	const metadata = await getGoal('goal', 'other-manager');
	assert.equal(metadata.access, 'administration');
	assert.equal(privateReads, 0, 'Do not even query private content for other managers');
	assert.equal(JSON.stringify(metadata).includes('Private'), false);
	assert.equal(metadata.goal.title, undefined);
	needsReviewer = true;
	const proposal = await getGoal('goal', 'reviewer');
	assert.equal(proposal.access, 'proposal');
	assert.equal(proposal.updates, undefined);
	assert.equal(proposal.review, undefined);
	privateReads = 0;
	teamRole = 'member';
	await assert.rejects(getGoal('goal', 'other-member'), { code: 'goal_not_found' });
	await assert.rejects(getGoal('goal', 'reviewer'), { code: 'goal_not_found' });
	revoked = true;
	await assert.rejects(getGoal('goal', 'subject'), { code: 'goal_not_found' });
	assert.equal(privateReads, 0);
	console.log('Goal access passed: feature gate, subject/reviewer content, manager metadata only, revoked and ordinary-member denial');
})().catch(error => { console.error(error); process.exitCode = 1; });
