'use strict';
const assert = require('node:assert/strict');
const { Client } = require('pg');
const { isDisposableTestDatabase } = require('./test-database');
const { installServerRoleSchema } = require('../core/server-role-schema');
const { installTeamMembershipSourceSchema: install, grantManualSource: grant, revokeMembershipSources: revoke, mergeMembershipSources: merge } = require('../core/team-membership-sources');
const { suppressMembership, isMembershipSuppressed, restoreSuppressedMembership } = require('../core/team-membership-sources');
const { requireManualMembership } = require('../core/team-membership-sources');

(async () => {
	const url = process.env.MEGU_DATABASE_URL;
	assert.ok(isDisposableTestDatabase(url), 'Disposable local database required');
	const client = new Client({ connectionString: url }); await client.connect();
	try {
		await client.query('BEGIN');
		await client.query('CREATE SCHEMA membership_source_test');
		await client.query('SET LOCAL search_path TO membership_source_test');
		await client.query(`CREATE TABLE users(id text PRIMARY KEY);
		 CREATE TABLE teams(id text PRIMARY KEY,discord_guild_id text);
		 CREATE TABLE team_memberships(team_id text,user_id text,joined_at timestamptz DEFAULT now(),revoked_at timestamptz,PRIMARY KEY(team_id,user_id));
		 INSERT INTO users VALUES ('owner'),('member'),('removed'),('derived'),('merged');
		 INSERT INTO teams VALUES ('team','123456789012345678'),('other','998877665544332211');
		 INSERT INTO team_memberships(team_id,user_id) VALUES ('team','owner'),('team','member');
		 INSERT INTO team_memberships(team_id,user_id,revoked_at) VALUES ('team','removed',now());`);
		await installServerRoleSchema(client); await install(client);
		assert.equal((await client.query('SELECT count(*)::int n FROM team_membership_sources')).rows[0].n, 2, 'Only active pre-existing memberships backfill');
		assert.ok((await client.query('SELECT * FROM team_membership_sources')).rows.every(row => row.kind === 'manual' && row.origin === 'legacy_backfill' && row.granted_by === null));
		assert.equal(await isMembershipSuppressed(client, 'team', 'removed'), true, 'Historical removals are conservatively suppressed');
		await assert.rejects(restoreSuppressedMembership(client, 'team', 'removed', 'owner', false), { code: 'team_member_restore_confirmation_required' });
		await assert.rejects(restoreSuppressedMembership(client, 'team', 'removed', 'owner', 'true'), { code: 'team_member_restore_confirmation_required' });
		assert.equal((await restoreSuppressedMembership(client, 'team', 'removed', 'owner', true)).length, 1);
		await install(client);
		assert.equal(await isMembershipSuppressed(client, 'team', 'removed'), false, 'Startup must not undo explicit restoration');
		await client.query("INSERT INTO server_role_mappings(id,guild_id,kind,team_id,created_by) VALUES ('mapping','123456789012345678','team','team','owner')");
		await client.query("INSERT INTO team_memberships(team_id,user_id) VALUES ('team','derived'),('team','merged')");
		await client.query(`INSERT INTO team_membership_sources(id,team_id,user_id,kind,source_key,mapping_id,cycle,origin)
		 VALUES ('derived-source','team','derived','discord_role','mapping','mapping',1,'role_sync'),('merged-source','team','merged','discord_role','mapping','mapping',1,'role_sync')`);
		await install(client);
		assert.equal((await client.query("SELECT count(*)::int n FROM team_membership_sources WHERE user_id IN ('derived','merged') AND kind='manual'")).rows[0].n, 0, 'Repeated schema initialization never converts derived membership to manual');
		await requireManualMembership(client, 'team', 'owner');
		await assert.rejects(requireManualMembership(client, 'team', 'derived'), { code: 'team_manual_membership_required' });
		await assert.rejects(requireManualMembership(client, 'other', 'owner'), { code: 'team_manual_membership_required' });
		const reject = async (sql, code) => { await client.query('SAVEPOINT invalid'); await assert.rejects(client.query(sql), { code }); await client.query('ROLLBACK TO SAVEPOINT invalid'); };
		await reject("UPDATE team_membership_sources SET team_id='other' WHERE id='derived-source'", '23503');
		await reject("UPDATE team_membership_sources SET mapping_id=NULL WHERE id='derived-source'", '23514');
		await reject("INSERT INTO team_membership_sources SELECT 'duplicate',team_id,user_id,kind,source_key,mapping_id,cycle,granted_by,origin,metadata,granted_at,revoked_at,revocation_reason FROM team_membership_sources WHERE id='derived-source'", '23505');
		await grant(client, 'team', 'owner', 'owner', 'repeat_approval');
		assert.equal((await client.query("SELECT count(*)::int n FROM team_membership_sources WHERE user_id='owner'")).rows[0].n, 1, 'Repeated manual grant is idempotent');
		await revoke(client, 'team', 'member', 'member_removed');
		await client.query("UPDATE team_memberships SET revoked_at=now() WHERE user_id='member'");
		await assert.rejects(grant(client, 'team', 'member', 'owner', 'join_approved'), { code: 'team_member_not_found' });
		await client.query("UPDATE team_memberships SET revoked_at=NULL WHERE user_id='member'");
		await grant(client, 'team', 'member', 'owner', 'role_approved', { mappingId: 'mapping' });
		const history = (await client.query("SELECT kind,cycle,origin,revoked_at FROM team_membership_sources WHERE user_id='member' ORDER BY cycle")).rows;
		assert.equal(history.length, 2); assert.ok(history[0].revoked_at); assert.equal(history[1].cycle, 2); assert.equal(history[1].kind, 'manual');
		await merge(client, 'derived', 'merged');
		const merged = (await client.query("SELECT kind,revocation_reason FROM team_membership_sources WHERE user_id='derived'")).rows;
		assert.equal(merged.length, 2); assert.ok(merged.every(row => row.kind === 'discord_role'));
		assert.equal(merged.filter(row => row.revocation_reason === null).length, 1, 'Merge keeps one active derived source and both histories');
		await grant(client, 'team', 'derived', 'owner', 'explicit_retention');
		await requireManualMembership(client, 'team', 'derived');
		assert.equal((await client.query("SELECT count(*)::int n FROM team_membership_sources WHERE user_id='derived' AND revoked_at IS NULL")).rows[0].n, 2, 'Manual and derived eligibility coexist');
		await revoke(client, 'team', 'derived', 'member_removed');
		assert.equal((await client.query("SELECT count(*)::int n FROM team_membership_sources WHERE user_id='derived' AND revoked_at IS NULL")).rows[0].n, 0);
		await suppressMembership(client, 'team', 'derived', 'owner', 'member_removed');
		await assert.rejects(requireManualMembership(client, 'team', 'derived'), { code: 'team_manual_membership_required' });
		await suppressMembership(client, 'team', 'derived', 'owner', 'member_removed');
		assert.equal((await client.query("SELECT count(*)::int n FROM team_membership_suppressions WHERE user_id='derived'")).rows[0].n, 1, 'Repeated suppression preserves the original decision');
		await assert.rejects(grant(client, 'team', 'derived', 'owner', 'join_approved'), { code: 'team_member_restore_confirmation_required' });
		await client.query('SAVEPOINT failed_restoration');
		await restoreSuppressedMembership(client, 'team', 'derived', 'owner', true);
		await assert.rejects(client.query("INSERT INTO users VALUES ('owner')"), { code: '23505' });
		await client.query('ROLLBACK TO SAVEPOINT failed_restoration');
		assert.equal(await isMembershipSuppressed(client, 'team', 'derived'), true, 'A later failure rolls back the clearance too');
		assert.equal(await isMembershipSuppressed(client, 'other', 'derived'), false, 'Suppression stays team-scoped');
		await restoreSuppressedMembership(client, 'team', 'derived', 'owner', true);
		await grant(client, 'team', 'derived', 'owner', 'join_approved');
		await suppressMembership(client, 'team', 'derived', 'owner', 'member_removed');
		const suppressionHistory = (await client.query("SELECT created_by,cleared_by,cleared_at FROM team_membership_suppressions WHERE user_id='derived'")).rows;
		assert.equal(suppressionHistory.length, 2, 'A new removal starts a distinct history record');
		assert.equal(suppressionHistory.filter(row => row.cleared_at && row.cleared_by === 'owner').length, 1);
		assert.equal(suppressionHistory.filter(row => !row.cleared_at && row.created_by === 'owner').length, 1);
		console.log('Membership sources passed: one-time conservative backfill, guild binding, manual cycles, mixed provenance, merge history and revocation');
	} finally { await client.query('ROLLBACK'); await client.end(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
