#!/usr/bin/env bash
#
# Bring a fresh cloud workspace to the point where `npm test` passes.
#
# Three things are missing from a bare clone and each one stops the suite dead:
#
#   1. node_modules
#   2. a local PostgreSQL. Seventeen of the twenty-two suites talk to one, and
#      `tests/test-database.js` refuses any host that is not localhost — on
#      purpose, because these tests create and drop databases.
#   3. a `.env`. It is gitignored, so the clone has none, and core throws
#      without `MEGU_DATABASE_URL`.
#
# Everything this writes is local and disposable. No real credential belongs in
# a cloud workspace: the Discord bot token, the OAuth client secrets and the
# production `DATABASE_URL` all stay out, which means the bot and sign-in will
# not run here. Tests, the participant-side UI and every page that does not
# need an account do.

set -euo pipefail

say() { printf '\n\033[1m▸ %s\033[0m\n' "$1"; }

cd "$(dirname "$0")/.."

# ── 1. dependencies ─────────────────────────────────────────────────────────
say 'Installing dependencies'
if [ -f package-lock.json ]; then
	npm ci --no-audit --no-fund || npm install --no-audit --no-fund
else
	npm install --no-audit --no-fund
fi

# ── 2. PostgreSQL ───────────────────────────────────────────────────────────
#
# A system server rather than Docker: a sandbox may not have a working Docker
# daemon, and when it does, starting one costs more than this needs. The port
# is the stock 5432, not the 55432 that docker-compose.yml maps — nothing reads
# that number except the compose file and the URL written below.

PGPORT=5432
PGUSER_APP=megu
PGPASS_APP=megu_dev
PGDB=megu_dev

start_postgres() {
	if pg_isready -q -h localhost -p "$PGPORT" 2>/dev/null; then
		return 0
	fi

	if ! command -v pg_ctlcluster >/dev/null 2>&1 && ! command -v postgres >/dev/null 2>&1; then
		say 'Installing PostgreSQL'
		sudo apt-get update -qq
		sudo DEBIAN_FRONTEND=noninteractive apt-get install -y -qq postgresql postgresql-client
	fi

	say 'Starting PostgreSQL'
	sudo service postgresql start 2>/dev/null \
		|| sudo pg_ctlcluster "$(ls /etc/postgresql 2>/dev/null | sort -n | tail -1)" main start 2>/dev/null \
		|| true

	# The service command returns before the socket is actually accepting.
	for _ in $(seq 1 30); do
		pg_isready -q -h localhost -p "$PGPORT" 2>/dev/null && return 0
		sleep 1
	done
	return 1
}

if ! start_postgres; then
	echo 'Could not start PostgreSQL. `npm test` will fail until one is reachable on localhost:5432.' >&2
	exit 1
fi

say 'Creating the Megu role and database'
# Idempotent: a rerun of this script must not fail on an existing role.
sudo -u postgres psql -v ON_ERROR_STOP=1 -q <<SQL || true
DO \$\$ BEGIN
	IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '${PGUSER_APP}') THEN
		CREATE ROLE ${PGUSER_APP} LOGIN PASSWORD '${PGPASS_APP}' CREATEDB;
	END IF;
END \$\$;
SQL
sudo -u postgres psql -tAc "SELECT 1 FROM pg_database WHERE datname = '${PGDB}'" \
	| grep -q 1 || sudo -u postgres createdb -O "${PGUSER_APP}" "${PGDB}"

# CREATEDB is not optional: `npm test` derives a throwaway `megu_dev_test`
# database and creates it as this role on every run.

# ── 3. .env ─────────────────────────────────────────────────────────────────
#
# Written here rather than pasted into the environment-variables box, which is
# visible to anyone with access to the environment. None of these are real
# secrets — they are generated per workspace and protect nothing outside it —
# but the habit of keeping key material out of that box is worth having.

if [ -n "${MEGU_DATABASE_URL:-}" ]; then
	say 'MEGU_DATABASE_URL is already in the environment — not writing .env'
	printf '  using %s\n' "$(node -e "const u=new URL(process.env.MEGU_DATABASE_URL);u.password='***';console.log(u.toString())")"
elif [ -f .env ]; then
	say 'Keeping the existing .env'
else
	say 'Writing .env'
	cat > .env <<ENV
# Generated by scripts/cloud-setup.sh for this workspace. Local and disposable.
#
# DATABASE_URL is deliberately absent. The bot's own tables read it directly,
# and pointing a scratch workspace at the live database is the one mistake here
# that cannot be undone.
MEGU_DATABASE_URL=postgresql://${PGUSER_APP}:${PGPASS_APP}@localhost:${PGPORT}/${PGDB}

# Device tokens and sessions. Random per workspace: without them the app still
# runs but logs a warning and drops both on every restart.
MEGU_TOKEN_SECRET=$(node -e "console.log(require('crypto').randomBytes(32).toString('hex'))")
SESSION_SECRET=$(node -e "console.log(require('crypto').randomBytes(32).toString('hex'))")

EXPRESS_PORT=3001
NEXT_PORT=3100
FRONTEND_URL=http://localhost:3100
EXPRESS_API_URL=http://localhost:3001
ENV
fi

# ── 4. the OCR engine (optional) ────────────────────────────────────────────
#
# Copies tesseract out of node_modules and downloads two language files. Only
# the slip reader uses it, and it already reports itself unavailable when the
# files are missing, so a sandbox with no egress is not a broken workspace.

say 'Vendoring the OCR engine (optional)'
npm run ocr:setup || echo 'OCR assets unavailable — slip reading will report itself off. Everything else is fine.'

# ── 5. prove it ─────────────────────────────────────────────────────────────
say 'Checking the database is reachable'
node -e "
require('dotenv').config();
const { Client } = require('pg');
const url = process.env.MEGU_DATABASE_URL || 'postgresql://${PGUSER_APP}:${PGPASS_APP}@localhost:${PGPORT}/${PGDB}';
const host = new URL(url).hostname;
if (!['localhost', '127.0.0.1', 'host.docker.internal', 'megu-db'].includes(host)) {
	// The test harness enforces this too, but by then the app may already have
	// written to whatever this points at. A scratch workspace aimed at a live
	// database is the one mistake here that cannot be undone.
	console.error('  MEGU_DATABASE_URL points at ' + host + ', which is not local. Refusing.');
	process.exit(1);
}
const c = new Client({ connectionString: url });
c.connect().then(() => c.query('select 1'))
	.then(() => { console.log('  postgres ok'); return c.end(); })
	.catch(e => { console.error('  postgres FAILED:', e.message); process.exit(1); });
"

if [ -n "${DATABASE_URL:-}" ]; then
	printf '\n\033[1;33m  warning\033[0m DATABASE_URL is set. The bot half reads it directly, so this\n          workspace will write to whatever it names. Unset it unless you\n          meant to point a scratch environment at that database.\n'
fi

printf '\n\033[1mReady.\033[0m  npm test   ·   npm run dev\n\n'
